### ISSUE TITLE
Replace loops that iterate over collection with forEach 

### ISSUE THREAD

**Issue by jzgithub1** [apache/accumulo#1023]
This might improve performance on multi-core nodes in some situations.

**Comment by hkeebler** [comment]
It would be good to have a reference list (web page) or something for contributors that contains improvements like this ticket for anyone to consider as they are modifying existing code.  It would likely reduce the number of comment iterations back and forth if there was something to reference when updating (or creating new) code, like 1. What can be changed to a forEach, 2. what can use a method reference, etc.

**Comment by ctubbsii** [comment]
> It would be good to have a reference list (web page) or something for contributors that contains improvements like this ticket for anyone to consider as they are modifying existing code. It would likely reduce the number of comment iterations back and forth if there was something to reference when updating (or creating new) code, like 1. What can be changed to a forEach, 2. what can use a method reference, etc.

Such a page could easily just become a tutorial on the Java language improvements themselves, as new Java versions are released with newer features. Many such pages already exist:

* https://docs.oracle.com/javase/7/docs/technotes/guides/language/enhancements.html#javase7
* https://www.journaldev.com/2389/java-8-features-with-examples
* https://www.azul.com/90-new-features-and-apis-in-jdk-11/

I don't think it should be a goal to reduce comment iterations. I think it's how we (community members) learn things from each other, like new language features (since we can't always keep up with tech changes on our own).

Aside from the language features that are updated and documented elsewhere on the web, what specific added value do you think such a page would have if we were to maintain a page like that ourselves?

**Comment by hkeebler** [comment]
I forget this is an open source project.  Thank you.

**Comment by jzgithub1** [comment]
I think the value of the page would be to let contributors know what our code standards are.  The code review of pull requests ultimately  enforces code standards anyways.  For example, you and others   remind me about the stream API when I check in iterative code so the present system of enforcing code standards does work.

**Comment by ctubbsii** [comment]
Most of what we have that could be called coding standards, are enforced with automation in the build with maven plugins. Most of the rest are "suggestions", "tips", "learned best practices" or even "subjective personal preferences". Deliberation and consensus are more important here than any sort of official coding standards (which change over time).

I'm not opposed to a web page. I just don't know what we'd put on it, and there is some risk of too much documentation (creating haystacks in which to place our needles).

**Comment by DomGarguilo** [comment]
Should #1495 close this issue?

**Comment by ctubbsii** [comment]
@DomGarguilo #1495 probably took care of most of the basic opportunities to make improvements here. There may still be opportunities to use parallel streams and forEach to improve performance in some places, but those would have to be identified on a case-by-case basis, and this issue is too broadly scoped to help in those specific cases. So, I'll close this. Thanks for bringing it to our attention!
