### ISSUE TITLE
Allow multiple tablet merges to occur at once.

### ISSUE THREAD

**Issue by andrewglowacki** [apache/accumulo#1050]
Right now, it appears only one tablet merge can occur at once. In my case, I have a lot of tablets that need to be merged where each takes about 5-10 minutes, making the total time prohibitively large.

I understand merging is a fairly complex activity, but this would be helpful for a users that require merging on a regular basis.

**Comment by ctubbsii** [comment]
Presumably, the 5-10 minutes is because each one is doing a "chop" compaction. You can speed things along by compacting the ranges ahead of time, that will be merged, and then the merge should be fast, but that doesn't save time overall. There was a feature proposal for "no-chop" merges, which would track original tablet boundaries along with file references in the metadata table, so these files wouldn't be read outside their original boundaries, and merging wouldn't need to trigger a compaction to truncate these files, but that was back-burner'd, because it was somewhat involved. It would be nice to revisit that feature for 2.1.

**Comment by keith-turner** [comment]
Chop compactions are part of the problem but not all of the problem.   Below are some other behaviors that can make this process slow.

 * All tablets in the merge range need to have any in memory data minor compacted and then unloaded.  If tablets are actively being written to that could slow this down a bit.
 * The FATE operation that does merge locks the table.   This prevents two merge operations on different ranges of a table from running concurrently.  
 * The shell command that does size based merges only does one range at a time.

Some possible way to improve this are :

 * The merge operation could run chop compaction before starting the merge fate operation OR no-chop merges could be implemented.
 * A range could be added to FATE table locks.  So instead of locking an entire table, a range of a table could be locked OR a merge API that takes a list of ranges could be added.
 * The shell command that does size based merges could submit multiple ranges concurrently.

**Comment by dlmarion** [comment]
@ctubbsii @keith-turner  - Chop compactions were removed in 3.1, right? Merges should definitely be faster in 4.0. Should we assign this to the 4.0 milestone and close this?

**Comment by keith-turner** [comment]
> @ctubbsii @keith-turner - Chop compactions were removed in 3.1, right? Merges should definitely be faster in 4.0. Should we assign this to the 4.0 milestone and close this?

This seems strongly related to #2483.  Given that this issue was motivated primary by merge being slow, I think the no chop changes address that problem and this issue could be closed.

**Comment by ctubbsii** [comment]
Yes, I agree this can be closed.
