### ISSUE TITLE
Review DistributedCache usage (pretty sure it's very broken)

### ISSUE THREAD

**Issue by ctubbsii** [apache/accumulo#1052]
The best explanation (if it even works) of how to use Hadoop's distributed cache is at https://stackoverflow.com/a/26421057/196405

But, I have not tested this.

Our code does not do anything like this.... we tell the distributed cache to add a cache file, but then we just loop through the list of cached URIs, pointlessly, and then reach directly out to the DFS to read it.

All of the Hadoop APIs to read the local cache files are (rightfully) deprecated, because there's no way to map them to the files that were added to the cache. But the APIs to add them to the cache are not deprecated... but they also aren't documented.

We should test the above solution, and if it works, use it, otherwise, completely remove any use of the distributed cache in our MapReduce code.

**Comment by jzgithub1** [comment]
Is this related to the VFS issue #933?

**Comment by ctubbsii** [comment]
@jzgithub1 No. It's unrelated.

**Comment by jzgithub1** [comment]
Working on this now.

**Comment by ctubbsii** [comment]
If we're not using `setSplitFile` in our own code, I'm not surprised, but since it's API, it should at least have a test (UT or IT). We definitely shouldn't change it. `ConfiguratorBase` is not public API, so we're free to change that if necessary, but I don't think even that would need to change for this issue... just it's implementation.

**Comment by jzgithub1** [comment]
Solution for Hadoop DistributedCache an this web page works:  https://stackoverflow.com/a/26421057/196405

I modified the TokenFileIT test to make the these calls on the  hadoop.Job object in the run() method:

 public int run(String[] args) throws Exception {
...
job.addCacheFile(new URI("hdfs://localhost:8020/some_file.json#some"));
job.addCacheFile(new URI("hdfs://localhost:8020/other_file.json#other"));
...
}

I also added an override method for setup(context) in the integrated tests internal hadoop.mapper class like so:

      protected void setup(Context context) throws IOException, InterruptedException {
        if (context.getCacheFiles() != null && context.getCacheFiles().length > 0) {

          File some_file = new File("./some");
          File other_file = new File("./other");

          BufferedReader br = new BufferedReader(new FileReader("./some"));
          try {
            StringBuilder sb = new StringBuilder();
            String line = br.readLine();

            while (line != null) {
              sb.append(line);
              sb.append(System.lineSeparator());
              line = br.readLine();
            }
            String everything = sb.toString();
          } finally {
            br.close();
          }

          // Do things to these two files, like read them
          // or parse as JSON or whatever.
        }
        super.setup(context);
      }

On my command line I added two small json files to HDFS via the commands:
 jzeiberg@dhcp-10-50-230-160  ~/.cache  hdfs dfs -put other_file.json / 
 jzeiberg@dhcp-10-50-230-160  ~/.cache  hdfs dfs -put some_file.json / 

When I ran the code in the debugger I was able to read the contents of the somefile.json in the setup function above using the "some" mnemonic specified by adding #some after the fully qualified hdfs URI in the job.addCacheFile function call.

Since this haddoop distributed cache works the way the stackoverflow webpage says it does I will now proceed to use this distributed cache method where we attempt to use distributed cache elsewhere in our code.

**Comment by ctubbsii** [comment]
If the framework places it in the current working directory when the file is cached locally, it could be a problem for our integration tests, since the current working directory in those cases is `<git-checkout>/test` and not `<git-checkout>/test/target`. If that happens, we'll need to come up with a workaround for our test, so the test doesn't pollute our source tree during a build.

**Comment by ctubbsii** [comment]
Clarification of the desired design:

On job setup (by user):
1. User inputs filename
2. We append mnemonic and create URI
3. We save URI in our config property
4. We tell distributed cache to store URI

On job run (by framework/us):
1. We read our URI from our config property
2. We check to see if we can read file with the mnemonic
3.   if no, we log a warning, and then use URI to read from HDFS directly

**Comment by jzgithub1** [comment]
I think this is done and ready to be merged.
