### ISSUE TITLE
Determine why thrift threaded selector server fails.

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#1076]
After the changes in #1059 the following ITs started to fail.

```
org.apache.accumulo.test.BalanceFasterIT.test
org.apache.accumulo.test.ManySplitIT.test
org.apache.accumulo.test.WaitForBalanceIT.test
org.apache.accumulo.test.functional.ConcurrentDeleteTableIT.testConcurrentFateOpsWithDelete
org.apache.accumulo.test.functional.ConcurrentDeleteTableIT.testConcurrentDeleteTablesOps
org.apache.accumulo.test.functional.CreateAndUseIT.createTableAndBatchScan
org.apache.accumulo.test.functional.DeleteTableDuringSplitIT.test
org.apache.accumulo.test.functional.MetadataMaxFilesIT.test
org.apache.accumulo.test.functional.SimpleBalancerFairnessIT.simpleBalancerFairness
```

Looking into `CreateAndUseIT` the tablet server became unresponsive when the client tried to split the table.   The following was seen in the tablet server log and after that point nothing could connect to the tablet server.

```
2019-04-03 11:50:37,638 [server.TThreadedSelectorServer] ERROR: run() on SelectorThread exiting due to uncaught error
java.nio.channels.CancelledKeyException
        at sun.nio.ch.SelectionKeyImpl.ensureValid(SelectionKeyImpl.java:73)
        at sun.nio.ch.SelectionKeyImpl.interestOps(SelectionKeyImpl.java:82)
        at org.apache.thrift.server.AbstractNonblockingServer$FrameBuffer.changeSelectInterests(AbstractNonblockingServer.java:440)
        at org.apache.thrift.server.AbstractNonblockingServer$AbstractSelectThread.processInterestChanges(AbstractNonblockingServer.java:191)
        at org.apache.thrift.server.TThreadedSelectorServer$SelectorThread.run(TThreadedSelectorServer.java:548)
```

Need to determine if this is a bug in Thrift's TThreadedSelectorServer or the a bug in the way Accumulo is using it.  While this is being investigated #1075 was opened to revert the default thrift sever back to what it was before #1059.  The TThreadedSelectorServer can still be configured.

**Comment by ctubbsii** [comment]
When I ran the ITs with the change, I saw that a lot of things failed due to a `AccumuloSecurityException` with a code of `DEFAULT_SECURITY_ERROR`. There's only a few places in our code where we use that... but on the other hand, its enum value is 0, the default value for a primitive integer... so it's possible some failure modes could set it to 0 when it should be something else.

One possibility is that the SASL parameters on the server type are not `null` when we expect them to be for the non-Kerberos mode. That's one situation that is directly related to the Thrift RPC layer where we use `DEFAULT_SECURITY_ERROR` code.

This is just an idea, though. I haven't investigated further.

**Comment by keith-turner** [comment]
I think I tracked this down.

https://issues.apache.org/jira/browse/THRIFT-4847

**Comment by jzgithub1** [comment]
Well done.

**Comment by cshannon** [comment]
This appears to have been resolved so closing out.
