### ISSUE TITLE
Simplify Maven Pom

### ISSUE THREAD

**Issue by milleruntime** [apache/accumulo#1115]
@EdColeman @mjwall and I were getting frustrated with our Maven build lifecycle the other day and thought it might be nice to simplify the pom down so "mvn clean verify" does the minimum amount of work.

Simplifiying the pom would help with maintainability for the project.  I find myself always running "mvn clean verify -Dspotbugs.skip -DskipTests" which is fine but can still take a while.  For newer developers unfamiliar with Maven appending an absurd amount of "skip" options can be a burden as well.

**Comment by ctubbsii** [comment]
I think it is a mistake to characterize this as a simplification. It would only be simpler for use cases which shortcut important checks. It wouldn't be simpler for the use case of actually running our verification checks. I don't think newer developers unfamiliar with Maven should be appending any skip options. Skipping checks should require some knowledge of what you are doing. The default should not be to skip quality assurance/verification plugins.

The whole point of running through to the `verify` phase is to verify the build... that means running all the verification checks. Users should not be skipping these verification checks unless they know what they are doing. I do not think the default run of `verify` phase should be to run fewer verification checks.

We frequently have developers checking in code which fails verification steps, because they've gotten into the practice of skipping these checks (a bad habit, I think). Skipping verification plugins by default during the verify phase would encourage more of that stuff to fall through, increasing the likelihood of reduced code quality until another developer steps in and closes the gap.

We've already added a `-PskipQA` profile, which was not in favor of. Why is that profile insufficient?

**Comment by milleruntime** [comment]
> We've already added a `-PskipQA` profile, which was not in favor of. Why is that profile insufficient?

I am not sure.  I think that only works running package?

**Comment by ctubbsii** [comment]
Profiles are active for the entire build lifecycle. The contents of the profile may only affect a portion of it, though. In this case, the `skipQA` profile includes mostly stuff that affects plugins after the `package` phase.
