### ISSUE TITLE
Improve HexFormatter scan command

### ISSUE THREAD

**Issue by milleruntime** [apache/accumulo#1138]
scan -fi org.apache.accumulo.core.util.format.HexFormatter -r 313c

is confusing and too long... make it do this:

scan -hex

**Comment by ctubbsii** [comment]
Although this might help the hex formatting case... we probably shouldn't design around a single use case. We have to look at the entire configuration space. Lots of little "convenience options" like this could get unwieldy if we don't draw a line somewhere, because everyone's going to want to get theirs baked in.

This is sort of the problem we got into with aggregator configuration in the shell... we had specialized configs for aggregators... but generalized configs for other iterators, including combiners. Although a bit long, the generalized configs were probably better long-run, rather than try to continue to maintain lots of little one-off specialized configs.

That said, a lot of people deal with binary data in Accumulo, and seeing data encoded as base16, hexadecimal, base32, or base64, might be really useful as a general rule to have baked in, so I wouldn't be opposed if we provided those basic facilities, and drew the line on anything else.

**Comment by milleruntime** [comment]
I only did this to drop the ScanInterpeter stuff

**Comment by keith-turner** [comment]
One option is to deprecate the formatting and interpreter options for 2.0 in the shell and not add the `-hex` option.  Going forward those shell options could be removed.  The deprecation message could ask user to open an issue if they need these features.

**Comment by milleruntime** [comment]
OK so sounds like we don't want a "scan -hex" option but we should deprecate the confusing shell options in 2.0 for possible removal in 2.1?

**Comment by keith-turner** [comment]
Could put the earliest version they would be removed in the message.

**Comment by milleruntime** [comment]
I will wait for feedback from @ctubbsii before making any changes.  I can't tell from his comments if he is for or opposed to this change.

**Comment by ctubbsii** [comment]
I'm not opposed to the change. I'm just confused at the underlying motivation. Is the goal to simplify/consolidate the scan options? Is it to remove the ScanInterpreter because it's confusing? Is it to add a hex output? It's not clear to me what the goal is.

Without understanding what is motivating the specific changes, it's hard for me to fully get behind a solution. So, I'm just trying to offer generic words of caution, so we don't get stuck with something we'll regret later. This specific change feels a bit lateral to me, and not obviously better than what exists now.

Also, none of the current behavior or suggested changes really fix the underlying problem. All of this only exists (and we maintain it) because people want to scan from something like a command-line, and manipulate the output without writing code. Back in 2013, [I suggested](https://issues.apache.org/jira/browse/ACCUMULO-1045) what I think is the best solution for this: separate utilities to replace the shell, so that output can be directly piped to whatever tools users want to use to manipulate their scan output for analysis and/or presentation.

I'd rather we had a scan utility that was independent of "shell" than try to provide an API within the shell for doing stuff in code a user can already do with existing utilities available in their terminal. With the client properties improvements, perhaps it's worth revisiting that now, and deprecating all the scan commands, rather than just specific presentation options? With a stable client API in Accumulo, we don't even have to release this separate utility as often as we release Accumulo. It would just use our public API to read a client config file, create a client, scan, and exit.

**Comment by milleruntime** [comment]
> Is  the goal to simplify/consolidate the scan options? Is it to remove the ScanInterpreter because it's confusing? Is it to add a hex output?

All of the above.

> I'd rather we had a scan utility that was independent of "shell" than try to provide an API within the shell for doing stuff in code a user can already do with existing utilities available in their terminal. With the client properties improvements, perhaps it's worth revisiting that now, and deprecating all the scan commands, rather than just specific presentation options? With a stable client API in Accumulo, we don't even have to release this separate utility as often as we release Accumulo. It would just use our public API to read a client config file, create a client, scan, and exit.

That would be nice.  But you probably spent more time writing this then I spent on this PR.

**Comment by keith-turner** [comment]
I have wanted to experiment with using Accumulo client API in the new JDK11 Java shell.  The easier that is, maybe the less these cumbersome options on the scanner are needed. Also the option to run scripts in the Accumulo shell, which was added after the formatter and interpreters, make these scan options less relevant.

**Comment by milleruntime** [comment]
This could be done for 2.1.  Leaving it open for now.

**Comment by milleruntime** [comment]
Closing in favor of #2787
