### ISSUE TITLE
Merge ServerInfo into ServerContext

### ISSUE THREAD

**Issue by milleruntime** [apache/accumulo#1203]
Refactoring to reduce redundant code and clean up some of the internals between ServerInfo, ServerContext, ClientContext and ClientInfo.  

I have been experimenting and I think this will be a solid refactor.

**Comment by ctubbsii** [comment]
I believe the main reason ClientInfo exists is to avoid reconstructing the AuthenticationToken when passing around client properties internally. (Note: ClientInfo and ServerInfo are internal only, and not public API). It'd be great if these could be refactored to consolidate them. I know @mikewalch had spent some time trying to consolidate client properties/info/context a bit already, but I'm not sure which roadblocks he encountered. I look forward to seeing how this turns out.

**Comment by milleruntime** [comment]
> I believe the main reason ClientInfo exists is to avoid reconstructing the AuthenticationToken when passing around client properties internally. (Note: ClientInfo and ServerInfo are internal only, and not public API). It'd be great if these could be refactored to consolidate them. I know @mikewalch had spent some time trying to consolidate client properties/info/context a bit already, but I'm not sure which roadblocks he encountered. I look forward to seeing how this turns out.

Yeah I think I am basically continuing what he started.

**Comment by milleruntime** [comment]
After doing some cleanup of ServerContext and ClientContext, I don't think this refactor is needed.  ServerInfo is now just internal to ServerContext and needs to exist since it extends ClientInfo.  ClientInfo is used a lot in Tests, mainly where we don't have a full ClientContext.
