### ISSUE TITLE
Garbage Collector problematic use of SimpleTimer

### ISSUE THREAD

**Issue by ctubbsii** [apache/accumulo#1314]
SimpleGarbageCollector creates a new instance of GarbageCollectWriteAheadLogs on each loop. Each construction of GCWAL creates a new LiveTServerSet, which registers a SimpleTimer task to scan for changes in the set of live TServers. This task executes indefinitely, and is never de-registered. Multiple copies of LiveTServerSet are created over time, each registering a new SimpleTimer task that executes indefinitely.

There are several problems here:

1. The tasks are redundant, and never de-registered. So, in GC's main loop, a new SimpleTimer task is created each time... growing indefinitely. We should only need one at any given time.
2. Because of the changes in 1be829848ffc195dbc8c3fa42a4f354d2678645e (#781), the GCWAL's overridden `update` method is called frequently, even when there are no changes in the live TServer set. This results in excessive spam of: "New tablet servers noticed: []" and "Tablet servers removed: []" log messages.

The first problem has been around longer (and might affect other uses of SimpleTimer... we should check), but the second problem was introduced in 1.9.3. Together, this results in an increasing number of timer tasks, each constantly logging to report no changes, easily filling up logs with useless information over time.

Workaround: restart the GC.

**Comment by EdColeman** [comment]
I have two options available for review - one modifies the SimpleTimer to return the Future<> instead of void, implements AutoCloseable to call cancel on the future. (https://github.com/EdColeman/accumulo/tree/gc_thread_issue_1314_close_option)

The second calls scan server directly, the GC task does not appear to do anything with the updates other than log - this avoids the start listening call that creates / schedules the timed task. (https://github.com/EdColeman/accumulo/tree/gc_thread_issue_1314_one_shot_option)

The second is cleaner and solves this immediate problem.  Returning the Future<> may be usefull for other cases where the call back / listener is doing more and calling scanServers directly is not an option - need to examine other SimpleTimer usages,

**Comment by ctubbsii** [comment]
I like option 2. Could maybe make the log message one line, rather than 3 separate messages.

**Comment by ctubbsii** [comment]
Hmm, option 2 isn't going to work as-is... LiveTServerSet gets torn down and reconstructed each cycle of the accumulo-gc, which means every time the accumulo-gc cycles and scanServers is called, this is going to log *every* tserver as new each time it cycles.

Instead, I think we can move LiveTServerSet out into the GC, so there's only ever one copy of that listener. It can be passed in as a parameter to GarbageCollectWriteAheadLogs.

**Comment by ctubbsii** [comment]
I did check the other occurrences of the use of starting that listener. I found 3. The other two occurrences were fine, but I did not check all uses of SimpleTimer.
