### ISSUE TITLE
Handle split points in delete range of metadata table

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#1384]
After the changes in #1365 an upgraded Accumulo instance could have metadata table splits in the ~del range that are irrelevant.  It would be nice to document what users need to do remove these in the release notes.

**Comment by keith-turner** [comment]
Opened apache/accumulo-website#257.  

I experimented with creating the old style ~del splits points in 2.0.1, upgrading, creating new style split, and then merging.  I took some notes from these experiments and stored them at the link below.

https://gist.github.com/keith-turner/9896c511f71d47b06eb8af46ed74b691

**Comment by ctubbsii** [comment]
Is this issue satisfied by the referenced documentation PR, or is there more to do for this?

**Comment by keith-turner** [comment]
> Is this issue satisfied by the referenced documentation PR, or is there more to do for this?

Yeah the referenced website PR satisfies this issue.

**Comment by ctubbsii** [comment]
> Yeah the referenced website PR satisfies this issue. The linked gist is just some notes from experiments I did to collect info to write the PR.

Okay, I'll close this then, since apache/accumulo-website#257 is the intended solution. (For some reason, I thought GitHub had already linked a reference to that PR, but it didn't... it only linked to the commits in the PR, not to the PR itself.)

> I used jshell to run Accumulo code in those experiments, that was neat.

I've used that recently as well. It's nice (assuming the class path is set up, and you know the fluent entry point to the API). I was thinking we might want to write a `bin/accumulo jshell` command to initialize jshell with the Accumulo class path and customized initial imports to make it even easier. A recent new contributor who I know was going through the tour on the website recently, @slackwinner, might be interested in picking that up. I will reach out to them after the (U.S.) holiday weekend, to gauge their interest and will create a separate ticket. Also, the more fluent code we write, the easier jshell is to use, with its tab completion. It might even overtake the value of our current shell at some point.

**Comment by slackwinner** [comment]
@ctubbsii I'd be happy to assist the team with creating the bin/accumulo jshell command if it's needed.

**Comment by ctubbsii** [comment]
> @ctubbsii I'd be happy to assist the team with creating the bin/accumulo jshell command if it's needed.

I created a separate issue to track that at #1870
