### ISSUE TITLE
Create type to represent tablet files

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#1396]
Accumulo tablet files have a very specific structure of `<volume>/tables/<table id>/<tablet dir>/<tablet file>`.  Code that deals with these paths use String or Hadoop Path type along with utility methods to extract needed information and sanity check the paths.  The reason String is used sometimes is that for the case where a path originates from the metadata table, it is extremely important to maintain the exact string that is in the metadata table.  Using Path may transform the String to something different.

Instead of using String and Path, it may be better to create a specialized type that holds this information and sanity checks it.  This type could be used in the code in place of String and Path.  Possibly something like :

```java
class TabletFile {
   Volume getVolume();
   TableId getTableId();
   String getTabletDir();
   String getName();
   Path toPath();
   // returns the exact path storted in metadata table if this path originated from the metadata table
   String getMetadataEntry();
}
```

Ample could use this more specific type instead of String.

**Comment by keith-turner** [comment]
[FileRef](https://github.com/apache/accumulo/blob/4c9429e8563d714fd3997d6b7eb9c7d0e3a8c837/server/base/src/main/java/org/apache/accumulo/server/fs/FileRef.java) is somewhat similar to what is proposed in this issue, but not quite the same.  Looking at FileRef, it would be nice to exclude serialization/deserialization code from TabletFile and make it a data only class.

**Comment by milleruntime** [comment]
Would you also need a member (possibly boolean) to indicate that it is a metadata entry or not?

**Comment by keith-turner** [comment]
> Would you also need a member (possibly boolean) to indicate that it is a metadata entry or not?

Possibly. Or could have a method `Optional<String> getMetadataEntry()`

**Comment by keith-turner** [comment]
@ctubbsii why is this marked as TODO for the 2.1.0 project?

**Comment by ctubbsii** [comment]
> @ctubbsii why is this marked as TODO for the 2.1.0 project?

@keith-turner Because I added it to the `2.1.0` project when I went through to clean up/organize issues/PRs that hadn't been organized by others in the appropriate release project. When adding a project to an issue/PR, the automation sets it to `To do`; normally, it would automatically move to `Done` when it is closed.

However, since I added the project to the issue after it was already closed, I would have to perform a second manual step to mark it as `Done` in the project. Normally I do this second step. For whatever reason, that didn't happen this time (either because of AJAX timeout in GitHub UI or because I simply forgot).

In future, it is best if everybody helps organize issues, by adding the target fix project version prior to it being closed, or manually marking it done immediately following closing it. If I am the only one doing this, some will inevitably slip through the cracks. Others can help by adding projects themselves, and properly marking them as `Done` as needed (or, if an issue is closed as `Won't fix` or similar, then removing it from the project).
