### ISSUE TITLE
Use Bulk import status for new bulk import

### ISSUE THREAD

**Issue by milleruntime** [apache/accumulo#1510]
There is a bulk import status baked into Accumulo for legacy bulk import process.  This gets displayed on the Monitor and was fixed for 2.X [here](https://github.com/apache/accumulo/issues/475).  It would be nice to have this work for the new bulk import and displayed nicely.  Here are the [states](https://github.com/apache/accumulo/blob/3fd5cad92f9b63ac19e4466f3f2d5237b905262c/core/src/main/java/org/apache/accumulo/core/master/thrift/BulkImportState.java#L28) that could be used.

**Comment by ctubbsii** [comment]
Since Accumulo itself does a lot less work on the server side for the new bulk imports, the value in showing status is probably pretty limited (first, because there are fewer server-side states, and second, because they should transition to completion faster), but it may still be worth showing some status.
