### ISSUE TITLE
Add vscode directory/files to .gitignore and apache-rat ignore.

### ISSUE THREAD

**Issue by andrewglowacki** [apache/accumulo#1582]
VSCode creates a .vscode directory and .factorypath files that are flagged by the rat plugin, and git as changes. These should be ignored/excluded

**Comment by ctubbsii** [comment]
@andrewglowacki Are you filing this issue to document it for later, or are you interested in submitting a pull request to address this?

If you're just documenting the issue for potential later work (perhaps by some other volunteer), or if the work might be substantial enough to discuss first, in order to avoid potentially wasted or misdirected effort, then creating an issue first might make sense.

If the latter, especially for very small stuff, there is no need to create an issue first. You can just create the pull request, since pull requests are their own issues on GitHub.

It's up to you. I just wanted to make sure you knew it wasn't required to have a separate ticket for each PR, just for the sake of creating tickets. :smiley_cat:

**Comment by andrewglowacki** [comment]
Whoops! Yea, I'm going to submit a PR when this build is complete. I wasn't sure, but next time I'll just submit a PR. Thanks for the clarification!

**Comment by ctubbsii** [comment]
> Whoops! Yea, I'm going to submit a PR when this build is complete. I wasn't sure, but next time I'll just submit a PR. Thanks for the clarification!

No problem. Just trying to make sure people don't do more work than they have to. Thanks for contributing! :smiley_cat:
