### ISSUE TITLE
Prepare for 1.10 release.

### ISSUE THREAD

**Issue by EdColeman** [apache/accumulo#1673]
This issue is to track outstanding issues / work that is required for a 1.10 release.  Initial efforts for a release were started in Jan/Feb but have been sidetracked and I'd like restart the process.

ToDos:
- release notes - draft available since Feb, updated 6 Aug with most recent changes.
- Two open Issues tagged blocker:
    -  #1298 Exception when attempting to get the next filename left tablet in bad state
    - #1086 ZooLock uses ZooReader which may retry on session expired

**Comment by keith-turner** [comment]
@EdColeman  and @milleruntime I marked #1086 a blocker because I was hoping to work on it before 1.10.  However, not sure I will be able to do that depending on the release time frame.  Given that #1086 is likely an issue that predates 1.9 and is not newly introduced between 1.9 and 1.10, it does not have to be a blocker for 1.10 (it would be nice to keep on the radar somehow though).   I am going to look into #1298 soon.

**Comment by EdColeman** [comment]
Thanks. As far as time frame, I was hoping the community would agree on something like "by the end of the month (August)"  If #1086 is still open, I assume that we can keep it as a blocker for 2.1 to give more visibility.

**Comment by milleruntime** [comment]
As a reference, here is the PR for the release notes: https://github.com/apache/accumulo-website/pull/218
I had forgot you already did the release notes... and I even reviewed them haha!

**Comment by milleruntime** [comment]
Something that I think is good to do before a release is update all the minor dependencies.  The maven versions plugin is great for checking this: ```mvn versions:display-dependency-updates```.  Some "minor" version upgrades are not possible or require more work so they won't be feasible at the end of the development cycle.  Here are some we should check (feel free to ping me with a "No Way Jose" and I will cross them off, I already eliminated the obvious major ones):

```
[INFO]   com.beust:jcommander .................................... 1.48 -> 1.78
[INFO]   com.google.auto.service:auto-service .............. 1.0-rc3 -> 1.0-rc7
[INFO]   com.google.code.gson:gson ............................... 2.7 -> 2.8.6
[INFO]   commons-cli:commons-cli ................................... 1.2 -> 1.4
[INFO]   commons-codec:commons-codec .............................. 1.4 -> 1.14
[INFO]   commons-collections:commons-collections ............ 3.2.2 -> 20040616
[INFO]   commons-configuration:commons-configuration .............. 1.6 -> 1.10
[INFO]   commons-io:commons-io ..................................... 2.4 -> 2.7
[INFO]   commons-lang:commons-lang ................................. 2.4 -> 2.6
[INFO]   commons-logging:commons-logging ......................... 1.1.1 -> 1.2
[INFO]   jline:jline ......................................... 2.11 -> 3.0.0.M1
[INFO]   junit:junit ............................................. 4.12 -> 4.13
[INFO]   org.apache.commons:commons-jci-core ....................... 1.0 -> 1.1
[INFO]   org.apache.commons:commons-jci-fam ........................ 1.0 -> 1.1
[INFO]   org.apache.commons:commons-lang3 ......................... 3.1 -> 3.11
[INFO]   org.apache.commons:commons-vfs2 ......................... 2.3 -> 2.6.0
[INFO]   org.bouncycastle:bcpkix-jdk15on ......................... 1.62 -> 1.66
[INFO]   org.bouncycastle:bcprov-jdk15on ......................... 1.62 -> 1.66
[INFO]   org.easymock:easymock ................................... 4.0.2 -> 4.2
[INFO]   org.eclipse.jetty:jetty-http ........ 9.2.26.v20180806 -> 11.0.0.beta1
[INFO]   org.eclipse.jetty:jetty-io .......... 9.2.26.v20180806 -> 11.0.0.beta1
[INFO]   org.eclipse.jetty:jetty-security .... 9.2.26.v20180806 -> 11.0.0.beta1
[INFO]   org.eclipse.jetty:jetty-server ...... 9.2.26.v20180806 -> 11.0.0.beta1
[INFO]   org.eclipse.jetty:jetty-servlet ..... 9.2.26.v20180806 -> 11.0.0.beta1
[INFO]   org.eclipse.jetty:jetty-util ........ 9.2.26.v20180806 -> 11.0.0.beta1
[INFO]   org.gaul:modernizer-maven-annotations ................. 1.8.0 -> 2.1.0
[INFO]   org.powermock:powermock-api-easymock .................. 2.0.2 -> 2.0.7
[INFO]   org.powermock:powermock-core .......................... 2.0.2 -> 2.0.7
[INFO]   org.powermock:powermock-module-junit4 ................. 2.0.2 -> 2.0.7
[INFO]   org.powermock:powermock-reflect ....................... 2.0.2 -> 2.0.7
```

**Comment by ctubbsii** [comment]
> [INFO]   com.beust:jcommander .................................... 1.48 -> 1.78

There's breaking changes in newer jcommander, and is not safe to update in 1.x I think.

> [INFO]   com.google.auto.service:auto-service .............. 1.0-rc3 -> 1.0-rc7
> [INFO]   com.google.code.gson:gson ............................... 2.7 -> 2.8.6
> [INFO]   commons-cli:commons-cli ................................... 1.2 -> 1.4
> [INFO]   commons-codec:commons-codec .............................. 1.4 -> 1.14

These should be fine, in general, but we should be careful about the `commons-*` ones. Some are riskier than others, and some we expect to be provided by, or matching, whatever Hadoop has. This is still an issue for Hadoop 2.x, and less so in Hadoop 3.x, where they have shaded much of their deps. In any case, 1.10 is supposed to be a stabilizing release, not one that could introduce weird dependency-related bugs.

> [INFO]   commons-collections:commons-collections ............ 3.2.2 -> 20040616

This is clearly not a newer version. :smiley_cat:

> [INFO]   commons-configuration:commons-configuration .............. 1.6 -> 1.10

I believe commons-configuration 1.10 ships some breaking changes. We've already updated in the main branch. I'd punt this one.

> [INFO]   commons-io:commons-io ..................................... 2.4 -> 2.7
> [INFO]   commons-lang:commons-lang ................................. 2.4 -> 2.6
> [INFO]   commons-logging:commons-logging ......................... 1.1.1 -> 1.2

Same comment above regarding being careful about `commons-*`.

> [INFO]   jline:jline ......................................... 2.11 -> 3.0.0.M1

This one is likely going to break the shell.

> [INFO]   junit:junit ............................................. 4.12 -> 4.13

This one will introduce a bunch of warnings, that have already been triaged in the main branch and updated there. It's a test dependency and not important to update here.

> [INFO]   org.apache.commons:commons-jci-core ....................... 1.0 -> 1.1
> [INFO]   org.apache.commons:commons-jci-fam ........................ 1.0 -> 1.1
> [INFO]   org.apache.commons:commons-lang3 ......................... 3.1 -> 3.11
> [INFO]   org.apache.commons:commons-vfs2 ......................... 2.3 -> 2.6.0

More commons dependencies to be careful about.

> [INFO]   org.bouncycastle:bcpkix-jdk15on ......................... 1.62 -> 1.66
> [INFO]   org.bouncycastle:bcprov-jdk15on ......................... 1.62 -> 1.66

Bouncycastle should be updated whenever we can, but I'm not even sure we still need it in newer JDKs. In any case, I believe this is a test dep, so it's probably fine.

> [INFO]   org.easymock:easymock ................................... 4.0.2 -> 4.2

Yes, if it doesn't break anything or introduce a bunch of warnings. I believe we've already updated the main branch.

> [INFO]   org.eclipse.jetty:jetty-http ........ 9.2.26.v20180806 -> 11.0.0.beta1
> [INFO]   org.eclipse.jetty:jetty-io .......... 9.2.26.v20180806 -> 11.0.0.beta1
> [INFO]   org.eclipse.jetty:jetty-security .... 9.2.26.v20180806 -> 11.0.0.beta1
> [INFO]   org.eclipse.jetty:jetty-server ...... 9.2.26.v20180806 -> 11.0.0.beta1
> [INFO]   org.eclipse.jetty:jetty-servlet ..... 9.2.26.v20180806 -> 11.0.0.beta1
> [INFO]   org.eclipse.jetty:jetty-util ........ 9.2.26.v20180806 -> 11.0.0.beta1

I believe this is the last jetty that still supported Java 7. Since we now use Java 8 for the 1.10 branch, we can update, but not to a beta, and it won't be easy. All jetty updates seem to have breaking changes. I would pass on these.

> [INFO]   org.gaul:modernizer-maven-annotations ................. 1.8.0 -> 2.1.0

We can update any test/build tooling without much risk, so this one is fine to update, as is anything found by `mvn versions:display-plugin-updates`. However, there's diminishing returns on the effort, since we've already gone through a lot of this in the main branch already, and I'm not sure how much benefit there is to updating 1.10 when we're trying to stabilize it.

> [INFO]   org.powermock:powermock-api-easymock .................. 2.0.2 -> 2.0.7
> [INFO]   org.powermock:powermock-core .......................... 2.0.2 -> 2.0.7
> [INFO]   org.powermock:powermock-module-junit4 ................. 2.0.2 -> 2.0.7
> [INFO]   org.powermock:powermock-reflect ....................... 2.0.2 -> 2.0.7

Test deps are fair game, but might require code changes.

----
In general, I'm in favor of updating plugin versions whenever we can, and test dependencies, too. Other deps need to be considered carefully, especially in maintenance branches where the risk of destabilizing things is greater.


Also, should this have been a separate issue? :smiley_cat:

**Comment by milleruntime** [comment]
> Also, should this have been a separate issue? 

Probably but I wasn't sure what was the point of this ticket other than to link to other tickets.  Which I thought we already were accomplishing with GitHub Projects...

**Comment by EdColeman** [comment]
I was hoping to use this as sort of a white board to pass info concerning the release.  I was looking for something more accessible than email that we could use to track different efforts towards the release between ourselves and those that may be interested in the release to see what has been accomplished and what remains.  
I guess I envisioned something like a kanban board tracking of tasks and progress.  Not so much for individual issue resolution, just a place to link those that are impacting the 1.10 release.  Maybe there's a better way to this with something in github, but this seemed to be a low-bar approach to try.

**Comment by milleruntime** [comment]
> Also, should this have been a separate issue? 

I deleted some of my comments and opened a separate issue in #1685 .  Sorry for cluttering up this one.

**Comment by milleruntime** [comment]
FYI there was an issue with the first RC: https://github.com/apache/accumulo/pull/1692
It was fixed with that PR and an RC2 has been created for testing.
