### ISSUE TITLE
Parallelize calls to InstanceOperations.getActiveCompactions() in listcompactions shell command

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#1764]
The shell command to list compactions gets a list of tservers and then for each tserver it calls InstanceOperations.getActiveCompactions() which makes an RPC to the tserver.  This could be slow for many tservers.  The calls to getActiveCompactions() for multiple tservers could be done in parallel.

**Comment by ctubbsii** [comment]
@keith-turner Would this be a `good first issue`? It seems pretty straight-forward.

**Comment by keith-turner** [comment]
> @keith-turner Would this be a good first issue? It seems pretty straight-forward.

@ctubbsii the following code calls getActiveCompactions().  The code is self contained, but it being in this iterator complicates parallelizing it a bit.

https://github.com/apache/accumulo/blob/d820360b975de759b1575d68456e69c828225a85/shell/src/main/java/org/apache/accumulo/shell/commands/ActiveCompactionIterator.java#L64

**Comment by ctubbsii** [comment]
I [saw another way to do it with a custom executor](https://4comprehension.com/parallel-collection-processing-1/), rather than specifically requiring a ForkJoinPool:
```java
stream.map(i -> CompletableFuture.supplyAsync(() -> process(i), executor)).collect(
  collectingAndThen(toList(), list -> list.stream().map(CompletableFuture::join).collect(toList()))
);
```
This submits all the tasks to an executor, then collects all the futures, then joins all the futures into the list of final results. Exception handling is tricky, but I imagine that it's tricky with parallel streams and ForkJoinPool also.

**Comment by keith-turner** [comment]
One possible way to implement this is :

 * Move the code in ActiveCompactionItertator that converts an ActiveCompaction object to a display string into a function called `toDisplay(ActiveCompaction)`.
 * Replace this [line](https://github.com/apache/accumulo/blob/d820360b975de759b1575d68456e69c828225a85/shell/src/main/java/org/apache/accumulo/shell/commands/ListCompactionsCommand.java#L67) with a stream.
 * Remove the ActiveCompactionIterator class

The code for stream could look like the following.

```java
    String finalFilterText = filterText;
    Predicate<String> textFilter = finalFilterText == null ? t -> true : t -> t.matches(finalFilterText);
    
    Iterator<String> activeCompactionIterator = tservers.stream().map(tserver -> CompletableFuture.supplyAsync(() -> {
      try {
        return instanceOps.getActiveCompactions(tserver);
      } catch (Exception e) {
        throw new RuntimeException(e);
      }
    }, executor)).flatMap(cf -> cf.join().stream()).map(ac -> toDisplay(ac)).filter(textFilter)
        .iterator();
```

However this solution drops one thing the current code is doing. The current code sorts each tservers active compactions by age.

**Comment by ctubbsii** [comment]
> I am uncertain if the stream will have the same order as the current iterator class, I am not sure if tservers will stay grouped together in output and if the age order created inside flatMap will be preserved.

It looks like the order of this one will depend on which tservers respond first, but within a tserver, it looks like they'll still be grouped and ordered correctly within a tserver. They could be grouped and sorted by tserver with an intermediate multimap or something, though.

While I don't think the flatMap will mess with the ordering, it does look like it will prevent parallelization, without using the collector strategy I mentioned above. Otherwise, the first item will call go through `map`, `flatMap`, `map`, `filter`, and `iterator` on the first call to `next` in the iterator... and the second one will wait until `next` is called again. This is what the collector strategy I posted above avoids... it ensures all of them are iterated, during the `collect` phase, and then operates on the collection with the `collectingAndThen` special-purpose collector.

**Comment by keith-turner** [comment]
> While I don't think the flatMap will mess with the ordering, it does look like it will prevent parallelization, without using the collector strategy I mentioned above.

Good catch, I was thinking the stream would buffer some between steps.   But there is no good reason the stream should do that.  I attempted to explicitly force buffering of all the futures in the stream below.

```java
    String finalFilterText = filterText;
    Predicate<String> textFilter = finalFilterText == null ? t -> true : t -> t.matches(finalFilterText);
    
    Comparator<ActiveCompaction> acComp =
        Comparator.comparingLong(ActiveCompaction::getAge).reversed();

   // The following stream buffers all futures mid stream before proceeding to ensure all tservers are submitted to executor
    Iterator<String> activeCompactionIterator =
        tservers.stream().map(tserver -> CompletableFuture.supplyAsync(() -> {
          try {
            return instanceOps.getActiveCompactions(tserver);
          } catch (Exception e) {
            throw new RuntimeException(e);
          }
        }, executor)).collect(toList()).stream() 
             .flatMap(cf -> cf.join().stream().sorted(acComp)).map(ac -> toDisplay(ac))
            .filter(textFilter).iterator();
```
