### ISSUE TITLE
Check for consistency of shell commands that operate on a table.

### ISSUE THREAD

**Issue by jmark99** [apache/accumulo#1776]
There have been recent updates to several shell commands that operate on tables for the purpose of adding the <code>--table/-t</code> option. This option allows a specified table to be the target of the command. This can be useful in situations where the shell command is not be within a table context or if the command needs to operate on a table other than the current table context. It is also especially helpful if using shell commands within a script where it is not possible to provide a table context.

It was suggested that all shell commands that operate on tables should be reviewed and the <code>table/t</code> options be added, if missing, thereby making all table-related shell commands consistent.

This ticket will examine the table-related shell commands to see if they provide a means to indicate the table name. The 'insert' command was updated recently to add the ability to supply a target table. In all, there are 39 shell commands that can take a table name parameter. Each of the 39 should allow a table name to be supplied.

For completeness, the commands are listed here:

deleteiter, deletescaniter, listiter, setiter, setscaniter, grant, revoke, config, deletetable, droptable, du, exporttable, offline, online, summaries, addsplits, compact, constraint, flush, getgroups, getsplits, merge, setgroups, delete, deletemany, deleterows, egrep, formatter, interpreter, grep, importdirectory, insert, maxrow, scan, table, clonetable, createtable, importtable, and renametable.

All but the last six listed above allow the table to be supplied using the -t/--table prefix. The final six do not use of the -t/--table prefix. There are eight that allow the table name to be supplied using both the -t/--table prefix or just the table name (deletetable, droptable, du, offline, online, summaries, compact, and flush).

**Comment by EdColeman** [comment]
Mark, thanks for picking this up - when scripting, needed to switch into a table before being able to run a command was a pain point.  

As for then it comes to requiring or having -t as an option on the remaining six - my inclination is to always have -t available so the commands take consistent input rather than needing to remember that those six are outliers.  However, there are two that stand out - clonetable and renametable - they take two table names so if only -t was added it could leave confusion unless there was -t (source?) and -n (destination) or something. Without two switches, what table is specified by -t (I'd assume the source, but...)

With these six, the intent is clear that they require a table name, so its fine either way - just wanted to weigh my preference is for consistency over brevity when possible.  For me, the extra typing required if -t was always required is less mental effort than needing to remember when -t not available.

**Comment by jmark99** [comment]
I tend to side with the consistency argument that you present. Granted, with the commands that do not have the option, it is pretty clear that a table name is required. So I can go either way. @ctubbsii commented on the PR with his preference if you would like to take a look. You are correct that the clonetable and renametable would have to be handled slightly differently. Perhaps a few others can weigh in before we decide if we should proceed with additional work. As @ctubbsii pointed out, it could be confusing to have commands that can work without the option as well as taking the option. But it is not unprecedented as eight of the commands already do that.

**Comment by ctubbsii** [comment]
The main concern with adding the option when it's already a required argument is confusion. A user might not know which to specify. They might specify both. What if the user specified both and they were different?! We'd have to add unnecessary complexity to report errors in those cases that we can avoid by limiting it to just the existing required arguments in those cases. I also prefer consistency, but another way to adhere to consistency is to be consistent between versions, rather than be consistent between commands. For those commands, since the required argument is already present, and it would add confusion and complexity to handle, I'm inclined to prefer consistency with previous versions. The scripting use case already works for these, so there's little compelling reason to at the option to these, in my opinion. But, if they are added, it can be done in a separate PR.
