### ISSUE TITLE
Monitor will always report Error on startup

### ISSUE THREAD

**Issue by milleruntime** [apache/accumulo#1777]
When starting up an Accumulo cluster, the Monitor will always report the Error "Unable to get info from Master", mostly because it will start up faster than the master.  It shouldn't be that difficult to add a bit of code to delay the error reporting until the Master is initially available.

**Comment by ctubbsii** [comment]
This is a cluster-startup timing issue only, and depends on how the cluster is started. The monitor is doing the correct behavior today... the master isn't up, so it says it's not up. The monitor is not wrong about that.

If we introduce a small delay in the monitor before it starts up, that might be okay... but it should not wait indefinitely for the master to be available initially, because it may never be available.

However, by doing so, we risk the monitor failing (or delaying) to report a valid problem when the monitor itself is restarted and the rest of the system is expected to be up. The monitor doesn't know what state the rest of the cluster is in, so it doesn't know if it is starting up alone or along with the rest of the cluster.

Since cluster startup is more rare than individual node startup, I'm inclined to just not fix this issue... as it's reporting a valid transient issue. After all, it's not that hard to wait a few seconds and refresh.

**Comment by milleruntime** [comment]
> This is a cluster-startup timing issue only, and depends on how the cluster is started. The monitor is doing the correct behavior today... the master isn't up, so it says it's not up. The monitor is not wrong about that.
> 
> If we introduce a small delay in the monitor before it starts up, that might be okay... but it should not wait indefinitely for the master to be available initially, because it may never be available.
> 
> However, by doing so, we risk the monitor failing (or delaying) to report a valid problem when the monitor itself is restarted and the rest of the system is expected to be up. The monitor doesn't know what state the rest of the cluster is in, so it doesn't know if it is starting up alone or along with the rest of the cluster.
> 
> Since cluster startup is more rare than individual node startup, I'm inclined to just not fix this issue... as it's reporting a valid transient issue. After all, it's not that hard to wait a few seconds and refresh.

That is fair.  I just thought it might be nice to not have any errors show up on a perfectly clean cluster with no data.

**Comment by ctubbsii** [comment]
> That is fair. I just thought it might be nice to not have any errors show up on a perfectly clean cluster with no data.

It might be best to just modify the cluster management scripts you're using to wait a few seconds before starting up the monitor.

**Comment by milleruntime** [comment]
Well @ctubbsii I was trying to create an easy issue for newcomers but you had to make me look into it and test it myself... https://github.com/apache/accumulo/pull/1778
