### ISSUE TITLE
To Halt or not when Error seen in AccumuloUncaughtExceptionHandler

### ISSUE THREAD

**Issue by dlmarion** [apache/accumulo#1874]
There was a [discussion](https://github.com/apache/accumulo/pull/1818#discussion_r543599320) in a previous PR regarding whether or not the VM should be halted when an [Error](https://docs.oracle.com/javase/7/docs/api/java/lang/Error.html) is thrown in a Thread.

Issue assigned to interested parties and a cc to @FineAndDandy

**Comment by dlmarion** [comment]
Relevant code is [here](https://github.com/apache/accumulo/blob/main/core/src/main/java/org/apache/accumulo/core/util/threads/AccumuloUncaughtExceptionHandler.java)

**Comment by ctubbsii** [comment]
@dlmarion I'm going to close this issue for a few reasons:

1. it doesn't represent anything actionable to do, and therefore isn't very good as an issue in our issue tracker,
2. it's not a good idea to assign tasks to others, even just to try to tag them, because ASF is composed of volunteers, and people should be able to opt-in to tasks, rather than have it assigned to them, and
3. tagging a select group of people without asking them a specific question or responding to them is not good practice, even if they've previously expressed interested; it could be seen as spamming those no longer interested in a topic, or could be interpreted as excluding others who might be interested,

If you're trying to initiate a discussion, the best place to do that within the Apache Software Foundation is with a discussion thread on a project's dev mailing list. That is the standard, community-inclusive way to create a dialogue in an Apache community, especially if there is large-scale or substantially impactful design decision-making to be done.

**Comment by dlmarion** [comment]
@ctubbsii - Should we get rid of the `Question` issue type then?

**Comment by ctubbsii** [comment]
> @ctubbsii - Should we get rid of the `Question` issue type then?

The Question label is a built-in one that is created by default by GitHub when you enable issues on a GitHub repository. It can be deleted, but I wouldn't, because it is useful to use it when users ask questions on our project issue tracker. We have no control over what issues users might create, so it's useful to have a label so we can use it to distinguish their questions from actionable items. When users do that, we can either answer and close, or we can recommend they contact the mailing list. Either way, it's still useful to have the label, so we can separate them from other issues.
