### ISSUE TITLE
Null pointer exception encountered in code that worked in 1.9.2

### ISSUE THREAD

**Issue by alerman** [apache/accumulo#1889]
We encountered an NPE in the init method of combiner. We were sending in null as the ENV and in 1.9.2 that did not cause issues as the method returned prior to this line. @milleruntime I believe you made those changes and I am not sure what should occur if it is null so hoping you will take a look

https://github.com/apache/accumulo/blob/6af856b38bb57f49418547a8b9c262c66a1fe31e/core/src/main/java/org/apache/accumulo/core/iterators/Combiner.java#L293

**Comment by ctubbsii** [comment]
@alerman The environment is provided to the iterator by Accumulo itself, and Accumulo should never provide a null environment. What is the use case for supporting the receipt of a null environment rather than recognizing that as an exception? Is it for testing your iterator? If so, why not create a mock environment?

**Comment by alerman** [comment]
@ctubbsii In this case our code was calling the init function itself. I can see the argument that we shouldnt be doing that but 1) its public and 2) this worked in 1.9.x and it is a behavior change in a minor release. I have put up a PR to our codebase to have it send in an empty environment rather than null, so this won't affect us any longer, but this could still affect anyone else that was doing it.

**Comment by milleruntime** [comment]
@alerman I am not sure what change you are refering to but the bug fix I did for the Combiner was in 1.10.  PR: https://github.com/apache/accumulo/pull/1680
And here is the commit: e3a14cd083848917b1f3f739eb79e6ea65a3e704

**Comment by alerman** [comment]
reopened as I had closed by mistake.

**Comment by ctubbsii** [comment]
Since this was re-opened, I will reply to the points that were made:

> 1) its public

The fact that the method is public says nothing about whether the arguments can be null, and in the absence of documentation (javadoc, annotations, etc.), the behavior is not defined. The behavior didn't break... a user's invalid assumption was broken. However, in this case, the API is clearly designed to be called by Accumulo, which always provides an concrete environment. It isn't designed for the user to call init themselves, never mind pass null. Rather, it is designed for a user to implement an initialization *given* an environment (which Accumulo provides, and is never null). So, given the design that Accumulo provides the argument, it's not surprising that we didn't document requirements for the argument for the user to pass, but we can address that with updated javadoc in SortedKeyValueIterator, if necessary.

Other than testing, I have not seen a use case articulated for a user calling init themselves, and for testing, one should simulate what Accumulo might provide with a mock environment. If there is a use case, I'd have to understand it better before suggesting a solution beyond updating the javadoc.

> 2) this worked in 1.9.x and it is a behavior change in a minor release. 

I'm not so sure it did work in 1.9. The use of the environment to check the scope of the major compaction was added in 1.6.5 and 1.7.1 to fix a serious bug. See https://issues.apache.org/jira/browse/ACCUMULO-2232 . The code may have been re-ordered more recently to manifest itself earlier, but the expectation that the environment be non-null has been baked into this method's implementation for a very long time.

Even if it did work in 1.9, it was only because of an invalid user assumption that it was safe to call the method themselves with a null argument. Accumulo's own behavior has not changed, because it always provided a non-null environment.

**Comment by ctubbsii** [comment]
In short, I don't think there's a bug here, or any code to fix. But, it may be helpful to improve SortedKeyValueIterator's javadoc for the init method.
