### ISSUE TITLE
Manager specific max message size

### ISSUE THREAD

**Issue by Manno15** [apache/accumulo#1902]
In relation to [ACCUMULO-2352](https://issues.apache.org/jira/browse/ACCUMULO-2352). Issue proposes implementing a specific manager max message size over defaulting the use to `general_max_message_size`. Similar to the specific Tserver one. Before I implement it, I want to see if this is still a desired feature or not considering the age of the original ticket.

**Comment by dlmarion** [comment]
So, https://issues.apache.org/jira/browse/ACCUMULO-2360 implemented a fix for large messages so that an OOME does not occur. https://issues.apache.org/jira/browse/ACCUMULO-2367 suggests that each service should have its own configurable thrift buffer pools. https://issues.apache.org/jira/browse/ACCUMULO-2352 is for adding one to the master specifically. I have the following questions:

1. What's the downside to the Manager using a larger than needed buffer?
2. What's the optimal size for the buffer for the Manager?
3. What's the side effect if a user makes it too small?

If the answer to #1 is "none" or something similar then I would suggest that we don't implement this change for several reasons.

**Comment by ctubbsii** [comment]
> ACCUMULO-2367 suggests that each service should have its own configurable thrift buffer pools.

I don't think this has really been a problem. The 2367 was pretty speculative about the possible benefits from this.

> If the answer to #1 is "none" or something similar then I would suggest that we don't implement this change for several reasons.

I think the downside is probably small to none. If this hasn't been a problem since 2014 when the issue was created, I'm inclined to recommend closing this and ACCUMULO-2367 as "not a problem".

**Comment by dlmarion** [comment]
+1 to closing.

**Comment by Manno15** [comment]
I am open to closing both. I will leave this open until tomorrow in case anyone else wants to add in their feedback and opinions.

**Comment by Manno15** [comment]
Closing as per the discussion above. If anyone has additional comments or feedback, they can still comment on this issue thread.
