### ISSUE TITLE
TinyLfu cache manager hangs in accumulo 2.0.1

### ISSUE THREAD

**Issue by mfmettler** [apache/accumulo#1975]
We've tried testing Datawave with Accumulo 2.0.1 with the
TinyLfuBlockCacheManager and the tservers hang under load within a few
minutes.  It reproduces every time.  This same configuration and tests
run fine with LruBlockCacheManager.  Our configuration includes

```
default    | table.cache.block.enable .......................... | false
system     |    @override ...................................... | true
default    | table.cache.index.enable .......................... | true

default    | tserver.cache.data.size ........................... | 10%
site       |    @override ...................................... | 2G
system     |    @override ...................................... | 4G
default    | tserver.cache.index.size .......................... | 25%
site       |    @override ...................................... | 2G
system     |    @override ...................................... | 1G
default    | tserver.cache.manager.class ....................... | org.apache.accumulo.core.file.blockfile.cache.lru.LruBlockCacheManager
system     |    @override ...................................... | org.apache.accumulo.core.file.blockfile.cache.tinylfu.TinyLfuBlockCacheManager
```

We're testing on a 10 worker, 2 manager node configuration on amazon aws.

CentOS Linux release 7.7.1908 (Core)
Hadoop 3.0.0-cdh6.3.1
Accumulo 2.0.1

We can, but don't need to, use Datawave to supply load and hang.  We can
also cause a hang by running a stand-alone test program and iterators
on the tables written out by Datawave.

Accumulo starts out okay, after a restart to install TinyLfuBlockCacheManager,
runs for a few minutes, and hangs.  CPU load on the workers falls to zero.
There is a long list of scans reported in ashell, but they just sit there
not completing.  The search running at the time of the hang doesn't error
out, but it doesn't complete either.  The tserver logfiles just go quiet.
No errors, no warnings, no messages.  

You can still connect to accumulo and attempt to start another query, and
it will start, but then hangs, and never finishes.  We are able to use
the ashell to configure tserver.cache.manager.class back to 
LruBlockCacheManager for the next restart.

If there is additional information that would be helpful, please let 
us know.

**Comment by ben-manes** [comment]
I would guess that you are observing a livelock due to recursive `computeIfAbsent` calls being unsupported by `ConcurrentHashMap`. You can verify this using jstack.

The TinyLFU cache uses this method for the loader calls,

https://github.com/apache/accumulo/blob/1dc72fce2c781dee597c8c11876a3bc6c321c199/core/src/main/java/org/apache/accumulo/core/file/blockfile/cache/tinylfu/TinyLfuBlockCache.java#L251-L254

In comparison, the Lru cache does this using the racy get-load-put idiom,

https://github.com/apache/accumulo/blob/1dc72fce2c781dee597c8c11876a3bc6c321c199/core/src/main/java/org/apache/accumulo/core/file/blockfile/cache/lru/SynchronousLoadingBlockCache.java#L73-L83

The benefit of `computeIfAbsent` is that it protects against [cache stampedes](https://medium.com/@DoorDash/avoiding-cache-stampede-at-doordash-55bbf596d94b). If this can be recursive, then it should be updated to the racy style like the Lru cache.

**Comment by keith-ratcliffe** [comment]
@ben-manes Thanks. I believe you are correct. Here's a jstack exerpt showing a deadlock that we experienced...
```
at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
"User: **** Start: 1612279224878 Client: xxx.xxx.xxx.xxx:41554 Tablet: f;20190610_21;20190610_20":
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x000000052ae8b878> (a java.util.concurrent.locks.ReentrantLock$NonfairSync)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(AbstractQueuedSynchronizer.java:870)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:1199)
        at java.util.concurrent.locks.ReentrantLock$NonfairSync.lock(ReentrantLock.java:209)
        at java.util.concurrent.locks.ReentrantLock.lock(ReentrantLock.java:285)
        at com.github.benmanes.caffeine.cache.BoundedLocalCache$BoundedPolicy$BoundedEviction.getMaximum(BoundedLocalCache.java:3454)
        at org.apache.accumulo.core.file.blockfile.cache.tinylfu.TinyLfuBlockCache.load(TinyLfuBlockCache.java:204)
        at org.apache.accumulo.core.file.blockfile.cache.tinylfu.TinyLfuBlockCache.lambda$getBlock$2(TinyLfuBlockCache.java:238)
        at org.apache.accumulo.core.file.blockfile.cache.tinylfu.TinyLfuBlockCache$$Lambda$129/316262722.apply(Unknown Source)
        at com.github.benmanes.caffeine.cache.LocalCache.lambda$statsAware$0(LocalCache.java:142)
        at com.github.benmanes.caffeine.cache.LocalCache$$Lambda$130/304458428.apply(Unknown Source)
        at com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$14(BoundedLocalCache.java:2337)
        at com.github.benmanes.caffeine.cache.BoundedLocalCache$$Lambda$131/899711363.apply(Unknown Source)
        at java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1892)
        - locked <0x0000000685ba4df0> (a java.util.concurrent.ConcurrentHashMap$Node)
        at com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2335)
```

**Comment by ben-manes** [comment]
This might be slightly different, but similar.

https://github.com/apache/accumulo/blob/1dc72fce2c781dee597c8c11876a3bc6c321c199/core/src/main/java/org/apache/accumulo/core/file/blockfile/cache/tinylfu/TinyLfuBlockCache.java#L202-L209

This calls `policy.getMaximum()` which currently reads under the eviction policy's lock as it is a non-volatile field. That called under the a `ConcurrentHashMap#compute` method, which takes a lock on the hashbin. If another thread is evicting, it would hold the policy lock and a hash collision might require the same hashbin lock for the entry's removal. This would cause the deadlock you are seeing.

One solution is to store the maxSize as a local variable, since it is never changed. I suppose the policy's accessor was used for convenience.

Another option is if Caffeine made this field a volatile so it could be read lock-free. That wasn't done since its otherwise used under the lock (being set, eviction) and policy methods are not expected to be called frequently. There are other methods on policy that need the lock, so we could only solves a few simple cases.

In this case, I think stashing the maximum size as a final field would be simplest and not require a dependency to be released.

**Comment by ctubbsii** [comment]
@ben-manes @keith-ratcliffe @mfmettler See #2158 as a proposed fix for this.

**Comment by keith-ratcliffe** [comment]
Will try out this patch on our cluster soon and let you know. Thanks!

**Comment by keith-ratcliffe** [comment]
@ctubbsii, this does indeed appear to be fixed. After applying your #2158 changes to accumulo-core (on rel/2.0.1), the issue has so far not resurfaced while testing DataWave on our cluster.

Steps to verify:
1. Patch accumulo-core-2.0.1.jar and update on all worker nodes
2. Configure `tserver.cache.manager.class`, etc as described above
3. Bounce Accumulo
4. Execute a significant number of concurrent scans to put tservers under load for several minutes

After 60+ minutes of testing this patch, I'm confident that this is now resolved

Thanks!
