### ISSUE TITLE
External Compaction metrics

### ISSUE THREAD

**Issue by dlmarion** [apache/accumulo#1992]
Investigate what metrics should be reported during external compactions

**Comment by keith-turner** [comment]
One use case I would like to experiment with that will need metrics is dynamically adjusting the number of external compactors running in Kubernetes based on the number of external compactions queued.  To test this scenario I would somehow need to obtain the running and queued counts from Accumulo.  Since not all running compactors may necessarily be running a compaction, that is why I am thinking the running count metrics may also be useful.

**Comment by dlmarion** [comment]
@keith-turner started this with [commit](https://github.com/apache/accumulo/commit/f3ece8801ebf027bb1e7b3b665bd14ae90012c6f)

**Comment by dlmarion** [comment]
FYI that there is work in progress with migrating the current metrics framework from Hadoop Metrics2 to Micrometer at https://github.com/apache/accumulo/pull/1981

**Comment by dlmarion** [comment]
Implemented a simple http endpoint in the coordinator (/metrics) that returns a JSON blob that can be parsed by https://github.com/zalando-incubator/kube-metrics-adapter which is a k8s supported custom metrics adapter (see https://github.com/kubernetes/metrics/blob/master/IMPLEMENTATIONS.md#custom-metrics-api) that can be used for horizontal pod scaling

**Comment by dlmarion** [comment]
I think #2032 will need to be resolved, specifically the moving of RUNNING.remove(RunningCompaction), to make the RUNNING count useful for scaling.

**Comment by keith-turner** [comment]
Wrote an IT in 860b87d7c84018c84b6244f06bb54b7db9f5c4a9 for these changes 38d4badfc23acf5b858dc4bc53401f5d47452722.
