### ISSUE TITLE
Unassigned tables on every restart accumulo 1.10.1

### ISSUE THREAD

**Issue by Viv1986** [apache/accumulo#2085]
HI all,

have accumulo 1.10.1 and last month every restart broke +r table which is root and after restore, it become whole cluster unassigned tables and need to wait near hour while all tables will be assigned, 
there is 1 master and 2 table servers, can anybody help me with that? 

021/05/06 17:20:50,343 | tserver:xxxxxx140.internal.xxxx.net | 1 | WARN | exception trying to assign tablet +r<< hdfs://xxxxxxxx120.xxxxxxxxxxxx-dev.local:8020/apps/accumulo/data/tables/+r/root_tablet 	java.lang.RuntimeException: Error recovering tablet +r<< from log files 		at org.apache.accumulo.tserver.tablet.Tablet.<init>(Tablet.java:499) 		at org.apache.accumulo.tserver.TabletServer$AssignmentHandler.run(TabletServer.java:2413) 		at org.apache.accumulo.tserver.TabletServer$ThriftClientHandler$3.run(TabletServer.java:1775) 	Caused by: java.io.IOException: Unable to find recovery files for extent +r<< logEntry: +r<< hdfs://xxxxxxxx120.xxxxxxxx-dev.local:8020/apps/accumulo/data/wal/xxxxxxxxxx.xxxxxxxxx-dev.local+9997/e31761f2-e600-49f9-9a5c-8972aa37005b 		at org.apache.accumulo.tserver.TabletServer.recover(TabletServer.java:3311) 		at org.apache.accumulo.tserver.tablet.Tablet.<init>(Tablet.java:437) 		... 2 more
-- | -- | -- | -- | --
2021/05/06 17:20:50,345 | tserver:xxxxxxxx140.internal.cloudapp.net | 1 | WARN | Error recovering tablet +r<< from log files
2021/05/06 17:20:50,349 | tserver:xxxxxxxxx140.internal.cloudapp.net | 1 | WARN | failed to open tablet +r<< reporting failure to master
2021/05/06 17:20:50,351 | tserver:xxxxxxxxx140.internal.cloudapp.net | 1 | WARN | rescheduling tablet load in 1.00 seconds
2021/05/06 17:20:50,383 | master:xxxxxxxxx120.internal.cloudapp.net | 1 | ERROR | xxxxxxxxx140.xxxxxxxxxxx-dev.local:9997 reports assignment failed for tablet +r<<

**Comment by ctubbsii** [comment]
Based on the error message, it looks like you're missing a recovery file in HDFS for the root tablet. I would first check for HDFS being corrupt. Did you see this after a failure? Have you finished recovering HDFS from that failure before starting Accumulo? Were any files unrecoverable in HDFS? Did all nodes come back online for HDFS?

**Comment by Viv1986** [comment]
@ctubbsii didn't found any errors in hdfs, everything recover ok, problem that I can't reboot cluster or table, it's all time become unavailable while all tables witll be reassgined

**Comment by EdColeman** [comment]
Do you have a lot of data in the write-ahead logs?  Is your ingest streaming or do you do mostly bulk ingest?

If you do not have a lot of data in the WAL, and IF you can determine that the tables rfiles are intact and accessible, you could try a few things - but these will likely lead to some data loss - especially for anything in the WALS.

Does the directory from your error message exist, does it have any files in it?

`hdfs://xxxxxxxx120.xxxxxxxx-dev.local:8020/apps/accumulo/data/wal/xxxxxxxxxx.xxxxxxxxx-dev.local+9997/e31761f2-e600-49f9-9a5c-8972aa37005b`

I am assuming that because this is the root table, you cannot scan anything with the accumulo shell to examine the metadata table.

There some information in the [user manual](https://accumulo.apache.org/1.10/accumulo_user_manual.html#_troubleshooting) on what needs to be done if the root (or metadata) table(s) have a reference to a corrupt wal - basically, shut down accumulo, move the tables rfiles, reinitialize accumlo and the bulk import the files that you moved.

**Comment by ctubbsii** [comment]
Before you do any recovery, I would examine the logs for any references to the missing file, to see if you can determine what might have happened to it. If HDFS is healthy and has no corrupt or missing data, I'm very curious how the file could have gone missing.

**Comment by Viv1986** [comment]
@ctubbsii I examine all logs and found nothing, also by hdfs dfs -ls I able to find that wal file and it have some size, so, any other suggestions except reinitialization?

**Comment by Viv1986** [comment]
ok my last tests show me that all clusters have that problem, and it's not related to error which described in my first message, I use ambari and it's restart tables and master with kill -9, and seems it's ok with reassign tables with such restart.
I have another cluster with same config, but with heapsize = 1.5G, and 40.75B records, and reassign there take near 15 minutes, and same cluster with 40G java heapsize and 52.71B records, reassign will take near 4 hours, what related to table reassign speed?

**Comment by EdColeman** [comment]
When you do a restart, do you start the tservers and THEN the master(s) - if you start the master first, it will see assign everything to the first tserver(s) that it sees, resulting in an unbalanced cluster that takes a while for everything to be processed and then rebalanced because only one (or a few) tservers are processing everything.  There is a property to have the master wait for a required number of tservers that was  added in 1.10.  It is best if the tservers are all up and then the master starts - taht way all tservers are available for assignments.

Other factors could be if the tables are performing batch writes (vs bulk import) - that will generate WAL files that need to be processed during recovery.
Do you every compact the tables - that will reduce the number of files as well as process any info in the WAL so that there is less work that needs to be performed during recovery.

**Comment by Viv1986** [comment]
@EdColeman it's reassign in any case, if I start first master, the last, or even if I not restart master.
Tables run compaction time per time, not manually, but some time ago I added disks and started major compaction and it run ok without any notice.

**Comment by EdColeman** [comment]
Please move this to discussion to the [user mailing list](https://accumulo.apache.org/contact-us/) .  On the list, please describe what steps you are taking,  and then behavior of the system - other details like # of tservers / tablets per tserver, type of ingest (bulk or batch) would be really helpful.  That will provide you with a wider audience for those that are not seeing this discussion.

**Comment by Viv1986** [comment]
@EdColeman tried, but all time 

Hi. This is the qmail-send program at apache.org.
I'm afraid I wasn't able to deliver your message to the following addresses.
This is a permanent error; I've given up. Sorry it didn't work out.

<user@accumulo.apache.org>:
Must be sent from an @apache.org address or a subscriber address or an address in LDAP.

**Comment by EdColeman** [comment]
Did you subscribe first?

**Comment by EdColeman** [comment]
Closing this - the discussion has moved to the mailing list and there is not enough actionable information in the issue to take any action.

**Comment by Viv1986** [comment]
can anybody tell me what related to speed of table reassign? cuz in same configuration I get ~14 tables per minute on current, and ~1500 per minute on another

**Comment by EdColeman** [comment]
Please ask this on the user mailing list.  You will be more likely to get a response if you include additional information.  There are a lot of factors that trigger reassignment and without any information on why the reassignment is occurring and what the system it is very difficult to just guess.

**Comment by milleruntime** [comment]
There are a number of factors that could affect Tablet migration (tablet size, number of tablets, number of tservers, recovery, configuration). Are you using the default configured Load Balancer (see `table.balancer` property) DefaultLoadBalancer? If so, it will attempt to keep an even number of tablets across all tservers. When a tablet gets migrated from one tserver to another, it will get unloaded and then loaded on the new tserver. So if the tablet has a Write Ahead Log (WAL) associated with it, it will do recovery on the WAL. If you are having issues with WALs (based on the previous comments) then this would hold up loading of the tablets with the problematic WALs.

If you have resolved the WAL problems, then you might want to look into using a different load balancer. See this blog post about the GroupBalancer: https://accumulo.apache.org/blog/2015/03/20/balancing-groups-of-tablets.html
