### ISSUE TITLE
Make WAL property names uniform

### ISSUE THREAD

**Issue by milleruntime** [apache/accumulo#2146]
Similar to #2142, it would be nice if all the properties dealing with write ahead logs had consistent names. Currently we have these properties named two ways:
`tserver.walog.max.age`
and
`tserver.wal.blocksize`

The properties with new names would need to be deprecated but I thought it might be something worth doing in 2.1.

**Comment by Manno15** [comment]
I agree that uniformity would be nice. Do you prefer `wal` or `walog`? From a quick glance, it seems we use `walog` more so probably easier to keep that naming convention.

**Comment by milleruntime** [comment]
Even though there are more properties that use the name `walog`, overall I think the term `wal` is more commonly used on the project.

**Comment by Manno15** [comment]
Makes sense. Do you think this could be a good first issue or someone with less experience to handle?

**Comment by milleruntime** [comment]
> Makes sense. Do you think this could be a good first issue or someone with less experience to handle?

I personally like to label issues as `Good First Issue` that are as simple as possible because there are usually other hurdles (building, environment, git) that new developers need to figure out before diving into the code. I think this change will have some upgrade code to go with it. If you know someone that has contributed but is newer to the project it might be a good issue for them to tackle.

**Comment by foster33** [comment]
>If you know someone that has contributed but is newer to the project it might be a good issue for them to tackle.

I am newer to this project and I have been looking for some bigger issues to tackle (something more than a `Good First Issue`). In regards to the potential upgrade code, what type of upgrades could you possibly expect? I understand the deprecation, but I just want to get a better understanding of this before I would dive in.

**Comment by milleruntime** [comment]
I am not sure of everything involved with changing property names but I know they will, at the very least, be stored in Zookeeper and config files. There has been a similar change recently where we renamed master to manager, perhaps that change could help as a guide. See https://github.com/apache/accumulo/pull/1873 

Here is the upgrade code for that change where properties are updated in ZK:
https://github.com/apache/accumulo/blob/8a636a3ba91f5dae1d8b09b095178889a7d79c1d/server/manager/src/main/java/org/apache/accumulo/manager/upgrade/Upgrader9to10.java#L237

**Comment by foster33** [comment]
> There has been a similar change recently where we renamed master to manager, perhaps that change could help as a guide.

Sounds good, thank you for that information.

I'm interested in working on this issue.

**Comment by foster33** [comment]
I seem to have ran into some trouble getting the deprecation and upgrade code to remove the properties entirely from the config command in the ashell (and presumably from other places). Does anyone know more about this process of changing and updating property names?

**Comment by ctubbsii** [comment]
> Does anyone know more about this process of changing and updating property names?

Sure. What's your question? Where are you having trouble?

**Comment by foster33** [comment]
> Sure. What's your question? Where are you having trouble?

Thank you. I was wondering about what different parts of the overall code pertain to updating and changing the property names. I know Mike had previously mentioned config files and in zookeeper. 

I have changed all of the references throughout the code of the old `.walog.` property names to `.wal.`, I have also made sure that all of the old properties have both the `Deprecation` and `ReplacedBy` tag.

From there I wanted to put some upgrade code in `Upgrader9to10.java` to rename properties that are not Master/ Manager specific. I then  made changes in `DeprecatedPropertyUtil.java` to help find the replacement name for the particular deprecated property.

I guess I am wondering what more / changes could I possibly need to do to have them be replaced when looking at the list of Properties in something like the accumulo shell? ... Or if that is even the goal in this. I saw in #1873 that certain things were done to change properties' names, but that was quite different since it was a Prefix type.

I hope this helps elaborate on my current progress.

**Comment by ctubbsii** [comment]
The main thing is to track down all the uses of any of the properties you're changing, to ensure they use the `conf.resolve()` function to read their values from whichever key the user used. That, and the `@ReplacedBy` and `@Deprecated` annotations should be enough to deprecate them.

If we want to be more aggressive, then we can do something like #1873 to block the old property name from being persisted in ZooKeeper and modify the upgrade code to translate any existing properties in ZooKeeper. However, that's not critical. It could be done before removing the old properties entirely, but it isn't necessary as part of the deprecation step. I think the main reason we did that for #1873 is because we anticipate dropping support for the old name a bit more aggressively.
