### ISSUE TITLE
Add sanity check for configuration settings

### ISSUE THREAD

**Issue by Manno15** [apache/accumulo#2148]
**Is your feature request related to a problem? Please describe.**
First posted on Jira Ticket: [here](https://issues.apache.org/jira/browse/ACCUMULO-887)

Quote from the Ticket: 
> I accidentally set the WAL max size to "4" instead of "4G".
This produced the following stack trace, and was pretty hard to track down. We should pay more attention to sane settings for these values.

**Describe the solution you'd like**
Not quite sure how to implement a solution but ideally small typos like forgetting the unit would be easier to track down. 

**Additional context**
I did confirm that this still occurs. The error message for Wal max size has changed since that Jira ticket so it was a bit more obvious on how to track down but this still applies for other properties as well.

**Comment by ctubbsii** [comment]
"4" in this case would have been interpreted as "4 bytes" since it is (presumably) `PropertyType.BYTES`. It can be hard to write general rules to detect and validate these kinds of things, because we don't know what the user had in mind, and the range of sane values is probably different for each individual property, and highly environment-specific. Additionally, special values, like "0" might have specific semantics (like deferring to a hard-coded default).

We could try to code in range constraints to every property that takes a numeric value... which might be tedious, and also might be unnecessarily constraining. After all, "4 bytes" is clearly wrong on a production system, but who is to say that "4 bytes" isn't a valid value for testing WAL rollover or specific failure conditions? And, what should the minimize permitted value actually be here? 1MB? Less? More? I'm not sure.

Having a good error message when the value results in a problem, might be the best option, rather than trying to determine the best range constraint... at least in the general case.

**Comment by Manno15** [comment]
I agree, there is a lot of nuance with this particular issue. Wal, specifically, has an exception message for when the block size is less than the minimum so in some cases that would be tracked down quickly. I am not quite sure if other properties have something like that.

**Comment by Manno15** [comment]
After further discussion, this ticket can be closed for now as there is no actionable work to be done at this time. The specific issue referenced in the JIRA ticket does have a more clear error message now which helps with debugging.
