### ISSUE TITLE
Update README.md to clarify use of 'main' vs '2.0' branch.

### ISSUE THREAD

**Issue by jmark99** [apache/accumulo#2204]
The documentation does not make clear that the main branch is designed to work with versions 2.1.x of Accumulo. If a user needs to run the examples against Accumulo 2.0.x, then the 2.0 branch should be used.

Update documentation to clarify this distinction. 

Additionally,  we could add a link to the 1.10.x examples if a user is looking for them (https://accumulo.apache.org/1.10/examples/).

**Comment by EdColeman** [comment]
Just a clarification - if we can keep it so that the main branch is independent of a version then there may be less to change on each release - if there was a tag / branch made on release, then the main branch is for development / next release and  tagged versions should correspond and be used together.

**Comment by jmark99** [comment]
Moved this issue from the Accumulo repo to the Accumulo-Examples repo. See https://github.com/apache/accumulo-examples/issues/79
