### ISSUE TITLE
Use `ScanInterpreter` for all relevant shell commands, not just `scan`

### ISSUE THREAD

**Issue by willmurnane** [apache/accumulo#2210]
When using the shell to perform scans, the `table.interepreter` property is used to interpret the supplied begin and end row text. However, this property is not used for other operations which also interact with `-b` and `-e` flags for begin and end rows:
* `compact`
* `merge`
* `flush`
* `deletemany`
* `deleterows`
* etc

and other operations which take rows and/or column families or column qualifiers as arguments:
* `addsplits`
* `delete`
* `insert`
* etc

This behavior is confusing to users of the shell, because some interfaces show and accept reformatted key components, and some others accept raw key components.

I propose that the interpreter should be applied to all parameters provided by the user before they are passed to Accumulo.

Alternatively, the interpreter construct could be dropped entirely (see discussion in #1138).

**Comment by ctubbsii** [comment]
Since we now have use of JShell, I think it would be reasonable to just deprecate and eventually drop the scan interpreter stuff (especially since it's not even spelled correctly). It's a bit weird to have shell-specific config stored in the per-table config on the server-side anyway. JShell is a much more powerful and flexible tool, and a lot less work to support, than these quirky shell behaviors.
