### ISSUE TITLE
Pretty-print PrintInfo's 'histogram' ouput

### ISSUE THREAD

**Issue by Manno15** [apache/accumulo#2217]
Original JIRA ticket : https://issues.apache.org/jira/browse/ACCUMULO-1660
Description from the ticket:
<pre>
The output from o.a.a.core.file.rfile.PrintInfo --histogram is hard to read. 
Specifically, the number of zeroes in each row in the histogram is difficult to tell at a glance.
We have code elsewhere to pretty-print large sizes using MB, GB, etc...
 It would be nice to see that here as well.
</pre>

**Describe the solution you'd like**
As shown in the photo below, the size is hard to determine at a glance. Using units like MB or GB would be easier to read. This could be done as the default or as another option on top of `--histogram`. We utilize `NumUtil` in other areas of the code such as `DUCommand` and that could possibly be used here as well..

**Additional context**
Currently, the output of the histogram command looks like the following:

![image](https://user-images.githubusercontent.com/29436247/127570710-c6bff9b2-56de-4b5f-a921-901fc2bc1c43.png)

An example of how to run the command is `accumulo rfile-info <table r-file> --histogram`.

**Comment by Shivakumar-SG** [comment]
Hey @Manno15 , I would like to take up this issue.

**Comment by Shivakumar-SG** [comment]
I'm a bit confused about how to reproduce the above mentioned output as I'm a newbie to open source😌. 
@EdColeman Would you mind giving me a lil start?

**Comment by EdColeman** [comment]
Maybe @Manno15 has additional suggestions, but the coding for this issue is probably the easiest part, but to develop and test might be more complicated.

More information on running the command is available in the documentation [Troubleshooting Tools](https://accumulo.apache.org/docs/2.x/troubleshooting/tools)

RFiles are the  storage format used by Accumulo.  

To generate sample inputs there are some options.

- Writing tests that use LogHistogram class (internal to PrintInfo) directly
- Using / adopting org.apache.accumulo.core.file.rfile.RFileTest

Options to generate "real" files:

- Running an Accumulo instance. See  [Setup](https://accumulo.apache.org/docs/2.x/getting-started
- /quickstart) 
- Running one or more of the integration tests. The output would end up in ./test/target/mini-tests/[TEST-NAME]/accumulo/tables/[TABLE_ID]  Running integration tests using maven is shown in [Running a Build](https://accumulo.apache.org/contributor/building)

The general structure used by Accumulo is described in the [Advanced Troubleshooting](https://accumulo.apache.org/docs/2.x/troubleshooting/advanced) and generate rfiles will be placed into directories according that structure and can then be displayed using the print-info shell command.

Successful development and testing would likely require one or more of the above to demonstrate larger prefixes (MB, GB...) are being correctly formatted.
