### ISSUE TITLE
Make text alignment consistent in Monitor

### ISSUE THREAD

**Issue by milleruntime** [apache/accumulo#2286]
**Describe the bug**
The text alignment in table cells is different across pages in the monitor. This is due to the 2 different ways we have of creating tables. The older way which uses straight JS functions and jquery, aligns text one way, while datatables aligns text the other way. It would be nice to replace all tables with datatables but that is a lot of work so until that happens we could at least make text alignment consistent between the two.

**Versions (OS, Maven, Java, and others, as appropriate):**
 - Affected version(s) of this project: 2.*

**Comment by ctubbsii** [comment]
Not sure if this is still the case, but I noticed that in the past, we've used tables to store data that didn't need a table (e.g. where there was only a single row of information, and we just put it in a tabular format for lack of design creativity). If that is still the case, instead of switching to datatables or fixing the alignment, it might make sense to just use a different style of display for non-tabular data. Bootstrap has lots of options for visualizing information: badges, jumbotrons, callouts, dialog boxes, lists, panels, headers, buttons, etc.

**Comment by DomGarguilo** [comment]
It seems like there are two ideas here that could have their own tickets:
1. Convert all tables to Datatables
2. Consider other display options for tables with only one row

**Comment by DomGarguilo** [comment]
It seems like most table's data are consistently left aligned with a few tables having hardcoded right alignment for certain columns. I'm wondering if these outliers that are not left aligned should be left as is or if those are the cases that are being referred to in this ticket and should be changed.

**Comment by ctubbsii** [comment]
If the tables are using Datatables, any custom alignment is likely intentional. So, the main concern for this issue is probably regarding any unusual alignments for non-Datatables tables. For those, I think before changing alignments, one should consider the two options @DomGarguilo highlighted in https://github.com/apache/accumulo/issues/2286#issuecomment-1119044423

However, I think it would be helpful to have a list of those non-Datatables tables (and maybe screenshots) that are under consideration for this. Even better, if there's specific alignment/formatting observations included in that list, for things to improve.

**Comment by DomGarguilo** [comment]
It seems like for the most part, everything is left aligned within the rows. I've been looking through the tables and some tables are a bit different. For example:

The manager table seems to right align numerical data and left align everything else:
![Screenshot from 2022-05-06 11-20-31](https://user-images.githubusercontent.com/47725857/167186581-2a80c8cc-c242-4428-bb13-772f15f6e0a5.png)

The dead tablet servers table and non-functioning tablet servers table left align the servers and right align everything else.
![Screenshot from 2022-05-06 12-24-16](https://user-images.githubusercontent.com/47725857/167186575-b99f8ff6-09dd-4156-809f-084636b5f824.png)
![Screenshot from 2022-05-06 12-23-58](https://user-images.githubusercontent.com/47725857/167186578-70d57283-d8c3-42ca-ad5e-ea7bda24a3a4.png)

There are probably other tables with different patterns. The question is what standard should we follow? Left/right/center align everything in all tables? Left align text and right align numerical data? Something else? 

I personally don't have a preference as long as things are consistent.

**Comment by DomGarguilo** [comment]
Here is a long list of all tables (I think).

| Table id      | is a DataTable |
| ----------- | ----------- |
| tableList | :heavy_check_mark:  |
| bulkListTable | :heavy_multiplication_x: |
| bulkPerServerTable | :heavy_multiplication_x: |
| compactionsList | :heavy_check_mark: |
| compactorsTable | :heavy_check_mark: |
| runningTable | :heavy_check_mark: |
| gcActivity | :heavy_check_mark: |
| trace | :heavy_multiplication_x: |
| logTable | :heavy_check_mark: |
| managerStatus | :heavy_multiplication_x: |
| recoveryList | :heavy_multiplication_x: |
| problemSummary | :heavy_check_mark: |
| problemDetails | :heavy_check_mark: |
| replicationStats | :heavy_multiplication_x: |
| scansList | :heavy_check_mark: |
| tServerDetail | :heavy_multiplication_x: |
| opHistoryDetails | :heavy_multiplication_x: |
| currentTabletOps | :heavy_multiplication_x: |
| perTabletResults | :heavy_check_mark: |
| traceSummary | :heavy_multiplication_x: |
| participatingTServers | :heavy_multiplication_x: |
| badtservers | :heavy_multiplication_x: |
| deadtservers | :heavy_multiplication_x: |
| tservers | :heavy_check_mark: |

**Comment by ctubbsii** [comment]
From the screenshots above, the only thing I would fix is the last GC run... I would center that.

For what it's worth, I don't think we should just align everything the same way. I think when we think about consistency, we should really be thinking about consistency among similarly situated fields, not a global consistency. There's a lot of differences between tables, warranting a "case-by-case" approach. One alignment may look better or worse than the same alignment on a different table.

For this, maybe it's just worth looking at the tables and making a best effort to fix anything that looks bad... rather than worrying about consistency. Every table is unique, after all.
