### ISSUE TITLE
listSplits table operation with a max num splits may have a bug.

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#2371]
In the following code there is a while loop, however in the while loop the variable `i` does not change.   If the while loop will execute more than once then it will add the same split multiple times which seems like a bug.

https://github.com/apache/accumulo/blob/45a4a93d2926760d6a916ae2da1d7e668ec4dcb1/core/src/main/java/org/apache/accumulo/core/clientImpl/TableOperationsImpl.java#L706-L710

Not completely sure if the while loop could execute more than once, needs further investigation.  If the outer variable `r` could be greater than 1, then it seems like the while loop could execute more than once. 

If the while loop could never execute more than once then maybe it could be changed to an if stmt.

**Comment by milleruntime** [comment]
I was talking with @ctubbsii a bit about some of the issues the many different use cases that can be encountered with splitting data evenly and the work I was doing for #2368. Instead of us trying to write our own algorithms, maybe we can use a library. He suggested taking a look at the Apache Datasketches project, for help with mathematical algorthims such as this. One type in particular that might be useful is the quantiles in ItemsSketch: https://datasketches.apache.org/api/java/snapshot/apidocs/org/apache/datasketches/quantiles/ItemsSketch.html#getQuantiles-int-

**Comment by jmark99** [comment]
I was looking at the code today. The value of 'r' will always be <= 1 so the while-loop should never execute more than one time per for-loop iteration. Switching the while-loop to an if-statement would not affect results while perhaps clearing up the code a small amount. Either way, the code accomplishes its intended purpose at the moment.

As for this particular ticket, three options can be considered:
* leaving correctly running code as is
* updating the while-loop to an if-statement to remove a small amount of confusion
* look into other methods of evenly parsing data as referenced above. 

Thoughts on this ticket in particular?

**Comment by milleruntime** [comment]
> updating the while-loop to an if-statement to remove a small amount of confusion

The code is confusing so I think this could at least be done to clear up any confusion and confirm there isn't an issue.
