### ISSUE TITLE
accumulo 2.0.1 has log4j dependency

### ISSUE THREAD

**Issue by pjfanning** [apache/accumulo#2542]
**Describe the bug**

https://repo1.maven.org/maven2/org/apache/accumulo/accumulo/2.0.1/accumulo-2.0.1.pom

Log4jv1 is end-of-life and has numerous security issues. Can you use log4jv2 instead?

**Comment by ctubbsii** [comment]
This is already fixed in our [LTM](https://accumulo.apache.org/contributor/versioning.html#LTM) release by #2458 for 1.10.2, and #1528 (and subsequent issues) for the upcoming 2.1.0. As a non-LTM release, 2.0.1 is not expected to receive another patched release. Instead, its patches are expected to be rolled into the next release, which is 2.1.0, still under development.

If you wish to replace log4j1 in your deployments of 2.0.1, you can do so without a new release from us, by simply dropping in reload4j, like what was done for 1.10.2. You may also be able to change your slf4j binding to the latest log4j2 or something else, like what was done for 2.1.0.
