### ISSUE TITLE
Rename property

### ISSUE THREAD

**Issue by milleruntime** [apache/accumulo#2618]
The property name `general.server.simpletimer.threadpool.size` is old and doesn't really make sense anymore with the refactoring of ThreadPools class. I am wondering if we should rename it. Maybe something like `general.server.threadpool.size`. The `SimpleTimer` class has been dropped.

https://github.com/apache/accumulo/blob/12fde7ec38c485acefa162ec0dfb6a73919fd576/core/src/main/java/org/apache/accumulo/core/conf/Property.java#L246

**Comment by EdColeman** [comment]
This might be more than just a simple rename. There are considerations of current usages, how and where the name / value is used and the expected behavior of existing code that uses the current values.

For the original issue as stated, one possibility would be to would be to rename both the property enum name (GENERAL_SIMPLETIMER_THREADPOOL_SIZE) and the string value used as a key (general.server.simpletimer.threadpool.size) to something that reflects the current usage.  

However, there are additional considerations:

It may be better (necessary?) to deprecate the current name with the replacement, but allow either to be used.

The change would need to replace the enum name in the code base and then any scripts that use the string value should also be modified.  This should also be documented in the release notes so that users know the change occurred.

For current installations that may use the current name, it would be necessary to rename the property name (key) that is stored in ZooKeeper during the upgrade processing so that the "saved" value would be transformed and remain valid any code that has this change.

**Comment by kitswas** [comment]
Just for clarification.

Is the comment 
https://github.com/apache/accumulo/blob/12fde7ec38c485acefa162ec0dfb6a73919fd576/core/src/main/java/org/apache/accumulo/core/conf/Property.java#L249
for the Experimental property `GENERAL_VOLUME_CHOOSER`?
https://github.com/apache/accumulo/blob/12fde7ec38c485acefa162ec0dfb6a73919fd576/core/src/main/java/org/apache/accumulo/core/conf/Property.java#L252

The code suggests so, but the comment is a tad confusing([simply too relevant](https://github.com/apache/accumulo/issues/2618#issuecomment-1104368037)).

**Comment by ctubbsii** [comment]
> Just for clarification.
> 
> Is the comment
> for the Experimental property `GENERAL_VOLUME_CHOOSER`?

Yes.

**Comment by kitswas** [comment]
> It may be better (necessary?) to deprecate the current name with the replacement, but allow either to be used.

This is something I believe I can do. May I make an attempt?

**Comment by kitswas** [comment]
![Screenshot](https://user-images.githubusercontent.com/90329875/168588271-2fb28c1a-5c93-480e-a2ef-24ffd4ee0b4f.png)
Is the name `"General"` alright? 

In method [`createExecutorService`](https://github.com/apache/accumulo/blob/dd81d608bff88835676e756ffcb2a2f6b69c9be8/core/src/main/java/org/apache/accumulo/core/util/threads/ThreadPools.java#L262).
