### ISSUE TITLE
Server client execute while loop does not handle thread interrupt

### ISSUE THREAD

**Issue by nikita-sirohi** [apache/accumulo#2621]
**Describe the bug**
Server client execute while loop does not handle thread interrupt. In the case of a thread interrupted, the loop will forever try and fail to open a socket.

**Versions (OS, Maven, Java, and others, as appropriate):**
 - 1.10 and on

**To Reproduce**
Would need to interrupt thread during a execute loop -- unfortunately the example I have is in a private repo -- hoping the community will look at the fix though and it will be clear if this fix is correct or not?

**Expected behavior**
While loop should exit if thread is interrupted -- this would mirror the behavior in ThriftScanner as well. 

**Additional context**
Found while writing a trino + accumulo/other services integration (in a private repo). Looking at the out of the box accumulo trino plugin, I believe it would have this error as well.

**Comment by nikita-sirohi** [comment]
I will open a PR

**Comment by ctubbsii** [comment]
Hi, @nikita-sirohi . Thanks for reporting the problem. I commented on your PR. However, I just wanted to mention here that it is not generally necessary to create a separate issue if you're going to submit a PR right away. It still makes sense to have a separate tracking issue sometimes, but unlike some other projects, it's not strictly required by us, since the PR serves as its own issue number on GitHub.
