### ISSUE TITLE
CacheEntry SPI has broken generics

### ISSUE THREAD

**Issue by ctubbsii** [apache/accumulo#2697]
The CacheEntry class uses a generic method for getIndex to retrieve a Weighable generic type. However, because the generic is on the method, instead of the class, there's no guarantee of retrieving the same Weighable subclass type for repeated calls to the CacheEntry. This forces the calling class to do unnecessary unchecked casts to ensure the result of this method is consistent with the result of a previous call to the same supplier.

This could be made much better if the generic type was put on the CacheEntry, so all calls to getIndex for a given CacheEntry instance would return the same Weighable type, and expect a Supplier that is of that same type.

The risk here is that this breaks users slightly. With runtime erasure, the generic types wouldn't matter for previously compiled code. It also wouldn't normally matter for newly compiled code... except that the Weighable interface is defined inside the CacheEntry class, and it needs to be moved in order to make the class generic instead of the method. That probably would break somebody. However, even then, it's probably low risk to make breaking changes here to fix this, as I doubt it is common for users to write their own block cache implementations.

**Comment by cshannon** [comment]
@ctubbsii - As I'm still trying to learn more about the internals of Accumulo I was poking around some of the caching implementation today just to see how block caching works and I noticed this issue. Is this still something you want done? If so I can work on it, but at this point maybe we should target it for the 3.0 cleanup release since 2.1 is being wrapped up? 

I started looking at what this change would require and it would touch a good number of files and since it's basically a clean up of the generics (along with a slight chance for breaking users as you noted) it seems like the 3.0 release would be a good time for this.
