### ISSUE TITLE
Additional improvements to the du command,

### ISSUE THREAD

**Issue by EdColeman** [apache/accumulo#2820]
**Is your feature request related to a problem? Please describe.**
As a follow-on to https://github.com/apache/accumulo/pull/1259, there may be  ways to improved the du command performance, possibly at the sacrifice of some accuracy.

**Describe the solution you'd like**
Ideally the du command could return nearly as fast as the hadoop directory usage command.

**Additional context**
There may be a conflict between how much space an Accumulo table needs - vs. how much space is it occupying on disk. Compactions in progress can increase the hdfs usage because they are created and stored on disk, but not yet part of the table "used" files. Files that are eligible for gc, but not deleted also inflate the hdfs space. 

The metadata stores estimated entity counts and files size that is updated on a compaction. For bulk imports, the information may not be available.

For a large table, does it matter?  You have a big number vs another bigger number. In most cases, the physically hdfs usage seems the most relevant. If the Accumulo size is a driving factor and a accurate number is needed - then you probably should run a compaction so that old data can be aged off, shared files consolidated,...At that point (barring additional bulk imports) the metadata values should be accurate and may be good enough. 

The du command accounts for shared files - if a table is cloned, it is a metadata operation and the file references in the metadata are "copied" - so you cannot use the file size in hdfs under the table directory because the table could be sharing files that are in a different tables directory tree.

Possible changes:

- if no files are shared, just use the hdfs (hdfs -dus option) directory size of the table.
- Maybe use the file entity / size estimates and then add the files size of bulk import files?
- provide options to the command just get the entity / size estimates from the metadata or just the hdfs directory size and allow the used to figure out what they needed in the first place. (or show both and wish them luck...)

**Comment by cshannon** [comment]
@EdColeman - I agree that making some changes here makes a lot of sense to improve performance. I have a background in Apache Kafka and it's similar there when trying to compute the message count and disk usage/size of a Topic and partitions (similar to tablets in Accumulo). It's an intensive process to have to walk to the partitions and figure out the number of messages/disk usage so estimating and caching sizes/metadata is usually sufficient because it doesn't much matter the exact count/bytes when talking about large enough numbers as long as it's close.

I am happy to work on this issue and make the changes once we get some feedback from everyone and come to a consensus about what changes should be done here.

@milleruntime, @ctubbsii , @dlmarion - Thoughts on this?

**Comment by cshannon** [comment]
If no one has any objects I am volunteering to go ahead and start with the 3rd suggestion listed and work on an option to scan the Metadata for the size information as that seems like a logical thing to try. I can provide a PR for that and see what people think. I may have a little bit of time later this week to get started but I am out next week so I probably won't have something to submit to be reviewed until at least the first week of August.

**Comment by cshannon** [comment]
@EdColeman -

Yesterday/today I spent a good amount of time diving into the Scan api and implementation between the client and server to get a better feel how that works and then I also started working on this a bit. I have a branch with a rough prototype/proof of concept that is a work in progress here: https://github.com/cshannon/accumulo/commits/accumulo-2820

It's not ready for a real review yet as there's more work to be done but you can take a look if you get a chance and see the direction I'm going. I had a couple questions/comments and wanted to get your thoughts.

1. The metadata table scan could technically just be done by the client without an RPC call but I kept the current way of sending an RPC request and letting the server do it inside of the [TableDiskUsage](https://github.com/cshannon/accumulo/blob/9b6ae27be4ba50513cf41c58281324211f8e75d3/server/base/src/main/java/org/apache/accumulo/server/util/TableDiskUsage.java) class. I think this is much better as it keeps the current design intact and is a simpler update plus this utility already scans metadata for the file names to use for the HDFS iterator. So it can simply be updated to read the sizes from metadata instead and the client/shell code can more or less work the same without many modifications.
2. I created new disk usage RPC call which same as the old with a new method parameter.  This will allow passing any options we want to custom the du command when sent to the server for processing. The main thing now is a [Mode](https://github.com/cshannon/accumulo/blob/9b6ae27be4ba50513cf41c58281324211f8e75d3/core/src/main/thrift-gen-java/org/apache/accumulo/core/clientImpl/thrift/TDiskUsageMode.java) enum which just currently has FILE, DIRECTORY, METADATA. The idea is the user running the command could specify how they want to compute the size. The documentation will describe the benefits/drawbacks of each mode. FILE is just the current default way of scanning the HDFS files, DIRECTORY would be for using the hdfs -dus command (not implemented yet in my prototype) and METADATA would be just scanning the metadata table. Having the options parameter and enum for mode will allow us to easily expand in the future with any flags or settings we want to compute usage.
3. I still need to update things to handle scanning the root table if someone wants to know the metadata table size itself.
4. I haven't looked at bulk import stuff yet but that could be another mode or just be included automatically, not sure.
5. Tests of course will still need to be updated and done.

**Comment by cshannon** [comment]
After talking offline to @EdColeman I am going to try a different approach of creating a new command called `du_meta` that will be simpler and just do the metadata scan on the client side and not touch the RPC call or the current command. The metadata stores the HDFS file sizes and this seems like a faster option for getting the output by doing the client side scan vs having to send an RPC call. The help for the command can mention the fact that for the most accurate info that a flush/compaction should be run so metadata is updated.

The old command can stay for now and eventually be marked as deprecated and removed if this new one performs better as expected. I also plan to add some flags to support different options such as computing the size of a single Table or all tables in a namespace, etc.

**Comment by cshannon** [comment]
@EdColeman - new working branch for the client side only version is here if you want to take a look: https://github.com/cshannon/accumulo/commits/accumulo-2820-client

This is by no means finished and still very much a work in progress and I will continue with it later this week, probably Friday. The output still needs work plus i think the totals being computed are off if there are splits as it doesn't quite look right when using your shared test data generation with split points as extra metadata entries are added which are probably not tracked correctly so I'll be looking at fixing that.  I did add a verbose flag to spit out the breakdown when data is shared across tables just like the original command does when using a pattern or namespace. Besides checking the math and handling splits plus working on the output there are still no tests or anything yet since I'm still experimenting.

**Comment by ctubbsii** [comment]
See my comments on the PR.
