### ISSUE TITLE
ZooZap catches overly broad exceptions

### ISSUE THREAD

**Issue by dlmarion** [apache/accumulo#2852]
Modify ZooZap to catch more narrow exceptions

**Comment by cshannon** [comment]
From taking a quick peak at this it looks like the checked exceptions that need to be caught are just KeeperException and InterruptedException and it seems like most places in the code (if not all) batch both at the same time and handle the same. Was there some specific behavior that you wanted to be done differently for error handling depending on the different thrown exceptions in this case?

**Comment by dlmarion** [comment]
> Was there some specific behavior that you wanted to be done differently for error handling depending on the different thrown exceptions in this case?

No, I don't believe so. The comment that spawned this issue was just we should just catch the exceptions that are thrown and not all RuntimeExceptions.

**Comment by ctubbsii** [comment]
The comment that spawned this issue was very specific to the code where it was newly being introduced. We already have occurrences where we catch overly broad exceptions when we shouldn't, or rewrap RTEs with another RTE as a result, as well as occurrences where we throw overly generic exception types. The point of the original comment was to avoid introducing new such occurrences, not to address all the existing ones. You'd have to go back to the original comment/issue to address the specific ones being added here that should be fixed.

**Comment by dlmarion** [comment]
See https://github.com/apache/accumulo/pull/2665/files#r938955552

**Comment by ctubbsii** [comment]
This is the direct link to the comment, in context: https://github.com/apache/accumulo/pull/2665#discussion_r938955552

**Comment by dlmarion** [comment]
GitHub gave me the link to the comment, but apparently doesn't display it.

**Comment by ctubbsii** [comment]
> GitHub gave me the link to the comment, but apparently doesn't display it.

It sometimes takes a bit to load and expand the collapsed comments. It should work if you open it in a new tab.
