### ISSUE TITLE
Simplify ScanServerSelector

### ISSUE THREAD

**Issue by dlmarion** [apache/accumulo#2855]
@ctubbsii commented on #2665 :

> There are a lot of nested interfaces inside this class. These should probably be separate files in the same package. Or, if they aren't required to be implemented by the user's SPI implementation, then they could be removed outside of the spi package to reduce user confusion (for example, if they are objects we create and pass to the user's plugin code).

The interfaces are required to be implemented by the user's SPI implementation. Investigate whether or not moving the interfaces to their own files makes things simpler to understand.

**Comment by ctubbsii** [comment]
> @ctubbsii commented on #2665 :

If you paste a link to the comment itself, rather than the ticket number, GitHub should provide an easy way to navigate back to the original comment, and will show a preview of that comment inline. Right now, there's no link back to the original comment, so this issue marked "good first issue" is hard for a user to find the original comment on the code that "this class" refers to.

**Comment by dlmarion** [comment]
See https://github.com/apache/accumulo/pull/2665/files#r938966238
