### ISSUE TITLE
Permissions checks that changed in #2988 broke a lot of things

### ISSUE THREAD

**Issue by ctubbsii** [apache/accumulo#2993]
**Describe the bug**
Many tests were broken by #2988. That change was reverted, and needs to be reworked before re-adding it.
(`-Dit.test=AuditMessageIT,DumpConfigIT,ImportExportIT,NamespacesIT,PropStoreConfigIT,PermissionsIT,ShellServerIT`)

I'm creating a new issue to track this, with the original developer assigned, so this doesn't get lost.

**Comment by dlmarion** [comment]
I made the following changes in #2994 

  1. Modified client.thrift to declare ThriftSecurityException where it's thrown
  2. Added check for system user in ClientServiceHandler to allow system process to get configuration
  3. Modified PermissionsIT so that test user always has READ permissions on table so that it can check the configuration for arbitrary properties
  
 The following tests are now passing: `AuditMessageIT, DumpConfigIT, ImportExportIT, PropStoreConfigIT, PermissionsIT`
 
 The following tests are still failing, but I think they may point to valid issues.
 
**NamespacesIT**
 - testPermissions may be failing due to consistency
 - verifyPropertyInheritance & verifySystemPropertyInheritance, root user does not have READ permission on DEFAULT namespace.

**ShellServerIT**
cloneTable - failing on line 649, getting configuration on table that was just cloned
cloneTableOffline - failing on line 671, getting configuration on table that was just cloned
exporttableImporttable - failing on line 212, getting the configuration for a table that was just imported.

The above tests are failing with the error:
```
org.apache.accumulo.core.client.AccumuloException: org.apache.accumulo.core.client.AccumuloSecurityException: Error PERMISSION_DENIED for user root - User does not have permission to perform this action
	at org.apache.accumulo.core.clientImpl.NamespaceOperationsImpl.getConfiguration(NamespaceOperationsImpl.java:266) ~[classes/:?]
```

**Comment by dlmarion** [comment]
This [one line]([9e98909](https://github.com/apache/accumulo/pull/2994/commits/9e98909a50924f9feedcd5950f7ce7997b3a2f84)) change resolves the test issues in ShellServerIT, NamespacesIT.verifyPropertyInheritance and verifySystemPropertyInheritance. If we want to keep this change, then we likely need to also update the upgrade code. If we don't want to keep this change, then we need to make a similar change in the tests.

**Comment by dlmarion** [comment]
I also fixed the NamespacesIT test, so I think all tests are passing now. I'm going to kick off a full IT build to be sure. There is still an open question w/r/t my comment above.

**Comment by ctubbsii** [comment]
The root user should not have permission by default to read the DEFAULT namespace, as that is intended for user tables, and the root user has no inherent need to read user tables. It can be granted to the root user in the test where it is needed.
