### ISSUE TITLE
Error upgrading to exec-maven-plugin version 3.1.0

### ISSUE THREAD

**Issue by DomGarguilo** [apache/accumulo#3033]
**Describe the bug**
When updating the exec-maven-plugin version to 3.1.0 in the pom, the build fails with `mkdir: missing operand`. I'm pretty sure this comes from here:
https://github.com/apache/accumulo/blob/78142d74f3ed1a23a374f5bd5fdbd7f245a16721/core/pom.xml#L344-L348

The second argument must not be behaving as expected. I can replicate this error in my terminal by not passing another argument i.e. `mkdir -p` with nothing after it.

**Versions (OS, Maven, Java, and others, as appropriate):**
 - Affected version(s) of this project: 2.1.0-SNAPSHOT

**To Reproduce**
Steps to reproduce the behavior (or a link to an example repository that reproduces the problem):
1. udpate exec-maven-plugin to 3.1.0
2. run `mvn clean package -DskipTests`

**Comment by ctubbsii** [comment]
I wonder if it is related to https://github.com/mojohaus/exec-maven-plugin/issues/334 , which also seems related to https://github.com/mojohaus/exec-maven-plugin/issues/75 . exec-maven-plugin seems to perpetually be confused regarding anything with `-p`, due to assumptions that it's related to a Java modulepath, even if the executable is entirely different.

It would be good to just put in an inline XML comment like the one we used to have for 1.6.0:  https://github.com/apache/accumulo/blob/631386de49bbc351411ce0e3c49982f1df998fe9/pom.xml#L742

**Comment by Manno15** [comment]
Just for context, the workarounds others have suggested in the ticket do work. Both `"-p"` and `--parents`

**Comment by ctubbsii** [comment]
> Just for context, the workarounds others have suggested in the ticket do work. Both `"-p"` and `--parents`

I'd rather wait for the upstream bug to be fixed, rather than use these workarounds. Hacking the quote parsing for the short option seems fragile, and using the long option won't work on non-GNU systems like BSD. There's no reason the plugin should be doing anything with the arguments passed to the executable at all. We can leave this at the current version for now.
