### ISSUE TITLE
Shorten displayed time strings in the monitor.

### ISSUE THREAD

**Issue by EdColeman** [apache/accumulo#3048]
Times in the monitor seemed to be displayed as `Wed Oct 26 2022 14:47:06 GMT+0000 (Coordinated Universal Time)` it might improve clarity if they were displayed in ISO-8601 format - `20221026T14:47:06Z` or something similar.

**Comment by EdColeman** [comment]
It's the way logs present time, so to my eyes it looks normal.  Anything shorted could be an improvement rather than explaining what GMT is on each timestamp

**Comment by cshannon** [comment]
I opened up PR #3056

The JavaScript function that is supposed to format the date calls format but then doesn't return the formatted value and instead returns the original date and a very verbose format.

An example of the format that displays is: `Fri Oct 28 2022 11:15:10 GMT-0400 (Eastern Daylight Time)` which is the default toString() method being called. The bug is here with the return on this line https://github.com/apache/accumulo/blob/6099e81c891195caa7f54a4f4e96cf9fd10afef0/server/monitor/src/main/resources/org/apache/accumulo/monitor/resources/js/functions.js#L138
