### ISSUE TITLE
Support read only Accumulo snapshots that can run in other data centers.

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#3065]
**Is your feature request related to a problem? Please describe.**

Provide a way for Accumulo queries to be served from multiple data centers.  This allows Accumulo queries to be more fault tolerant and enables certain use cases for performance.

**Describe the solution you'd like**

One possible way to accomplish this is by building on scan servers and the unimplemented [system snapshot feature](https://accumulo.apache.org/design/system-snapshot.html).  Using these two features, could have one primary Accumulo cluster and one or more secondary Accumulo clusters that serve data from snapshots.

The primary cluster would have the following responsibilites.

 * Ingest new data
 * Perform data maintenance (age off old data, delete unwanted data, correct erroneous data, etc)
 * Take periodic system snapshots of the data and metadata (table config, system config, tablets, etc) and periodically delete older snapshots.
 * Serve queries.

The secondary clusters would do the following.

 * Copy snapshots from primary or other secondary clusters.  Only need to copy differences after copying first snapshot.
 * Run scan servers against the latest snapshot to serve queries as needed.  Scan servers could run in Kubernetes and be scaled up and down as needed.
 * Be able to assume the role of primary if needed.  The snapshot design doc discusses restoring Accumulo from a snapshot, so that functionality could be leveraged for this use case.

Below is a diagram of what this might look like.

![Slide4](https://user-images.githubusercontent.com/1268739/200007788-954994c3-883c-4f54-b43e-9f44a11b1d6a.jpg)

There are a few things I like about this approach.

 * Data maintenance is done in one place, rather than each cluster doing data maintenance possibly leading to slightly different data in each cluster over time.  The differences in data would be caused by differences in config and user iterator code on each cluster.
 * Data maintenance has computational cost associated with it, so it may be computationally cheaper to do it in one place and copy the results.  For example, some data maintenance operations may require spinning up a large Kubernetes cluster to run external compactions for a long time period.  These long running computations may be more expensive than copying the resulting snapshot diff.  However there may be cases where the copy is more expensive than the computation.
 * Configuration is done in one place.  As a bonus if the snapshots contained the user jars used for scan time iterators, spinning up a snapshot on a secondary cluster could yield very predictable behavior as the code+config+data is the same on each secondary.  Using the same containers across clusters with user jars baked in is another way to get code consistency. 
 * With Accumulo's encryption features, the snapshot data could be end-to-end encrypted when copied between clusters. A backup cluster could even have encrypted snapshots w/o having the keys to read them until needed.
 
**Describe alternatives you've considered**

There are many alternative ways to accomplish this and would need to compare the solution above to those.  Below are two possible ones.

- Make existing import/export table functionality support differential import/export using clones of tables.  This shares a lot of the benefits of the system snapshot approach, its just per table snapshots.  It feels a bit more cumbersome and does not cleanly capture all levels of Accumulo config.
- Update the existing replication feature to support replicating files, it currenltly only replicates WALs so does not replicate bulk imports or the results of compactions that modify data.  Do not need to replicate compaction results if the same data maintenance operations are performed on each cluster.

**Comment by ctubbsii** [comment]
This seems similar to the replication feature that has been unmaintained / abandoned. What makes this different?
And, would it be better to advocate users create an ingest pipeline outside of Accumulo for cross-data center snapshots/replication/copies? Like, have data come in via Kafka or NiFi, and have multiple consumers/destinations for the different target data centers?

**Comment by keith-turner** [comment]
> This seems similar to the replication feature that has been unmaintained / abandoned. What makes this different?
And, would it be better to advocate users create an ingest pipeline outside of Accumulo for cross-data center snapshots/replication/copies? Like, have data come in via Kafka or NiFi, and have multiple consumers/destinations for the different target data centers?

The main difference with the replication feature and multiple ingest pipelines is that each those require redundant data maintenance operations.  I am a bit uncertain if centralized data maintenance makes this feature worthwhile though.  Is doing the computation cheaper than the copy?  Is the consistency provided by doing data maintenance in one place worth the overhead of implementing this feature?  I suspect it may be worthwhile, but I am not completely sure.

This feature could not be done w/o first doing system snapshots which I think have a lot of their own benefits independent of this.  I think this feature would mainly be about making scan servers be able to read from a system snapshots.

**Comment by EdColeman** [comment]
A few things.

First as replication was designed, it only supported streaming ingest.  If you are doing bulk-ingest then you needed to make other provisions anyway.

And as far as bulk ingest and replicating the data - it really is user dependent.  You can elect to generate the bulk import files and then replicate those or you could tee the data and perform the bulk ingest preparation in parallel at each location.  

If you elect to ship bulk import files, then you only pay for the cost of generation once, but you could end up sending more data (if the ingest increases the data size because of indexing or multiple views...) and the latency is likely longer because the data is transmitted after the files are generated.

If you tee the data, then you may have additional consistency questions - the bulk import processes could start at slightly different times with slightly different data.  The bulk prep job could fail or take longer at one of the locations,....  

So it is really going to be user dependent.

From a redundancy perspective, tee-ing the data and processing the data locally at each site probably has the best fail-over posture because of the increased isolation of all of the independent processes - but could also have the largest opportunity for scans to return slightly different results without additional synchronization.

**Comment by dlmarion** [comment]
Something to think about is the case where a secondary system has shorter/longer retention than the primary, so maybe it's not an exact copy but has different retention requirements. I think in this specific case, you would want to ship the rfiles when added to the system (either from a minor compaction or bulk import) and let the other system perform it's own maintenance. Maybe that's a different ticket.

**Comment by ctubbsii** [comment]
> This feature could not be done w/o first doing system snapshots which I think have a lot of their own benefits independent of this. I think this feature would mainly be about making scan servers be able to read from a system snapshot.

I absolutely agree that system snapshots have their own independent benefits.

With that in mind, and thinking in terms of system complexity, I think it's better for scan servers have one normal mode of operation, and for users to make use of it in clever ways that suit their needs, than it is for us to support multiple modes of operation for the scan servers. For example, since snapshot restoration would have its own independent benefits, one could cleverly make use of that ability to stand up an on-demand cluster from a snapshot, and have scan servers operate as they normally would on on a cluster, rather than have a separate mode of operation on the snapshot directly. This is slightly more system administration work, but should be *substantially* less code and feature complexity.

This is how I think in general, as it's much easier to maintain simpler tools that users can re-purpose for a variety of use cases, than it is to maintain complex tools tailored to a large predetermined set of use cases. I think I'd like to see where the snapshot feature takes us before I spend too much time thinking or evaluating the idea in this issue, though.

**Comment by keith-turner** [comment]
> For example, since snapshot restoration would have its own independent benefits, one could cleverly make use of that ability to stand up an on-demand cluster from a snapshot, and have scan servers operate as they normally would on on a cluster, rather than have a separate mode of operation on the snapshot directly. This is slightly more system administration work, but should be substantially less code and feature complexity.

I like that.  I think I can close this as it turns out its just a possible use case for system snapshots.

**Comment by keith-turner** [comment]
I was thinking if scan servers could read directly from a snapshot it would mean that tablets in the snapshot do not need to be hosted on tablet servers on a secondary cluster.   In the past I have spoken w/ @dlmarion and he mentioned it would be nice if scan servers supported offline tables.  Thinking that feature would also help support the use case mentioned in this issue as it would mean the secondary clusters would only need a few tservers to serve metadata tablets.  Making scan servers be able to read from offline tables would support be more generally useful than making them read from a system snapshot.
