### ISSUE TITLE
Confirm that scanning offline table with no ScanServers fails.

### ISSUE THREAD

**Issue by dlmarion** [apache/accumulo#3084]
#3082 allowed an offline table to be scanned if the consistency level is set to EVENTUAL. Need to add a test that confirms the scan does fail when no ScanServers are running.

**Comment by dlmarion** [comment]
Confirmed that there is more work to do here.  If you insert the following [here](https://github.com/apache/accumulo/blob/main/test/src/main/java/org/apache/accumulo/test/ScanServerIT.java#L158) the test fails.

```
TabletLocator.getLocator((ClientContext) client, TableId.of(client.tableOperations().tableIdMap().get(tableName))).invalidateCache();
```

The reason it succeeds currently is that the table was online and a tablet was hosted. That information is in the TabletLocator. Once that information is no longer present, then the current client code fails.

**Comment by ctubbsii** [comment]
I'm marking this as a blocker, because if we remove this restriction in a patch release, we need to be confident it works and doesn't lower the stability of the release line.  So, this should block the 2.1.1 release (unless support for offline scanning is reverted instead, which I would not advocate doing).

**Comment by dlmarion** [comment]
We are no longer planning on allowing eventual scans on offline tables.
