### ISSUE TITLE
Explore adding tests for per table classpath configuration with plugins

### ISSUE THREAD

**Issue by cshannon** [apache/accumulo#3156]
As part of removing the deprecated CompactionStrategy in #3112 @keith-turner [noticed](https://github.com/apache/accumulo/pull/3112#discussion_r1059499042) that there were a lack of testing for the Compaction plugin feature as well as just all plugins in general. We should explore adding in testing for for per table classpath for Compaction plugins as well as all other plugins that are part of the SPI.

**Comment by DomGarguilo** [comment]
I think this would be helpful as well. I was looking for examples of `CompactionSelector`s and `CompactionConfigurer`s to get a better understanding of how to create new ones. There are a few tests with different `CompactionSelector`s but very few places that `CompactionConfigurer`s are tested.

**Comment by ctubbsii** [comment]
We don't need to test per-table classpath configuration, because that's not how the classloader works now (not required to anyway). For testing plugins, we should test: 1) the plugin aspect/nature (making sure it executes correctly when configured to do so), and 2) unit test individual plugin implementations separately.

The context class loader factory can be tested by providing a custom factory that returns the system classloader, but does something else that can be detected in the test, so we know the plugin aspect is working properly. If we have any reference implementations of this factory in our code, we can have unit tests for those, that ensure they return the expected classloader when provided with a given mocked input environment. Other plugins should be tested similarly: 1) test the pluggable aspect (may require integration test), and 2) unit test provided implementations.

**Comment by DomGarguilo** [comment]
Given what I have gathered from the feedback above, it doesn't seem like there is much to do here. The plugins that are in the codebase now are mostly just examples that are used to test that custom plugins can be created and take affect.

**Comment by cshannon** [comment]
I went ahead and closed this as it doesn't seem like there's much to do as Dom pointed out.
