### ISSUE TITLE
Accumulo will fail to start if startup.tserver.avail.min.count is too large

### ISSUE THREAD

**Issue by ivakegg** [apache/accumulo#3157]
In 1.10 we set master.startup.tserver.avail.min.count to 174 and master.startup.tserver.avail.max.wait to 5m.  At one point the system was taken down and upon restart we only had enough nodes to start 157 tservers.  We expected the system to continue startup after 5m but instead it continued blocking.  The last master info message we saw was:

Blocking for tserver availability - need to reach 174 servers.  Have 157 Time spent blocking 1575 sec.

That would be 26.25 minutes and we were still blocked.

It appears that the master.startup.tserver.avail.max.wait is not working as we expected.  We had to manually modify the master.startup.tserver.avail.min.count in zookeeper to be able to start the system.  Either we need to update the master to break out of the loop once max.wait is met, or add a master.start.tserver.avail.max.iterations property or something like that.

 - Affects 1.10 but I believe this code is unchanged in 2.1
 - OS: CentOS 7.3

**Comment by ddanielr** [comment]
This while loop handles the waiting logic for startup.
https://github.com/apache/accumulo/blob/1.10/server/master/src/main/java/org/apache/accumulo/master/Master.java#L1516-L1530

Looking at the comparison, it breaks out if `minTserverCount` is less than amount of current servers.
https://github.com/apache/accumulo/blob/1.10/server/master/src/main/java/org/apache/accumulo/master/Master.java#L1514

Or if there are no more retries available from `tserverRetry`.
https://github.com/apache/accumulo/blob/1.10/server/master/src/main/java/org/apache/accumulo/master/Master.java#L1506-L1509
 
I'm not very familiar with the Retry class, but it doesn't look like the `maxRetries` value is set as part object creation, just `maxWait`. However, the `infiniteRetries()` method is called which sets `maxRetries` to `-1` and I would think, always allows retries to be possible. 

https://github.com/apache/accumulo/blob/18c4f1ab7167cbdf8123b6bbc5f57b728650ad21/fate/src/main/java/org/apache/accumulo/fate/util/Retry.java#L49

If this is indeed the problem, it could be fixed by either changing the while loop to be duration based, or calculating the correct amount of retries for the time interval and setting the `MaxRetries` param of `tserverRetry`.

**Comment by EdColeman** [comment]
The behavior may be desired or maybe not and is user dependent.  The initial use case for the min tservers was to protect against starting the master before at least X tservers were online.  What would happen is the manager processes would be started and then the tservers - and as soon as the manager saw one (or a few tservers) the metadata tables would be assigned and then it was off to the races, where almost everything would be assigned to a few tservers and then a lengthy delay with migrations and reassignments.  The tserver min count was to ensure the X servers would be available before the manager would proceed.  Maybe that's 25%, 50%, 99.999% of your servers? 

The whole thing can be avoided and handled external to Accumulo.  If the start-up sequence is ZooKeeper, Hadoop, tservers and then the manager processes.  The tservers will register with ZooKeeper and wait.  Users can then choose to validate that things are okay before proceeding.  And that "okay"  is up to the user.  Maybe you have strict requirements that with some kind of custom balancer that some nodes are more important that others where some things are pinned to servers with specific capabilities (say the metadata tables)  - then, maybe you'd want to make sure they were online and registered before that manager starts, and the actual count is less important.

Others, could decide that if I can't get to 25% I do not want to proceed - I don't care how long that is, without at least 25% I never want to start.  For others, it could be wait for 99.999%, but if I don't get that, well if we wait 30 minutes, I guess that what we have is as good enough, and all we can do for right now.

So, the count was basically a simplistic trigger-guard for a particular foot-gun.

**Comment by ivakegg** [comment]
OK then, I guess this is working as designed.  Thank you everybody.

**Comment by EdColeman** [comment]
This might still be valid and we can possibly improve the way we handle the interaction of the two values, or at least document the interaction(s) better.

I was just trying to caution that different users may have different expectations / needs.

- If number of servers is important and the driving requirement - set the timeout to infinite / never time out.
- If minimal restart time is the critical factor, use a low number of tservers and a relatively short time out. (and live with the consequences)
- ?

The thing is that the parameters should be considered a guard against a worst case start-up and that if users need more specific / special handling they should explore alternate solutions external to Accumulo and the provided example scripts and really just use these as a backup.
