### ISSUE TITLE
GitHub Actions Maven Build - Do we still need ZK 3.5.10 build?

### ISSUE THREAD

**Issue by dlmarion** [apache/accumulo#3201]
There is a Maven [build](https://github.com/apache/accumulo/blob/main/.github/workflows/maven.yaml#L73) as part of the GitHub Actions that uses ZooKeeper 3.5.10. Is this still needed for 3.0?

**Comment by ddanielr** [comment]
The [original commit](https://github.com/apache/accumulo/pull/2516) for adding the zookeeper `3.5.x` option was due to the upgrade from `3.5` to zookeeper `3.7` 


Before that upgrade, the test was just utilizing a previous version of hadoop. 
`- {name: 'hadoop-compat', javaver: 11, args: 'package -DskipTests -Dhadoop.version=3.0.3'}`
vs
` - {name: 'compat', javaver: 11, args: 'package -DskipTests -Dhadoop.version=3.0.3 -Dzookeeper.version=3.5.10'}`

I'm surprised there is still a compatibility test for Hadoop `3.0.3` since the log4j issues weren't patched in the `3.0.x` line.

Is compatibility testing is still desired? If so, what should drive the version number choice?

Additional details: 
- [HADOOP-18088](https://issues.apache.org/jira/browse/HADOOP-18088)

**Comment by dlmarion** [comment]
IMO we can remove this check for version 3.0 and beyond.

**Comment by ctubbsii** [comment]
Superseded by patch to update to 3.6 in #3200
