### ISSUE TITLE
Question on Differences between RFiles, 1.10.2 -> 2.1.1

### ISSUE THREAD

**Issue by avgAGB** [apache/accumulo#3267]
I've noticed recently that Accumulo 2.0+ has backwards compatibility in terms of being able to import rfiles from 1.10.2 for example, but the opposite is understandably not the case. I was wondering, would anyone be able to explain what exactly is the difference between the way the rfiles are written or structured between the two versions, and is there any way for a 2.1.1 rfile to be converted backwards to something that 1.10.2 could import? Or are the versions mechanically too different to convert?

**Comment by ctubbsii** [comment]
@avgAGB We occasionally add features to RFiles that make it support things we add to Accumulo. Those changes won't be understood by older versions of Accumulo, but they don't typically alter the fundamental storage concepts of RFiles. I believe the main feature added after 1.10 was the ability to support data emitted from a configured Sampler.

If you need to extract data from one RFile version and store it in an older Accumulo version, you could just create a scanner and scan the data in the file, storing it in whatever intermediate format you wish.

Since this issue tracker is mainly used by developers to track issues, you may have luck finding home grown solutions for your situation, or similar situations, that you can adapt, from the bigger audience of users if you post your question to [the user mailing list](https://accumulo.apache.org/contact-us/).
