### ISSUE TITLE
1.10.3-rc0 failing test: TabletServerResourceManagerDynamicCompactionPoolTest

### ISSUE THREAD

**Issue by DomGarguilo** [apache/accumulo#3283]
**Test name**
 - TabletServerResourceManagerDynamicCompactionPoolTest.testDynamicThreadPoolUpdates

**Describe the failure observed**
I have run into this failure twice now but it does not occur every time. 
The first time I observed the test fail with an assertion error at this line:
https://github.com/apache/accumulo/blob/ed75b4521094faa6f6e1037a444747390a120068/server/tserver/src/test/java/org/apache/accumulo/tserver/TabletServerResourceManagerDynamicCompactionPoolTest.java#L128
And the second time the test failed with `TestTimedOutException: test timed out after 20000 milliseconds` at this line:
https://github.com/apache/accumulo/blob/ed75b4521094faa6f6e1037a444747390a120068/server/tserver/src/test/java/org/apache/accumulo/tserver/TabletServerResourceManagerDynamicCompactionPoolTest.java#L134

The following are the steps I took to run the test when it failed:
1. Download the [1.10.3.rc0 candidate artifact](https://repository.apache.org/content/repositories/orgapacheaccumulo-1099/org/apache/accumulo/accumulo/1.10.3/accumulo-1.10.3-src.tar.gz)
2. Extract the contents and cd into that directory 
  `tar -xvf accumulo-1.10.3-src.tar.gz && cd accumulo-1.10.3`
3.  Run the test command `mvn clean verify` 

**Testing Environment:**
 - Version of this project: 1.10.3-rc0
 - OS: Pop!_OS 22.04 LTS x86_64
 - Java: 11.0.18
 - Maven: 3.6.3

**Comment by ctubbsii** [comment]
The timeout failure could be because the machine was resource-constrained. A lot of tests get flaky when running in a relatively constrained environment, when it comes to timeouts.

However, I'm interested in the assertion error... if there's an associated stack trace, that could be helpful. I have not been able to reproduce this bug, and I can't find any history of this test failing like this. It could also be another resource-constrained issue, if a thread died because of memory or something. Please let us know if you can figure out anything else about this test failure. For now, though, I'm going to proceed in preparing a 1.10.3-rc1 without addressing this, since I can't reproduce it.

**Comment by Manno15** [comment]
I was also unable to reproduce this error. Was this seen only when running the entire test suite or did you see it when running the test by itself?

**Comment by DomGarguilo** [comment]
> However, I'm interested in the assertion error... if there's an associated stack trace

I only saw the test fail with the assertion error once and do not have the stack trace from that run unfortunately.

**Comment by DomGarguilo** [comment]
I tried bumping up the timeout on this test and have not seen it fail again so it's probably some resource constraint issue on my machine. Closing for now.
