### ISSUE TITLE
Suspension may not be properly cleared for tablets in some cases

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#3314]
**Describe the bug**
While working on #3284 I noticed this code :

https://github.com/apache/accumulo/blob/15c9f55280f4ce28a80b800f1e05128f33c85db3/server/base/src/main/java/org/apache/accumulo/server/manager/state/MetaDataStateStore.java#L140-L151

Tracing back what calls this method, AFAICT its only passed TabletLocationState objects with a non-null suspend. If my analysis is correct then this method ignores all of its input.

Seems like the code should be :

```java
      for (TabletLocationState tls : tablets) {
        if (tls.suspend != null) {
          tabletsMutator.mutateTablet(tls.extent).deleteSuspension().mutate();

        }
     }
```

This need a bit more investigation.  Took a quick look at 1.10 code and it seems to be the same there.

**Expected behavior**
The suspension is properly cleared.

**Comment by keith-turner** [comment]
TabletLocationState objects passed to the unsuspend method have a state of SUSPENDED

https://github.com/apache/accumulo/blob/15c9f55280f4ce28a80b800f1e05128f33c85db3/server/manager/src/main/java/org/apache/accumulo/manager/TabletGroupWatcher.java#L296

To have a state of SUSPENDED, suspend must be non-null

https://github.com/apache/accumulo/blob/15c9f55280f4ce28a80b800f1e05128f33c85db3/core/src/main/java/org/apache/accumulo/core/metadata/TabletLocationState.java#L133-L149

**Comment by ivakegg** [comment]
As far as I can tell you are absolutely correct.  If the suspend is set, then the tablet is suspended and hence that check for != null is exactly the opposite of what it should be.

**Comment by keith-turner** [comment]
> I hate to say this but "How did this ever work?"

It feels like the intention of this code may be to remove the suspended indicator in the metadata table when a tablet is suspended but has no current or future location.  But not completely sure about that, need to look into to it some more.

It seems the code has always behaved this way, so not sure what that means.  Does that mean there is some rare edges case that is not being properly handled?  Or does something else compensate for what this code was trying to do?

**Comment by dlmarion** [comment]
> I hate to say this but "How did this ever work?"

I tried to track through this. This code is pretty convoluted.  While the tablet is in a suspended state, the TabletGroupWatcher continues to [call](https://github.com/apache/accumulo/blob/2.1/server/manager/src/main/java/org/apache/accumulo/manager/TabletGroupWatcher.java#L282) `hostSuspendedTablet`.  After the suspension time has passed `hostSuspendedTablet` [adds](https://github.com/apache/accumulo/blob/2.1/server/manager/src/main/java/org/apache/accumulo/manager/TabletGroupWatcher.java#L424) the tablet to the `unassigned` map so that it can be assigned. I can't see anywhere in the assignment process where the suspension flag is removed from the tablet metadata. So, I assume that the tablet gets assigned and hosted, and the suspend information still exists. Once hosted, `TabletLocationState.getState()` will return `HOSTED` instead of `SUSPENDED`. The next time the Tablet gets [unloaded](https://github.com/apache/accumulo/blob/2.1/server/tserver/src/main/java/org/apache/accumulo/tserver/UnloadTabletHandler.java#L123) from a TabletServer the code goes down a path of passing `-1` for the `suspensionTimestamp` and ends up deleting the suspension tablet metadata information [here](https://github.com/apache/accumulo/blob/2.1/server/base/src/main/java/org/apache/accumulo/server/manager/state/MetaDataStateStore.java#L127).

**Comment by dlmarion** [comment]
I think that this is working as intended. I'm going to move this to the elasticity project as it might be an issue there, but I think it's good for 2.x and 3.x.
