### ISSUE TITLE
Spamming log messages

### ISSUE THREAD

**Issue by ivakegg** [apache/accumulo#3394]
The message that denotes that a compaction strategy is deprecated is being output as a WARN message.  This is spamming our logs.  Please remove that message or make it part of a logger for a separate class for which we can turn logging off.

Accumulo 2.1.1-SNAPSHOT
CentOS 7.3

**Comment by ctubbsii** [comment]
Can you provide the exact message? It would save a ton of time, because we're doing stuff like this in multiple places for different reasons.
Also, I'm sure you've considered this, but it's worth a mention that, in general, the best way to avoid log messages about deprecated items is to use their replacements.

**Comment by ivakegg** [comment]
https://github.com/apache/accumulo/blob/11320ee8e6906265f9c10e0974322a6665f02df4/server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/CompactableUtils.java#L498

**Comment by ctubbsii** [comment]
@ivakegg Have you considered using a RegEx filter for the specific messages you want to control? 
https://logging.apache.org/log4j/2.x/manual/filters.html#regexfilter
You can configure it so that the filter is only used on the specific logger that emits that message, so you're not doing regex matching on everything, which might be expensive. You could also use a more efficient custom filter, too.

Using filters is a more flexible general solution, than moving specific messages into their own logger classes.

I'm just reluctant to hide or reduce warnings about use of deprecated features for everybody, since we really want users to move away from them, in general. Having said that, I agree there can be a certain amount of messaging that is too much. I'm not exactly sure where the threshold should be for this particular one, so I'm looking first to general solutions. And I think filters are good general solutions.

**Comment by ctubbsii** [comment]
Closing this issue for now, since there are two documented workarounds (1. stop using deprecated props, and 2. use regex filter for logging), and no response from reporter since last comment a month ago.
