### ISSUE TITLE
Provide a way to modify property values without a running cluster

### ISSUE THREAD

**Issue by EdColeman** [apache/accumulo#3423]
When the properties changed from being stored individually on ZooKeeper nodes to a single node in a compressed blob, the ability to modify properties without a cluster is no longer available.  Something similar to the `zoo-info-viewer` should be provided that can be used to change property values with only ZooKeeper running.

The tool should provide a text output similar to `zoo-info-viewer` that can be edited and then re-imported.

Alternative:

The shell config command will currently not work without a tserver - if the shell can be modified to use a manager, then it may be sufficient to use the shell with ZooKeeper and a manager running.

**Comment by ctubbsii** [comment]
`zoo-info-editor`? Or rename `zoo-info-viewer` to `zoo-info-tool`?

**Comment by dlmarion** [comment]
> The tool should provide a text output similar to zoo-info-viewer that can be edited and then re-imported.

Alternatively, you could use the same `-s` syntax that the Shell uses instead of parsing text input.

`ManagerClientServiceHandler.set(Table|Namespace|System)Property` all end up calling `PropUtil.(set|remove)Properties()`. PropUtil is already in server-base along with the other utilities. As a quicker solution, we could:

  1. Modify PropUtil to implement `KeywordExecutable` and maybe give it a better name in `keyword()`
  2. Implement `execute()` to do the same argument parsing that `ConfigCommand` uses and call the appropriate PropUtil method.

**Comment by dlmarion** [comment]
This will basically be impossible if #3433 is implemented.

**Comment by ctubbsii** [comment]
> This will basically be impossible to do in the Shell if #3433 is implemented.

No. The idea here was to have a separate server-side admin utility for this, not to implement it in the shell, which is intended as a client-side utility that uses our public API.

**Comment by EdColeman** [comment]
Can be closed with #3445
