### ISSUE TITLE
Add tests for AccumuloConfiguration.isPropertySet

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#3486]
**Is your feature request related to a problem? Please describe.**

Was looking into #3491 and as part of that investigation I was wondering if AccumuloConfiguration.isPropertySet() was behaving properly.  Looked through all of the isPropertySet() implementations and each seemed good.  Looked at the tests and could only find that SystemConfiguration had a test for isPropertySet() and that it only tested the true case and not the false case.

**Describe the solution you'd like**

Adding unit test that verify the expected behavior of AccumuloConfiguration.isPropertySet for each impl would be useful to avoid regressions. Not sure if its workable, but wondering if it would make sense to create generic unit test suite for AccumuloConfiguration impls that can verify certain expected behaviors OR is it easier to have a unit test for each impl.

**Comment by DomGarguilo** [comment]
I am working on adding these tests and ran into something that I am a bit confused about and was hoping someone could help clear up for me.

The impl of `isPropertySet` in `DefaultConfiguration` just returns false:
https://github.com/apache/accumulo/blob/4ec6dd2054d6a588dfc5a9a5f139d32799c90e83/core/src/main/java/org/apache/accumulo/core/conf/DefaultConfiguration.java#L63-L66
It is not evident to me why this is the case and seems odd that it returns false even when the property exists within the `Map<String,String>` of properties. This affects the behavior of other implementations as well, for example `SiteConfiguration.isPropertySet` which checks its `parent` config which is a `DefaultConfiguration` resulting in similar behavior as describes above in certain scenarios:
https://github.com/apache/accumulo/blob/4ec6dd2054d6a588dfc5a9a5f139d32799c90e83/core/src/main/java/org/apache/accumulo/core/conf/SiteConfiguration.java#L248-L251

Why is `DefaultConfiguration.isPropertySet` implemented this way?

**Comment by keith-turner** [comment]
> Why is DefaultConfiguration.isPropertySet implemented this way?

The goal of the method is to determine if a user explicitly set a given property.  The reason DefaultConfiguration always returns false is that a user can not explicitly set a prop on it.

**Comment by DomGarguilo** [comment]
> > Why is DefaultConfiguration.isPropertySet implemented this way?
> 
> The goal of the method is to determine if a user explicitly set a given property. The reason DefaultConfiguration always returns false is that a user can not explicitly set a prop on it.

That makes sense. In #3676 I added some javadoc to `isPropertySet()` to explain this.

On another note, I am wondering (for what seems like the rest of the AccumuloConfiguration implementations) if the `isPropertySet()` and the `get()` method implementations should be more tightly coupled? Maybe the `isPropertySet()` checks the property against the return value of `get()` for null so that the two do not diverge accidentally at somepoint.

**Comment by ctubbsii** [comment]
> Maybe the `isPropertySet()` checks the property against the return value of `get()` for null so that the two do not diverge accidentally at somepoint.

The point of `isPropertySet()` is completely independent of the null-ness of the return value of `get()`. There's no synchronicity between them to check. They are already divergent. Null or not null just means that's the current value. It says nothing about whether a user set that value or if that's the default. That's why `isPropertySet()` was created... to intentionally keep it independent from the value returned from `get()`.

**Comment by EdColeman** [comment]
Fixed with #3676
