### ISSUE TITLE
Accumulo goal state not visible on all pages

### ISSUE THREAD

**Issue by ivakegg** [apache/accumulo#3548]
ticket #3373 added back the display of the system goal state but only on the manager server overvew page.  This should be moved into the title bar along with the links so that is does not matter which page you are on.

Accumulo 2.1.1

**Comment by DomGarguilo** [comment]
I can start looking into this. It seems like reasonable idea to me but am interested to hear others opinions on adding this.

**Comment by ctubbsii** [comment]
The goal state is only a manager goal state. It doesn't impact other services. It seems reasonable to me that it should be associated only with the manager details, in order to avoid the confusing implication that it is somehow a system-wide thing. But, I can see the advantage of seeing the manager's goal state on other pages. Another thing to consider is that this concept of a manager safe mode is going to change dramatically with the elasticity branch, where there are expected to be multiple managers in future, so I'm hesitant to make a change to the current behavior that will train users to think about it now in a way that will be incorrect in future.

**Comment by ctubbsii** [comment]
Perhaps we can put something in the nav menu "stop lights" next to the manager, so it's dot is yellow when in safe mode (and has the words SAFE MODE next to it in the menu), and that propagates up to a yellow dot when the menu is collapsed?

**Comment by ivakegg** [comment]
I like that idea @ctubbsii with a caviot.  Given it is common for some of the tservers to be down, then a yellow dot on the Servers menu would easily be ignored.  Perhaps the Servers menu can be expanded into the title bar so that manager, tservers, and gc are always visible.

**Comment by ctubbsii** [comment]
@ivakegg Expanding the menu into the title bar would be difficult to do without mangling the display, especially for smaller screens. But we could use a different icon that propagates up, so instead of a dot, it's something like https://icons.getbootstrap.com/icons/exclamation-triangle/ next to the rolled-up servers menu, and also next to the Manager link in that menu. And we could make sure that the icon is the same as the one shown on the manager page itself next to the message about being in safe mode, so it's intuitive that the icon in the menu is related to the message with the same icon on the manager page.

**Comment by DomGarguilo** [comment]
What if instead of a collapsible server dropdown menu, the three servers had their own separate link in the nav bar next to one another?

**Comment by DomGarguilo** [comment]
I made the following changes to the nav bar:

![image](https://github.com/apache/accumulo/assets/47725857/6faa5e7c-8225-4917-8b21-0f9dcaf7feba)

It was mentioned in a previous comment about changing the color of the dot next to the manager server when it is in safe mode. Right now it does not change due to the manager being in safe mode but i can try adding that if what I have so far is looking good.

**Comment by ctubbsii** [comment]
> What if instead of a collapsible server dropdown menu, the three servers had their own separate link in the nav bar next to one another?

That's the solution I said above that I thought would be "mangeled", especially on smaller screen widths. It diverges from the attempt to try to create a consistent minimalistic theme in the bar. So, I think they should stay collapsed in a menu, but a small and distinct visual element can be used that propagates up in the safe mode case (or other unique, rare, cases) to replace the dot.
