### ISSUE TITLE
Decide what to do with property tserver.last.location.mode

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#3596]
The property tserver.last.location.mode can have a value of assignment or compaction. When its compaction it sets the tablets last location when a tablet compacts on a tserver.  However since tablet servers no longer compact tablets this property may no longer be have a reason to exists. 

Noticed this while working on #3592

**Comment by dlmarion** [comment]
If tservers and compactors are running on the same host, this it's possible that `compaction` could still have an effect.

**Comment by ctubbsii** [comment]
While it may still have an effect, and could still be useful, I would like to point out that the reason the property exists was mainly to change the default assignment behavior to the `assignment` mode. Prior to this property existing, the default behavior was hard-coded in the `compaction` mode. The compaction mode itself was a best-effort to achieve data locality. It's not clear that the benefits were very substantial, though. Tablets can migrate around, and the location where data was most recently compacted may not even be the location where most of the tablet's data is stored. It's also possible that none of the user's data is local, even with the mode set to compaction... as that's dependent on very specific assumptions about HDFS behavior that may not hold (the assumption that there's a local copy made for each block replica). A lot of those assumptions fall through when you consider erasure coding instead of replication, data S3 instead of HDFS, differences in user configuration for replication, the fact that a data node might not even be running on the same node as the tserver, etc.

I think this property could be removed if users have more metrics about where tablet files are being compacted, and could use that information to exercise fine-grained control over tablet assignments by some other means. Then again, in a world where most of Accumulo is offline and hosted only ondemand, I'm not sure it's really going to matter, because we're no longer going to care as much about balancing thrashing or churn on assignment locations due to rebooting a cluster.
