### ISSUE TITLE
Remove property tserver.compaction.major.delay

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#3606]
The tserver no longer does compactions and those were removed in #3604, need to remove this property.

**Comment by EdColeman** [comment]
In general, are the properties (and metrics) that are being removed, are there equivalents in the new code?  We should look to provide a mapping from previous -> new so that users that may need these setting know how to map them to the new equivalent.

 If it is a straight removal - then that should be noted too.

Maybe we start a section in the release notes that we update as we go along?  It may be easier than trying for identify or remember all of the changes at the end?

**Comment by jmark99** [comment]
Closed by #3950
