### ISSUE TITLE
Explore only scanning tablets known to need attention in TGW when time period has not elapsed.

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#3666]
This issue is a follow on #3447.  In the 3447 a queue was added for tablets that are known to need attention for the TGW.  The TGW has a configured period to do a full metadata scan.  Could the TGW be modified to only scan the new queue introduced in 3447 when its time period has not elapsed? This could avoid a full metadata scan when only a few tablets need attention.

**Comment by dlmarion** [comment]
Regarding the changes that were added to the ManagerClientServiceHandler in #3447 , I don't think that the TabletGroupWatcher waits for the full interval because an event is sent to the EventCoordinator [here](https://github.com/apache/accumulo/blob/elasticity/server/manager/src/main/java/org/apache/accumulo/manager/ManagerClientServiceHandler.java#L701).

> Could the TGW be modified to only scan the new queue introduced in 3447 when its time period has not elapsed?

I think it *does* not wait for the time period to elapse if the EventCoordinator is notified. Maybe we could make this more explicit by invoking the EventCoordinator in TabletStateStore.addTabletStateChange implementations. In that case I think you would want the opposite, where you don't scan the metadata unless the time has elapsed.

**Comment by keith-turner** [comment]
The approach I am working on at the moment is making the event coordinator accept different types of events so that the TGW can respond accordingly.  Currently have the following events types.

 * ALL : an event that impacts all datalevels off accumulo.  Like a tserver dying.  This kind of event will make all the TGWs do a full scan.
 * DATALEVEL : An event that impacts an entire datalevel.  This happens when the TGW has made changes and wants to immediately run again.  This type of event will only make one TGW do a full scan.
 * TABLE: An even that impacts an entire table.  This happens after something like table creation.  Only one TGW will respond to this event and it may only scan the data for that table.
 * TABLE_RANGE : An event that impacts a range within a table.  This happens with things like compaction, split, and on demand hosting request. Only one TGW will respond to this event and it may only scan the data in a that range of the table.

I am working to make the TGW have different behavior depending on the type events that have happened and the time since it last full scan.  So if a TABLE_RANGE event comes in and its only been a few seconds since the last full scan, then the TGW will just handle the tablets in that range and not do another full scan.

When the TGW does do a full scan, still want the behavior introduced in #3447 where the more targeted events above are injected for immediate processing.

**Comment by dlmarion** [comment]
@keith-turner  - does #3705 close this?
