### ISSUE TITLE
Avoid storing split points in Zookeeper

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#3709]
In the elasticity branch split code was moved from the tablet server to the manager.  The Manager executes a FATE operation to perform splits.  This FATE operation will store the split points in ZK memory. As part of a #3705 a new test was added the creates 1 million tablets.  This test adds 10K splits at a time. The test was manually modified to do 100K splits at a time and it caused ZK and/or the manager to fall over.

It would be better if the split points were stored in a tmp file.  The create table fate operation already does this when it has splits.  The new split fate code could probably share code with create table.

**Comment by cshannon** [comment]
In general, I was thinking as we go to Elasticity it might be nice to see if we can get more things out of Zookeeper and store in Accumulo itself. Zookeeper can be a bottleneck and other projects are dropping it for performance reasons as clusters are getting larger (such as Kafka). In theory the changes in Elasticity will allow us to scale up with many more tablets since they are offline/ondemand which would require a lot more metadata tracking in ZK and I can see that could cause issues, like in this case.

For example, for the split points here, I'm wondering if in the future it would be make sense to store the split points in Accumulo in another table. Anyways, just a thought, in this case the tmp file probably makes sense since it's already doing that elsewhere and code could be shared. There also might be reasons that isn't possible but again this is just more of a general comment that could be applied to other situations too.

**Comment by dlmarion** [comment]
@cshannon  - Is this issue OBE now that we have user FATE operations being stored in an Accumulo table instead of ZooKeeper?

**Comment by cshannon** [comment]
I believe so, the information is stored in SplitInfo which is persisted as part of the Repos in the Accumulo table now. So at least for the user tables it's no longer in ZK and I don't think we need to worry about it being in ZK for metadata.

**Comment by dlmarion** [comment]
@jmark99 - are you working this?
