### ISSUE TITLE
Remove writer class

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#3735]
**Describe the bug**
In #3733 the internal writer class was refactored to use a batch writer.  Also some code was refactored to use the batch writer directly instead of the writer.  The remaining code use the writer class is the replication code, so it may be easy to completely remove the class in 3.1.x.

The writer class used to use the single mutation RPC mentioned in #3734.

**Comment by ctubbsii** [comment]
If #3733 is split into two tasks: one to refactor to use the batch writer, and the other to fix the BatchWriter's writes-after-close bug, then when the first task is merged forward, we can just delete it from 3.1, since it will be unused in 3.1 after that. Right now, it's hard to do that separately, because the changes in #3733 that would allow us to do this are currently entangled with the bugfix there.
