### ISSUE TITLE
Reevaluate setgoal and getgoal shell command names

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#3800]
See this discussion : 

https://github.com/apache/accumulo/pull/3785#discussion_r1339509741

**Comment by EdColeman** [comment]
The was / is (?) a utility class `../manager/state/SetGoalState.java` - we may want to try and be consistent with naming - (assuming the utility is still needed.)

**Comment by jmark99** [comment]
The downside of using something like `setgoalstate` is that is does not offer any more context than `setgoal`, which was the impetus for the initial issue to be opened.

**Comment by EdColeman** [comment]
If we go with `sethostinggoal` then we may want to consider renaming the SetGoalState class (or make an alias and keep both?)  There are downsides to changing the class (esp. if referenced in the docs somewhere), but there may be a benefit if both methods (shell, utility) are similarly named so that it is clear that the are doing the same thing.

I am not advocating for one name or another, just wondering if we want to be consistent in this case.

**Comment by ctubbsii** [comment]
> The was / is (?) a utility class `../manager/state/SetGoalState.java` - we may want to try and be consistent with naming - (assuming the utility is still needed.)

That class was specifically setting a manager goal state. I think it's related, but not quite the same as what these are doing.

**Comment by EdColeman** [comment]
@ctubbsii is correct.  My fault - I confused the two commands and their intent.

**Comment by keith-turner** [comment]
> @keith-turner, @ctubbsii I like the idea of sethostinggoal and gethostinggoal. 

@jmark99 I like sethostinggoal and gethostinggoal

**Comment by jmark99** [comment]
Closed by #3842
