### ISSUE TITLE
Decide and test behavior of setting a tablet hosting goal for offline table

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#3856]
A new API for setting tablet hosting goals was added in the elasticity branch.  Need to decide how this new API should behave with offline tables and test this behavior.

Also should update [this table](https://cwiki.apache.org/confluence/display/ACCUMULO/A+More+Cost+Efficient+Accumulo) with the behavior.

**Comment by dlmarion** [comment]
Need to update or remove https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=247828052

**Comment by dlmarion** [comment]
@keith-turner @ctubbsii - I think this issue pre-dates the change regarding online/offline vs enabled/disabled for table states. So my question, should a user be able to alter a table that is disabled? If not, then we can close this (and probably open an issue to enforce this).

**Comment by ctubbsii** [comment]
> @keith-turner @ctubbsii - I think this issue pre-dates the change regarding online/offline vs enabled/disabled for table states. So my question, should a user be able to alter a table that is disabled? If not, then we can close this (and probably open an issue to enforce this).
> 
> Edit: [This](https://github.com/apache/accumulo/pull/3851#issuecomment-1766507126) comment implies that it might be useful to change the state when disabled.

For a disabled table, I think the critical part is that the structure of the table can't be changed... you can't add or delete data, or merge tablets, or add split points, or change its files, etc. Also, we won't make it available for reads or other operations that require resources to be actively put to use, like creating a scanner. You should still be able to do non-destructive backup-type operations, like export table and clone. For metadata/config operations, I'm not so sure. I think there's value, for surgical/administrative/repair purposes, in being able to alter configuration and doing certain surgical operations to tablet state in the metadata, but I'm not sure if we want to open that floodgate to any of those types of operations, because if we do, then we might want to start allowing metadata-only operations like adding splits and merges, and there's good reasons to not allow that.

Perhaps we could restrict these metadata/config alterations to only surgical use with an admin/surgery tool, but they are disallowed via the public API? I'm not sure. You can already do these kinds of surgical operations manually by editing the metadata table and ZK directly... so, I think this is really a question of what the permission checks are for doing it through the public API or if we provide any particular tooling for it (which is really two separate questions).
