### ISSUE TITLE
Add properties to exit server process when idle

### ISSUE THREAD

**Issue by dlmarion** [apache/accumulo#4076]
In Elasticity we intend to support dynamic scaling of the TabletServer, ScanServer, and Compactor processes. When making decisions based on metrics, you could determine that you don't need X number of processes, but you don't really know if the current processes are idle or not. For example, you may decide that you don't need X compactors running because the metric for the compaction queue length is zero. You decide to shut down some number of Compactors, but some of them are doing work, which is lost and then those compactions get re-queued.

Additionally, some frameworks may not have a downscale mechanism that allows for the graceful termination of a process. For example, the Kubernetes pod termination [process](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-termination) sends a SIGTERM to the pod, waits a configurable amount of time, then sends a SIGKILL.

We could create two properties for the Compactor, ScanServer, and TabletServer processes to help with graceful downscaling: `idle.shutdown.enabled` and `idle.shutdown.period` . These processes could exit when:

  1. `idle.shutdown.enabled` is true (default: false)
  2. and, in the case of the Compactor, it has been `idle.shutdown.period` since it completed its last compaction, or in the case of the TabletServer and ScanServer, it has not hosted a Tablet in `idle.shutdown.period`.

In the case of the Kubernetes Horizontal Pod Autoscaler [HPA], scale down can be [disabled](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#example-disable-scale-down). This would allow using the HPA to scale up based on metrics (queue lengths, etc), and to scale down based on inactivity.

**Comment by keith-turner** [comment]
Wondering if this setting could work with the use case where a minimum is desired.  For example would like to keep between 3 and 100 scan servers running based on activity.   Seems like this setting would always scale down to zero when things are idle.

**Comment by dlmarion** [comment]
Yeah, that's a good point. Seems like scaling down to zero if there is no work could be valid.

**Comment by dlmarion** [comment]
I created #4078 as an initial implementation, but it doesn't implement a minimum. I could add a property for the mininum and implement a check that counts the number of children in ZooKeeper for the process (to include the resource group), but I think that would be best-effort and not guaranteed.

**Comment by keith-turner** [comment]
> I created https://github.com/apache/accumulo/pull/4078 as an initial implementation, but it doesn't implement a minimum. I could add a property for the mininum and implement a check that counts the number of children in ZooKeeper for the process (to include the resource group), but I think that would be best-effort and not guaranteed.

I think implementing a minimum would be tricky and is not needed now. I just looked at the PR and was wondering if metrics could be emitted that indicate an idle time.  Like each server process could emit a metric, hey I have been idle for Xms.  Not sure if this is something an HPA impl could leverage though.

**Comment by ctubbsii** [comment]
I think that a shutdown request handler and exposing sufficient metrics for an external decision-maker to request a shutdown would probably be better than baking in properties and logic to handle them. It would put less burden on Accumulo to reimplement complex scenarios that might be valid use cases. Just keeping it simple by being able to handle a shutdown request and letting the decision happen outside of Accumulo can keep Accumulo's complexity low without limiting the supported use cases.

For instance, Amazon EC2 can scale dynamically through external mechanisms and although I'm not really an expert on these systems, I believe it to be possible emit metrics from your VMs to drive the decision. From what I understand, the VMs just receive an ACPI power off signal, and the OS can shut down gracefully, including triggering any systemd services to shut down gracefully. That could easily be done for Accumulo services with a good systemd unit file, whether it involved a graceful shutdown, or just killing the process.

I also had a discussion with a researcher awhile back who had some expertise in designing robust systems. Their argument was that if your system is robust enough, it's not worth even baking in any kind of graceful shutdown handling... just killing the process would be sufficient because graceful shutdowns are just redundant code paths where more consistency-related errors can occur. I think he had a good point, but I don't think I could communicate his arguments as well as he could, and I can't remember his name. So, I take it as just something to consider.

**Comment by dlmarion** [comment]
> I think that a shutdown request handler and exposing sufficient metrics for an external decision-maker to request a shutdown would probably be better than baking in properties and logic to handle them

What do we do if the orchestration system that users might use doesn't allow invoking commands, shell scripts, etc. to make the shutdown request as part of the orchestration process?

**Comment by dlmarion** [comment]
> What do we do if the orchestration system that users might use doesn't allow invoking commands, shell scripts, etc. to make the shutdown request as part of the orchestration process?

Answering my own question here: I guess someone could write their own rudimentary scaler by:

1. Monitoring for the metrics they are interested in
2. For downscaling, invoke the shutdown request and waiting for the command to return
3. Use the `kubectl scale` command to increase or decrease the number of pods.

I'm not quite clear on how item 2 would work w/r/t the java application running inside a Pod. It might be dependent on the networking.

**Comment by dlmarion** [comment]
I would be interested in hearing more opinions about if/how we implement this. Personally, I'm a proponent of implementing this - mainly because it helps solve an issue that is lacking in the HPA (FWIW, I found some discussion related to adding functionality to the HPA downscaling mechanism at https://github.com/kubernetes/kubernetes/issues/107598). However, I do agree that in cases where users are not using Kubernetes and doing things manually, they will have to use some other existing scheduling tool (e.g. docker swarm) or write their own.

**Comment by keith-turner** [comment]
Looking over the kubernetes issue, it seems like if this were done with metrics that maybe one could have a custom script that periodically updates the shutdown cost of pods using metrics data and HPA could use that to make decisions.  However I am not sure I understood that correctly.

One thing I like about the approach in this issue is that offers a way to scale down that does not kill compactors in the middle of a long compaction.  If only using HPA and it scales down, then it may kill a compactor that has been working on a compaction for hours when it could have killed a compactor process that was doing nothing.

Ideally we could use HPA+metrics to do this because it would operate within its min and max, but that may not be possible currently, not sure. Also using HPA+metrics puts all of the scaling config in one place instead of having some scaling config in Accumulo and some in Kubernetes.   If in the furture we find a way to accomplish the goals in this PR with HPA+metrics we may end up with redundant code in Accumulo if this is added.  So we could deprecate and remove these change then if we add them now.

I don't think the lack of a minimum is big deal for compactors.  If the number of compactor processes goes to zero, its not a big deal as long when compaction jobs is queued some compactors are started.  I don't think anyone cares if there is some latency before a queued compaction starts.  For scan servers and tablet servers though, I could see a desire to keep a minimum number of those processes running to make sudden queries on a system that was idle more responsive.  I am in favor of the proposal in this issue for compactors as it offers a simple way to scale down that avoids killing compactors that are not idle.  I am uncertain about the usefulness of the idle setting for tablet servers and scan servers though.

It may be good to work through using this new property in K8s to scale compactors up and down and see if it works as desired.

**Comment by dlmarion** [comment]
Some thoughts on probable scaling scenarios:

|Component|Metric or Condition|Action|Comments|
|-----------------|----------------------------|----------|--------------- |
| Compactor | Idle | Shutdown unless minimum specified ||
| ScanServer | Idle | Shutdown unless minimum specified ||
| TabletServer | Idle | Shutdown unless minimum specified ||
| Compactor | queue.length > x  | Start a new instance ||
| ScanServer | queue.length > x  | Start a new instance, if not enough resources terminate Compactor |Would client need to emit a metric for this?|
| TabletServer | hold.time > x  | Start a new instance, if not enough resources terminate Compactor |Hold time indicates pause of live ingest due to flush latency|

**Comment by ctubbsii** [comment]
> > I think that a shutdown request handler and exposing sufficient metrics for an external decision-maker to request a shutdown would probably be better than baking in properties and logic to handle them
> 
> What do we do if the orchestration system that users might use doesn't allow invoking commands, shell scripts, etc. to make the shutdown request as part of the orchestration process?

It seems to me that if their orchestration system can't handle orchestrating the processes with a simple signal to start or stop it, it's not a very good orchestration system. But even if user's don't have that, they'll have *some* way to send network commands to the servers from clients (otherwise, how would they communicate with the distributed system?), and could supplement their orchestration system with commands triggered outside of the limits of that system.

I don't think the user's choice to use an inadequate orchestration system is sufficient requirement to bake in orchestration directly into Accumulo. We should provide good interfaces, so users can integrate with their environment, but we shouldn't take it on ourselves because users *might* make a choice to deploy Accumulo in an environment without providing their own environmental tools that suit their particular requirements.

If it were a common thing for orchestration systems to not be able to start/stop processes or send/receive signals to processes, then perhaps my opinion about building this might be different (though I'd still prefer to consider building it around Accumulo rather than within, to avoid scope creep and bloat). But, I think the status quo is exactly the opposite. I think it would be unusual for an orchestration system to *not* support this kind of integration with an application. Can you provide an example of a commonly used orchestration system that doesn't offer controls like this?

**Comment by dlmarion** [comment]
So, it's likely the case then that we will need to allow users to specify additional tags at server startup to emit with the metrics. For example, for Kubernetes, the specific pod name.  I'll work on modifying my PR to accept additional tags that get emitted **and** emit an idle time metric. Scaling down specific pods in Kubernetes does not seem to be a solved problem, so we'll need to provide enough information for users to do it on their own. Using this information they should be able to monitor for a metric, terminate an idle pod by its identifier, and reduce the number of replicas in the deployment so that new pods do not get started.

It's possible that there could be a race condition between terminating a pod and reducing the number of replicas in the deployment. I'm wondering if we might need an RPC that tells the server to not accept any new work (shutting down its Thrift server?).

**Comment by keith-turner** [comment]
> It's possible that there could be a race condition between terminating a pod and reducing the number of replicas in the deployment. I'm wondering if we might need an RPC that tells the server to not accept any new work (shutting down its Thrift server?).

I think we could defer making decision on an RPC to handle that case.  Race conditions will always be there when making decisions based on metrics that lag.  A goal could be to choose pods to shutdown in a way that is better than randomly choosing on average.    There may still be false positives, just want less false positives than choosing randomly.  Whatever end to end strategy is used could try to determine how much it improves over randomly choosing as a way of evaluating how good it is.

**Comment by keith-turner** [comment]
> So, it's likely the case then that we will need to allow users to specify additional tags at server startup to emit with the metrics.

That seems generally useful.  Were you thinking that all metrics emitted by an accumulo process would have these user specified tags appended?  How are you thinking user would specify these tags?

**Comment by dlmarion** [comment]
> > So, it's likely the case then that we will need to allow users to specify additional tags at server startup to emit with the metrics.
> 
> That seems generally useful. Were you thinking that all metrics emitted by an accumulo process would have these user specified tags appended? How are you thinking user would specify these tags?

I was thinkng of a new property, `general.micrometer.tags.additional` or something, that defaults to an empty string and is a user-supplied list of comma-separated `tag=value` pairs. For example:

```
general.micrometer.tags.additional:pod.name=blah;other.tag=foo
```

When the set of common tags is [initialized](https://github.com/apache/accumulo/blob/elasticity/core/src/main/java/org/apache/accumulo/core/metrics/MetricsUtil.java#L82-L95) for the process, we could just read the property there and add the tags.

**Comment by ctubbsii** [comment]
How about just `general.tags`?

**Comment by dlmarion** [comment]
I'm game for whatever makes the user think that they are providing additional tags. There are a base set which they don't have control over.

**Comment by ctubbsii** [comment]
> I'm game for whatever makes the user think that they are providing additional tags. There are a base set which they don't have control over.

To make it clear it's user-provided extra tags, then maybe `general.tags.extra` or `general.tags.user` or `general.metrics.user.tags`

**Comment by dlmarion** [comment]
#4078 has been updated to add the user tags property, add a general idle interval property which drives the incrementing of the idle metric, and removal of the idle stop feature.
