### ISSUE TITLE
Coordinator Log warn message needs improvement

### ISSUE THREAD

**Issue by ddanielr** [apache/accumulo#4219]
**Describe the bug**
Currently the log warning message alerts when  compactors have not checked in for a given queue in a specific time interval. 

This warning level message will show up when the system is in a normal working state. 

**Versions (OS, Maven, Java, and others, as appropriate):**
 - Affected version(s) of this project: 2.1.x and newer.

**Expected behavior**
The warning log message should only be emitted when the system is not in a normal working state. 

**Additional context**
If the warn message log is updated to consider running compactions and number of jobs in the queue before emitting the message, then this would reduce the number of warn messages that don't require user action.

1. If a queue size is zero, then the following two situations are possible: 
   a. The compaction service may have been removed, along with its compactors. In 2.1, that means the tserver should not have a corresponding compaction queue defined, and the queue should be removed from the check.
   b. The queue is empty, so the compactors have backed off checking. This situation will be addressed by #4217

2. If long running compactions are keeping compactors busy, then communication is still happening so the warn message is not accurate.

**Comment by keith-turner** [comment]
When I merged main into elasticity in commit 9550da7c838994f9f6e9547819566b01e4b1dc6e I omitted the changes from 05c2f45042ee91a5fe04702caa77ab19f78c0f9a / #4362 because it would have been a completely different implementation in elasticity and I did not want to reimplement it in a merge commit.  So reopening this issue because the work still need to be done in elasticity.
