### ISSUE TITLE
Create new util that wrap nanoTime

### ISSUE THREAD

**Issue by DomGarguilo** [apache/accumulo#4360]
Using nanoTime is more correct than currentTimeMillis, but using nanoTime correctly is tricky.  Thinking we may benefit from having an internal  class that wraps nanoTime and limits what can be done with it to operations that are known to work well with nanoTime.  Maybe something like the following.

```java
package org.apache.accumulo.core.util;

import java.time.Duration;

public class NanoInstant {
    private final long nanoTime;
    
    private NanoInstant(long nanoTime) {
        this.nanoTime = nanoTime;
    }
    
    public NanoInstant add(Duration duration) {
        return new NanoInstant(nanoTime+duration.toNanos());
    }
    
    // elapsed is the terminology used in the nanoTime javadoc
    public Duration elapsed(NanoInstant since) {
        return Duration.ofNanos(nanoTime - since.nanoTime);
    }
    
    public static NanoInstant now(){
        return new NanoInstant(System.nanoTime());
    }
}
```

_Originally posted by @keith-turner in https://github.com/apache/accumulo/issues/4358#issuecomment-1989346735_

**Comment by EdColeman** [comment]
It may help if it can be explained how this is an improvement over using the standard Java Instant class before going down this route,

**Comment by DomGarguilo** [comment]
Additional context:

> There is also a java.time.Instant class that seems like it could be useful in this situation as the value for the map. Having looked into it in the past, found Instant was also not good to use w/ System.nanoTime, but I can not remember the specifics.

_Originally posted by @keith-turner in https://github.com/apache/accumulo/pull/4358#discussion_r1520026952_

I can try looking into why Instant is not good to use with nanoTime.

**Comment by keith-turner** [comment]
Below are two reasons why using the Instant class is problematic if backed by nanoTime.

 * According to nanoTime java docs one should never compare two nanoTimes.  Instant extends `Comparable<Instant>`, so the interface supports an operation that should never be done w/ nanoTime.
 * According to nanoTime javadoc it does not represent wall time.  So even if converting the unit from nanos to millis, one should never compare currentTimeMillis() return to a nanoTime return.    The Instant class has a heavy feel of wall time w/ concepts like timezones in its API.  Comparing a wall time Instant and nanoTime derived Instant make work in the code but would be incorrect.

For the utiity name, `NanoInstant` is probably not good because its related to this type that has much wider capabilities than System.nanoTime could ever support.  Should probably just call the type `NanoTime` to tightly couple it to the very unique and narrow behavior of System.nanoTme.

**Comment by EdColeman** [comment]
If Instant was use consistently instead of trying to mix System.nanoTime and Instant would the issues go away?  Instead of `long now = System.nanoTime` and then needing to convert to a delta and the duration, if it was `Instant now = Instant.now()` and then comparing with another instant should not be a problem to use compare or any math operation available on instant (isBefore, isAfter...)

Instant may be heavy-weight, but when compared to a custom class it may not be that much more,

Also, the TZ and wall-clock support could be handy if we wanted to log an instant. In cases where the Instant could be log lived (say something over 15 minutes) then logging a date-time stamp looking thing could help looking at logs.   Reporting an instant was created 900,000 millis ago is not as helpful as saying 15 minutes ago or maybe better created at 12:15:00.000 UTC.

**Comment by EdColeman** [comment]
A light-weight approach may be to use static helper methods to do the conversions / comparisons and then keep the local variables as a long.

**Comment by keith-turner** [comment]
> Instant may be heavy-weight, but when compared to a custom class it may not be that much more,

Using Instant.now() would have the same problem as using System.currentTimeMillis for computing elapsed time.   System.nanoTime is the most robust way to compute elapsed time in java and that is why we use it.
