### ISSUE TITLE
Add specific hostname connection option for accumulo shell

### ISSUE THREAD

**Issue by ddanielr** [apache/accumulo#4823]
**Is your feature request related to a problem? Please describe.**
The accumulo shell communicates with the system by connecting as a random tserver.
This can be problematic as information like property site config information is based on the specific tserver connection.

**Describe the solution you'd like**
The shell should accept a specific tserver hostname parameter that it will attempt use for its connection details. 
This change allows users to debug issues with a specific tserver.

**Comment by ctubbsii** [comment]
This is not something our API supports. The shell should only use our public APIs. If we want to add this feature, we should add something to the AccumuloClient to use a specific server. However, this is tricky, because our client code only uses a random server for certain operations, and the set of servers from which it chooses depends on the specific RPC service type being used for that specific operation.

**Comment by ctubbsii** [comment]
An alternative to adding new APIs is to have the implementation read specific system properties that can be added for troubleshooting. For example, we could have properties that look something like:

```
org.apache.accumulo.client.rpc.<serviceType>.host=<host:port>
```

And then, if that property is set, instead of randomly selecting one, it just connects to that specific one for that specific service type. If we did this, it should just be set as a system property, though, and not added as a shell-specific command-line or connection option. The user could customize their `accumulo-env.sh` to add it to their `JAVA_OPTS` if they wished. Or they could set `JAVA_OPTS` themselves when they run `bin/accumulo shell`.

**Comment by dlmarion** [comment]
> The accumulo shell communicates with the system by connecting as a random tserver.
> This can be problematic as information like property site config information is based on the specific tserver connection.

I believe the random behavior that you are referring to only happens when the client is executing a method from the [ClientService](https://github.com/apache/accumulo/blob/3.1/core/src/main/thrift-gen-java/org/apache/accumulo/core/clientImpl/thrift/ClientService.java) or the [TabletServerClientService](https://github.com/apache/accumulo/blob/main/core/src/main/thrift-gen-java/org/apache/accumulo/core/tabletserver/thrift/TabletServerClientService.java).

The random connection logic is located [here](https://github.com/apache/accumulo/blob/3.1/core/src/main/java/org/apache/accumulo/core/rpc/clients/TServerClient.java#L60). Looking at the methods on the [TabletServerClientService$Iface](https://github.com/apache/accumulo/blob/main/core/src/main/thrift-gen-java/org/apache/accumulo/core/tabletserver/thrift/TabletServerClientService.java#L30), I think we should support specifying a specific server name for the ClientService only.
