### ISSUE TITLE
Use operation id column in MetadataConstrains to detect split mutation

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#4857]
The MetadataConstraints code uses the [presence of a directory column](https://github.com/apache/accumulo/blob/ab996d0d26df4b2ed2c1874289d5b785ecbe2686/server/base/src/main/java/org/apache/accumulo/server/constraints/MetadataConstraints.java#L325-L327) to detect a split mutation.  In 4.0.0 splits mutations will [set an operation id](https://github.com/apache/accumulo/blob/ab996d0d26df4b2ed2c1874289d5b785ecbe2686/server/manager/src/main/java/org/apache/accumulo/manager/tableOps/split/UpdateTablets.java#L209) and this could be used to detect a split more precisely rather than the directory column.

**Comment by cshannon** [comment]
I started to look at this now that the changes with #4852 were merged and it looks relatively straight forward. One thing I noticed, which might be better as a separate PR first because it also would affect 3.1, is the lack of validation for the directory column. I think it would be nice to add a check and new violation if that format is wrong. There is already a utility to do the validation: `ServerColumnFamily.validateDirCol()` I can work on a quick PR for that and test improvements, and another PR to use the opid in elasticity to detect splits.

**Comment by cshannon** [comment]
I'm going to open up a PR just for main for now and include the extra directory column validation check for two reasons. 

1. The violation codes have diverged between [3.1](https://github.com/apache/accumulo/blob/2e63b7140d04fee881f429e674db0f96df4c6183/server/base/src/main/java/org/apache/accumulo/server/constraints/MetadataConstraints.java#L239) vs [main](https://github.com/apache/accumulo/blob/f47f835c0be746bc32a52516fb0e89624574497c/server/base/src/main/java/org/apache/accumulo/server/constraints/MetadataConstraints.java#L267). In 3.1 there are only 10 violation codes and we have 16 in main. If we want to add a new violation code to 3.1 for the directory check, we either have to make it number 11 and then go try and change codes 11-16 in main (which may be error prone to try and find all the spots), or we would need to just make it code 17 in 3.1 ad skip 11 through 16. I am not sure which is best because skipping the numbers is a lot easier but a bit weird to have missing codes.
2. I don't think the changes in 3.1 would merge forward cleanly anyways. The metadata constraints code has diverged a bit with the changes in elasticity so it's likely there would just be merge conflicts anyways in both the metadata constraints class and the test for it so I think it would probably be simpler to anyways to just backport the change and merge forward an empty commit if we decide it is worthwhile to do that. (and figure out how to handle the error code)

**Comment by keith-turner** [comment]
For new error codes added in 3.1 we could start those at 310 or 3100 and new error codes added in 4.0 could start at 400 or 4000.
