### ISSUE TITLE
Improve the concurrency of appending log messages in the monitor

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#4876]
When log messages arrive in the monitor they end up going to [RecentLogs.addEvent](
https://github.com/apache/accumulo/blob/38952c922648014e74e4e7a5704bfa256f390faa/server/monitor/src/main/java/org/apache/accumulo/monitor/util/logging/RecentLogs.java#L66).  This method is synchronized and has the potential to become a choke point because of the synchronization when lots of log messages are arriving.

**Describe the solution you'd like**

Remove the synchronized block and instead use a concurrent data structure like a Caffeine cache or concurrent map.

Suspect the complexity of this fix will be low, so put a 2.1 milestone to start with.  If that is not the case can change the milestone.

**Comment by dlmarion** [comment]
Other options might include:

 - a ring buffer, log4j2 asynchronous logging uses the LMAX Disruptor [RingBuffer](https://github.com/LMAX-Exchange/disruptor/blob/master/src/main/java/com/lmax/disruptor/RingBuffer.java#L84) (it's already a dependency I think).
 
 - a [LinkedTransferQueue](https://docs.oracle.com/en%2Fjava%2Fjavase%2F11%2Fdocs%2Fapi%2F%2F/java.base/java/util/concurrent/LinkedTransferQueue.html), but might have to check it's size before putting the object on it as it's unbounded.

**Comment by cshannon** [comment]
> * a ring buffer, log4j2 asynchronous logging uses the LMAX Disruptor [RingBuffer](https://github.com/LMAX-Exchange/disruptor/blob/master/src/main/java/com/lmax/disruptor/RingBuffer.java#L84) (it's already a dependency I think).

RingBuffer here is an interesting idea, but the main thing that I noticed looking at the code is that it uses a map specifically for deduplication. A key is generated so it avoids storing duplicates and I don't know that is possible for another data structure like RingBuffer but I haven't looked at it very closely.

**Comment by ben-manes** [comment]
Do you want it exact or can it be lossy (sampled)?

Caffeine uses ring buffers as a lightweight recording of events that are replayed under a tryLock. It’s lossy for reads (request sampling) as a skewed distribution means popular items reappear frequently enough to get deemed hot, even if some are lost. It’s a pretty common pattern, pubsub, where the ring buffer is just a fixed queue between multiple producers / single consumer so that you don’t throttle the producers.

If sampling is okay then just a tryLock to append an event is likely enough, and an exclusive lock for aggregate operations like clear() and sanitized().

**Comment by keith-turner** [comment]
The situation I was seeing that prompted me open this issue was that many  tservers were having lots of errors, those were being forwarded to the monitor.  The monitor would eventually die w/ OOME.  Some jstacks of the monitor showed close to 200 jetty threads stuck trying to get the lock for [this method](https://github.com/apache/accumulo/blob/38952c922648014e74e4e7a5704bfa256f390faa/server/monitor/src/main/java/org/apache/accumulo/monitor/util/logging/RecentLogs.java#L66) prior to OOME.   The hypothesis was that the tservers continued to send messages and those would be placed on a jetty thread pool queue until the monitor it ran out of memory.  Following that hypothesis I opened this issue to improve the concurrency.  Then opened #4877 to explore rate limiting with the assumption that solving this issue would increase the upper bound on what the monitor could process a second but there would still be an upper bound, so may still be nice to gracefully handle exceeding the upper bound.

**Comment by ctubbsii** [comment]
Just for context, the only reason we have concurrency on the incoming events is to handle deduplication/aggregation with count of repeated messages. We could just drop that feature. The user could then use their own deduplicating log4j filter for recently repeated messages, so the monitor doesn't have to. We could also show the last half hour of messages instead of a fixed number of unique messages. We could let the browser do the aggregation/counting from whatever messages we have.
