### ISSUE TITLE
Make `WorkFinder` and the `TransactionRunner`s critical to the Manager

### ISSUE THREAD

**Issue by kevinrr888** [apache/accumulo#4906]
**Is your feature request related to a problem? Please describe.**
When work on https://github.com/apache/accumulo/pull/4524/, noticed if the WorkFinder or any of the TransactionRunners die, the Manager will continue to run normally. These are necessary for the Manager to run normally, so the Manager should die if any of these die.

**Describe the solution you'd like**
WorkFinder and TransactionRunner should be made critical similar to how DeadReservationCleaner is critical to the Manager.

**Additional context**
https://github.com/apache/accumulo/pull/4524#discussion_r1631667416 was the discussion regarding this

**Comment by dlmarion** [comment]
The TransactionRunner runnables are added to a scheduled executor service. The TransactionRunner can die due to some Error or Exception, but the executor service is monitored and new TransactionRunner's are added as necessary. See:

https://github.com/apache/accumulo/blob/f52c0b4dd483fb1a4ff5029ab3efe4b7e8ce0f78/core/src/main/java/org/apache/accumulo/core/fate/Fate.java#L353-L377 .

The `WorkFinder` thread is created via the Threads class, which should be true of almost every server-side thread in the codebase. The Threads created via this class have an UncaughtExceptionHandler set on them that will terminate the VM. See https://github.com/apache/accumulo/blob/main/core/src/main/java/org/apache/accumulo/core/util/threads/AccumuloUncaughtExceptionHandler.java

**Comment by kevinrr888** [comment]
Ah okay thanks regarding the TransactionRunner. When I get around to this, I'll double check that new runners are created if needed, but the existing code looks good.
When I was checking this, when the WorkFinder died, the termination did not occur... I'll look at this again when I get around to it
