### ISSUE TITLE
Update formatter codestyle

### ISSUE THREAD

**Issue by milleruntime** [apache/accumulo#496]
We should update the settings in contrib/Eclipse-Accumulo-Codestyle.xml for Java 8 and where the line wrapping breaks.  At the very least we should use the google style guide: https://google.github.io/styleguide/javaguide.html

**Comment by alerman** [comment]
+1 the 100 character line wrap seems pretty low and ends up causing a lot of unused space in my IDE

**Comment by ctubbsii** [comment]
For reference, we used to have 160 char line lengths... which was way too long. I think 100-120 is relatively comfortable for me, personally, but Google style guide suggests 80 or 100. 100 was what I proposed. (Here's [the mailing list thread][1].)

[1]: https://lists.apache.org/thread.html/bcfcd3891c1586b36317e22200d7cce68cc50431453e2407dc3990cc@%3Cdev.accumulo.apache.org%3E

**Comment by alerman** [comment]
Should we just reuse the one from [here](https://github.com/google/styleguide/blob/gh-pages/eclipse-java-google-style.xml). Are there other settings you think should be different then googles?

Should we copy this in to our repo, or maybe just sub-tree it so we can get the updates?

**Comment by ctubbsii** [comment]
I can't remember, but I think the formatter plugin provides that one on the class path already, so we wouldn't even need to copy it in. It doesn't get updated often enough to bother with git subtree or anything like that. I would be happy to use it directly rather than even bother maintaining our own... but it might be worth doing a diff of the two just to make sure that it is what we'd want. I suspect there are some things we'd want to customize, even if it's only a few small tweaks.

**Comment by milleruntime** [comment]
@ctubbsii Since you are more familiar with Eclipse codestyle formatter, did you want to knock this one out for 2.0?

**Comment by ctubbsii** [comment]
I'm not that familiar with the new options for Java 8 and later. I'd have to look into it. This doesn't need to be a blocker, though. It's definitely not on my priority list.

**Comment by ctubbsii** [comment]
For now, I'm just going to import the old config into a newer Eclipse, and re-export it, with the new fields, with minimal tweaks. If we want to adopt GoogleStyle in future, that's fine, but for now, I think it's enough to just get the new lambda (and other new) options enshrined into the config file.
