### ISSUE TITLE
Queation about Scanner class for setting range in accumulo table info 

### ISSUE THREAD

**Issue by byungwok** [apache/accumulo#668]
![accumulo](https://user-images.githubusercontent.com/39606428/46346774-24c9fc80-c684-11e8-8525-61403418953f.PNG)

Hi i have qustion about java api for dealing with accumulo in java.

Look at above picture, i'd like to remove that data marked red. it's good to clear in accumulo CLI in accumulo centos7. using that natural character set. no encoding or change

but, in java api it is not scanned and deleted as "Scanner.setRange(Range.exact(row))" did not set range this charset. log said me null point exception. In my guess that's hex charset. so Does not that method '.setRange()' or 'Range.exact(row)'  read and found a special character such a unicode or Hex character? only can read String type? Or before input the row name, should be some encoding or handling to the other type like String?
if should i do that, How to do that don't you have some example for do that? the encoding

that shapefile data was inputted by geowave and i'd build that come based on Rowoperation.java in accumulo-example repo. 

I look forward to an answer ASAP so please flee free advice to me.

Thank you for your reading :)

**Comment by ctubbsii** [comment]
Hi @byungwok . I'm not sure I fully understand your question, but Accumulo manages lexicographical ordered arbitrary byte arrays. The APIs for String (or CharSequence) parameters are for convenience, and if a character encoding is not provided, it will assume UTF-8 (unless there's a bug that we've overlooked, and then it *may* assume whatever default encoding your local JVM is using).

If you need to scan/delete/insert something with non-printable (binary) characters, you should be able to provide the exact byte array, rather than use any String with a particular encoding.

For convenience, the shell attempts to identify characters which aren't printable and displays them in a hex-encoded format. However, it's not a perfect algorithm... it assumes non-printable, even if your console is capable of printing them, and it may be hard to distinguish between something like the bytes for the literal string `\x00` (a literal backslash, followed by a literal 'x', followed by two literal '0' characters) and the encoded form of a null (0) byte `\x00`. The shell has limitations like this, but you should be able to distinguish between these cases easily using the Java API directly.

**Comment by keith-turner** [comment]
@byungwok I suspect you may need to do something like the following for java

```java
Range.exact(new Text(new byte[] {(byte)0xab, (byte) 0xd2}));
```

**Comment by byungwok** [comment]
Thank you very much ctubbsii and keith-turner. i'll try thanx
