### ISSUE TITLE
Developr guide link in CONTRIBUTING.md is a dead link

### ISSUE THREAD

**Issue by jkosh44** [apache/accumulo#681]
Developer Guide link in CONTRIBUTING.md is https://accumulo.apache.org/contributor/source, which results in a 404. I believe it should probably be https://accumulo.apache.org/how-to-contribute/.

**Comment by ctubbsii** [comment]
Hi @jkosh44 ; I see you also created #682. Thank you for that. Please be aware that if you want a pull request to reference an issue, you can use the syntax `#681` instead of `Issue 681`. GitHub will automatically link if you use the former syntax, but it doesn't link if you use the latter.

Also, keep in mind that there is no reason to create an issue, and then immediately create a pull request. On GitHub, pull requests *are* issues, so that is redundant. Sometimes we create an issue to track future work, or one person creates an issue and then another person creates a pull request. But if you're creating both, only minutes apart, it's redundant.

**Comment by ctubbsii** [comment]
Fixed in PR #682

**Comment by jkosh44** [comment]
Thanks @ctubbsii, will keep that in mind for the future.
