### ISSUE TITLE
error geowave-accumulo.jar in CDH Accumulo module 

### ISSUE THREAD

**Issue by byungwok** [apache/accumulo#700]
![cdh](https://user-images.githubusercontent.com/39606428/47006112-26112400-d170-11e8-9603-146bc070e86b.PNG)

Nowadays i'm trying to set the CDH Accumulo for using geowave. 
just input a geowave jar file for accumulo in ext directory. However after that all accumulo module is down with that error log above. it can not read and accept the geowave jar file for accumulo avaliable.
In my guess, This logs looks like to relate with commons-vfs2-2.0.jar that CDH has. but not sure.
Something need a new jar file for CDH Accumulo?
as the geowave manual said,  i already konw that geowave can be also working with CDH. 
So i'd like to seek  advice for solving this problem.
I'm looking forward to the fastest possible response.

my System info is;
CDH version : Cloudera Express 5.15.1 (#3 built by jenkins on 20180731-0834 git: 6e046fd999fd99e7e12299386ba69b23afa43c60) 
Java version : 1.8.0_181
Accumulo version :  1.7.2-cdh5.5.0

Please let me know advice ASAP

Thank you for your reading

**Comment by ctubbsii** [comment]
Hi @byungwok . This does not appear to be an Accumulo issue. It may be related to Cloudera CDH or Geowave, but this is not the right forum to get support for either of those (I suspect both of those have their own community forums for support, but I don't know what they are). Also, please note that Accumulo 1.7.x is not an actively maintained version of Accumulo. You should probably upgrade to the latest, 1.9.2, unless you are receiving support for the earlier version from your vendor.

From the exception, it looks like either 1) the jar file is corrupt, 2) you don't have the appropriate unzip library installed on your system to unpack the jar, or 3) the file system permissions to do not permit your accumulo process to read the jar. It's also possible that the issue was fixed in commons-vfs2-2.1, which I know has some bug fixes in it, and you may be able to put on your class path in place of commons-vfs2-2.0, but I can't be certain it will fix this specific issue.

Hopefully the above suggestions will help. However, I'm closing this issue, since it does not appear to be a problem with Accumulo.
