### ISSUE TITLE
Accumulo 2.0.0 and  hadoop 2.8.1

### ISSUE THREAD

**Issue by SebeiHiba** [apache/accumulo#709]
Hi,
Does accumulo 2.0.0 require the use of hadoop3.x or can I use hadoop 2.8.1?

regards

**Comment by ctubbsii** [comment]
@SebeiHiba Accumulo 2.x is built against Hadoop 3, and is intended to work against that version. It may be possible to run it against older versions of Hadoop, and doing so may require patching Accumulo or altering its classpath at runtime, but since it was not developed against Hadoop 3, the only way to know is to try. Personally, I would recommend upgrading Hadoop before using Accumulo 2.x instead of trying to force Accumulo 2.x to run on older Hadoop versions.

For what it's worth, Accumulo 1.9 is built to work against either Hadoop 2 or Hadoop 3, and should only require class path changes at runtime.
