### ISSUE TITLE
How to move Accumulo table data to HDFS which has different structure 

### ISSUE THREAD

**Issue by byungwok** [apache/accumulo#742]
Hi 
First of all Thank you for your last answer. i'd check that is working well. very big thanks.

This question is about export&import accumulo table data from one hdfs to the other hdfs which has different Ip, port and directory structure. 
I already follow this document about export/import (https://accumulo.apache.org/1.7/examples/export) However this paper assumes the same device and Hadoop hdfs. Of cause, i know that how to copy hdfs to hdfs using 'distcp' and hdfs url.  But Unfortunately, For security  the end hdfs is isolated and has different ip and dir structure. So i'd carry the data like this 'hdfs -> local -> hdfs' yah it looks so silly and very Inefficient. but it's the best so far in my knowlege.  

So i think may re-write 'distcp.txt' and the other files has accumulo table data to fit with the 'end hdfs' url structure at local. I'm not sure is it correct because i already fail. So in this case, should i change the ip and url in all files; distcp.txt, *_info.txt, *.bin, and  table_config.txt? Did you have some the other best way to move to this easier?
Please let me know how to do that

Thank you for reading and good day :)

**Comment by keith-turner** [comment]
The following may work, have not tested it

Copy to local

```bash
hadoop fs -cat /tmp/table1_export/distcp.txt | xargs -I XX hadoop fs -cp XX file:///local/dir
```

copy from local to hdfs


```bash
hadoop fs -cp file:///local/dir hdfs://dest/dir
```

**Comment by byungwok** [comment]
thank you i'll try but well..it may look like the same function that 'hdfs dfs -put&-get' anyway i'll try

**Comment by byungwok** [comment]
![hdfs](https://user-images.githubusercontent.com/39606428/47899063-b1521f80-debb-11e8-9c64-0a79df8fdd33.PNG)
![hdfstolocal](https://user-images.githubusercontent.com/39606428/47899064-b1521f80-debb-11e8-9ad1-dd49f03b257d.PNG)

yap i tested what u comment me both. it takes all *.rf files related with Accumulo table in hdfs. then can go from local to hdfs Thanks

So what about 'distcp.txt' files? should i change the hdfs url info to destination hdfs ip:port manually? i think it's main to re-create accumulo table in the end hdfs. how should i handle it?

**Comment by keith-turner** [comment]
> So what about 'distcp.txt' files? should i change the hdfs url info to destination hdfs ip:port manually? i think it's main to re-create accumulo table in the end hdfs. how should i handle it?

`distcp.txt` is not needed for import.  For import you just need all files listed in `distcp.txt` in a single directory in HDFS.  `distcp.txt` is just created to help copy all of the files needed to one dir.

**Comment by byungwok** [comment]
thank you 
got it so in short, I don't need to handle any hdfs url in accumulo export files manually right? it sounds like that

**Comment by EdColeman** [comment]
I believe that you are correct. In the Accumulo example, the use of distcp is because that is the most common way of transferring the files between clusters.  How ever you get the files to the destination system is really up to you.  If you can get the files listed in discp.txt and the exportMetadata.zip file into a single directory on the destination system, the import command does not care how they got there, and you should be good to go.

The Accumulo bulk import command takes a table name and the hdfs directory on the destination system, the only hdfs url needed is the url / path to the directory with the files. 

> importtable table_name hdfs_path_to_files

The import uses the exportMetadata.zip file to recreate the table metadata and settings (including the splits) and then moves the rfiles in the provided directory into / under the Accumulo directory structure (i.e. xxx/accumulo/tables/new_table_id/...rf)

The paths in the distcp.txt file are a convenience for using the distcp command -f option  (see https://hadoop.apache.org/docs/current/hadoop-distcp/DistCp.html):

> bash$ hadoop distcp -f hdfs://nn1:8020/distcp.txt hdfs://nn2:8020/bar/foo

distcp uses the paths listed in the provided file (distcp.txt in this case) and copies them to the foo directory on the destination system.  The results of distcp on the destination system are a single directory, with the Accumulo rfiles and the exportMetadata.zip file. 

The alternate form of the distcp command takes a file list and the destination system directory, so you could do something like:

> disctp hdfs:nn1/accumulo/tables/yy/Axxxx1.rf hdfs:nn1/acumulo/tables/yy/Axxxxx2.rf hdfs:nn1/path_to_exportMetadata.zip  hdfs:nn2/foo/bar  

Passing all of the paths from distcp.txt, including the exportMetadata.zip file to distcp, the result would be the same - a single directory on the destination system with the Accumulo rfiles and the exportMetadata.zip file, its just much easier in this case to give it the files with -f.

You don't need to use distcp, you just need to end up with the same, expected directory and all of the files. Hope this helps.

**Comment by byungwok** [comment]
Thank you for your comment 'EdColeman' I'll try all

**Comment by byungwok** [comment]
![default](https://user-images.githubusercontent.com/39606428/47980989-63345a80-e10d-11e8-8a28-9acba8655164.PNG)

Thank you for all answers. when i tried to import data in accumulo, it said 'ERROR: org.apache.accumulo.core.client.AccumuloException: Incompatible data version 1'. Does it means to has different version between depart hadoop and dest hadoop or accumulo?  FYI i'm testing this between Apache accumulo 1.8.1 and accumulo 1.7.2-cdh5.5.0. does it make this msg? then for fixing it up, what should i do?  touching version and the other src info in 'accumulo_export_info.txt', exportMetadata.zip?

**Comment by keith-turner** [comment]
> Does it means to has different version between depart hadoop and dest hadoop or accumulo?
This is an Accumulo error.  Serialization of RFiles changes between 1.7 and 1.8, so can not export from 1.8 and import to 1.7.

**Comment by byungwok** [comment]
got it Thanks

**Comment by ctubbsii** [comment]
Closing inactive question.
