### ISSUE TITLE
Shorten method names in AccumuloClient builder

### ISSUE THREAD

**Issue by mikewalch** [apache/accumulo#747]
[AccumuloClient](https://github.com/apache/accumulo/blob/master/core/src/main/java/org/apache/accumulo/core/client/AccumuloClient.java) has long method names for its builder that could be shortened before 2.0 is released.

Below are examples of this proposed shortening:

```java
// current
Accumulo.newClient().forInstance("myinstance", "zookeeper1,zookeeper2")
      .usingPassword("myuser", "mypassword").build();
// proposed
Accumulo.newClient().instance("myinstance", "zookeeper1,zookeeper2")
      .user("myuser", "mypassword").build();



// current
Accumulo.newClient().usingClientInfo(clientInfo)
     .usingToken("user, new PasswordToken("pass")).build();
// proposed
Accumulo.newClient().from(clientInfo).user("user", new PasswordToken("pass")).build();
```

Below is a chart of the proposed method names for the [AccumuloClient](https://github.com/apache/accumulo/blob/master/core/src/main/java/org/apache/accumulo/core/client/AccumuloClient.java) builder. Naming is subjective so I am open to no change or different names. Feel free to comment on this issue:

| Current Method Name | Proposed Method Name |
|--------------------------|-------------------------------|
|  forInstance(String name, String zk) | instance(String name, String zk) |
| usingProperties(String propsFilePath) | from(String propsFilePath) |
| usingProperties(Properties properties) | from(Properties props) |
| usingClientInfo(ClientInfo info) | from(ClientInfo info) |
| usingPassword(String username, CharSequence password) | user(String username, CharSequence password) |
| usingKerberos(String principal, String keytabFile) | kerberosUser(String principal, String keytabPath) |
| usingToken(String principal, AuthenticationToken token) | user(String principal, AuthenticationToken token) |
| withTruststore | truststore |
| withKeystore | keystore |
| withJsse | jsse |
| withPrimary | primary |
| withQop | qop |
| withSsl | ssl |
| withSasl | sasl |
| withBatchWriterConfig | batchWriterConfig |
| withBatchScannerQueryThreads | batchScannerQueryThreads |
| withScannerBatchSize | scannerBatchSize |

**Comment by ctubbsii** [comment]
I'd like to see the authentication options split up a bit to avoid the `(String, String)` (or `CharSequence` variants) parameter ambiguity and the redundancy in the user principal. Something like:

```java
  // one of these two
  .user(CharSequence principal)
  .as(CharSequence principal)
    // followed by one of these three
    .token(AuthenticationToken token)
    .password(CharSequence password)
    .keytab(Path keytab)
```

I'd also like to see fewer `String` arguments when `Path` or `File` make more sense. For example,

```java
  .from(Path propertiesFilePath)
```

and in the `instance`. However, I'm uncertain what to do for instance. I think `instance` could refer to the instance name as a "cluster id" or similar. Maybe something like:

```java
  Accumulo.newClient().toCluster(CharSequence name).registeredAt(CharSequence... host);
```

Names for the client endpoint are hard. Maybe the term "endpoint" could be worked in to the method name instead? I'm not sure.

I lean towards keeping the `with` prefixes. Those keep it the API closer to natural human language (maps to prepositional phrases), which is important for fluent APIs, and I think it would be inconsistent to drop those, but leave the `from` prepositional phrases.

**Comment by mikewalch** [comment]
Below is my second proposal incorporating a lot of @ctubbsii suggestions with some differences:

* Kept instance name & zookeeper together in the same method as they are always both needed.
* I like the prepositional phrases early but I don't think they are required later in the builder.
* I renamed `forInstance` to `to` but maybe `toCluster` or even the original `forInstance` is better.

```java
// current
Accumulo.newClient().forInstance("myinstance", "zookeeper1,zookeeper2")
      .usingPassword("myuser", "mypassword").build();
// proposed
Accumulo.newClient().to("myinstance", "zookeeper1,zookeeper2")
      .as("myuser").password("mypassword").build();

// current
Accumulo.newClient().usingClientInfo(clientInfo)
     .usingToken("user, new PasswordToken("pass")).build();
// proposed
Accumulo.newClient().from(clientInfo).as("user").token(new PasswordToken("pass")).build();
```

| Current Method Name | Proposed Method Name |
|--------------------------|-------------------------------|
| forInstance(String name, String zk) | to(CharSequence instanceName, CharSequence zookeepers) |
| usingProperties(String propsFilePath) | from(Path propsFile) |
| usingProperties(Properties properties) | from(Properties props) |
| usingClientInfo(ClientInfo info) | from(ClientInfo info) |
| doesn't exist | as(CharSequence principal) |
| usingPassword(String username, CharSequence password) | as(user).password(CharSequence password) |
| usingKerberos(String principal, String keytabFile) | as(user).kerberos(Path keytab) |
| usingToken(String principal, AuthenticationToken token) | as(user).token(AuthenticationToken token) |
| withTruststore | truststore |
| withKeystore | keystore |
| withJsse | jsse |
| withPrimary | primary |
| withQop | qop |
| withSsl | ssl |
| withSasl | sasl |
| withBatchWriterConfig | batchWriterConfig |
| withBatchScannerQueryThreads | batchScannerQueryThreads |
| withScannerBatchSize | scannerBatchSize |

**Comment by keith-turner** [comment]
I am not a fan of all of the `with` prefix names. If all optional paths have it then I think it adds noise with no value.

I have mixed feeling about `from(Path)` vs `from(String)` because I think 99% of code will be `from(Paths.get(filePath))`.

**Comment by mikewalch** [comment]
Below is my third proposal incorporating input from @keith-turner with some changes:

* Combined `as` with `password`, `kerberos`, & `token` methods as they always used together. I don't think we'll need more `as` methods given that `as(principal, Authentication token)` is pretty future proof. 

```java
// current
Accumulo.newClient().forInstance("myinstance", "zoo1,zoo2")
      .usingPassword("user", "password").build();
// proposed
Accumulo.newClient().to("myinstance", "zoo1,zoo2").as("user", "password").build();

// current
Accumulo.newClient().usingClientInfo(clientInfo)
     .usingToken("user, new PasswordToken("pass")).build();
// proposed
Accumulo.newClient().from(clientInfo).as("user", new PasswordToken("pass")).build();
```

| Current Method Name | Proposed Method Name |
|--------------------------|-------------------------------|
| forInstance(String name, String zk) | to(CharSequence instanceName, CharSequence zookeepers) |
| usingProperties(String propsFilePath) | from(String propsFilePath) |
| usingProperties(Properties properties) | from(Properties props) |
| usingClientInfo(ClientInfo info) | from(ClientInfo info) |
| usingPassword(String username, CharSequence password) | as(CharSequence user, CharSequence password) |
| usingKerberos(String principal, String keytabFile) | as(CharSequence principal, Path kerberosKeytab) |
| usingToken(String principal, AuthenticationToken token) | as(CharSequence principal, AuthenticationToken token) |
| withTruststore | truststore |
| withKeystore | keystore |
| withJsse | jsse |
| withPrimary | primary |
| withQop | qop |
| withSsl | ssl |
| withSasl | sasl |
| withBatchWriterConfig | batchWriterConfig |
| withBatchScannerQueryThreads | batchScannerQueryThreads |
| withScannerBatchSize | scannerBatchSize |

**Comment by ctubbsii** [comment]
@mikewalch I like the `to(name)`, because we're connecting *to* an Accumulo instance with that name, but the second parameter could be misleading with that name (we're not constructing a client *to* those hosts; they just serve as an endpoint), and I'm not a fan of two string types like that... it's very easy to accidentally swap them (common problem and why we made the shell have explicit separate args, `zi` and `zh` to replace `zk`). Maybe we should do:

```java
  to(CharSequence name, CharSequence[] zookeepers);
```

With the array type, and using Java 8 syntax, we can call it like:

```java
  Accumulo.newClient().to(name, {"localhost:2181"}); // OR
  Accumulo.newClient().to(name, {zk1, zk2});
```

This is a bit more explicit about the ZKs, and less ambiguous in the params.

Also, the more I think about it, the more strongly I think that `from(String propsFilePath)` should be `from(Path propsFilePath)`, especially for consistency with the other place (keytab) where you use `Path` type. I don't think this will bloat user code too much... it's (at the most) once per client... and if a variable is used, it doesn't even matter:

```java
  Path propsFile = Paths.get(args[0]);
  Accumulo.newClient().from(propsFile);
```

Also, the "jsse" method is confusing. That should just be a boolean that says "use JSSE system props". Maybe "useJsse" makes more sense than just "jsse". I think some of the others have similarly bad semantics when removing "with". They just don't read as well, or make as much intuitive sense.

**Comment by keith-turner** [comment]
One reason to not use `from(String)` now is that we may want to leave it available for future use.  I have always though it would be nice if Accumulo had a standardized connection string that could encode instance, zookeepers, and credentials.  It may be nice to have `from(String connectionString)` in the future. 

> Some boilerplate is reasonable, when it helps clearly communicate the required type

I realized that for communication, the variable name used in the API is much more important than the type.  If I see `from(Path foo)` I would still need to consult javadoc.  However if I see `from(Path clientPropsFile)` or `from(String clientPropsFile)` then I may not need javadoc.  

> Maybe "useJsse" makes more sense than just "jsse".

We need to strike that balance between adding useless noise and useful information. I think this ends up being a function of the number of unique prefixes and the number of methods similar to TFIDF. Also, we may be ok making the less frequently used methods longer and therefore more self documenting. For this case `enable` may be a better prefix for communicating useful info.   I am really happy to see this proposal shorten the most frequently used methods.  

Seems like the following could lead to boilerplate code because every user has to split/parse this.  The zookeeper API just takes String for this.

```java
to(CharSequence name, CharSequence[] zookeepers);
```

**Comment by ctubbsii** [comment]
> I don't think a user would ever write code like the following because they would usually not know the number of zookeepers at compile time.
> 
> ```java
>  Accumulo.newClient().to(name, {zk1, zk2});
> ```

Okay, sure, but accepting an array doesn't require them to... that was just one example of calling the proposed method. I'd expect them to supply the array from whatever data structure they have. I would not necessarily expect them to collapse their data structure into our specific, comma-separated "stringly-typed" field in our Java API (in our config in serialized form, yes, but not in our programmatic API). Other examples of calling this method with the array type:

```java
  Accumulo.newClient().to(name, zkString.split(";")); // OR
  Accumulo.newClient().to(name, zkGson.fromJson(jsonLine, String[].class)); // OR
  Accumulo.newClient().to(name, zkList.toArray());
```

If the array parameter type isn't a good idea, can anybody else suggest an alternative solution to avoid the `(String, String)` parameter ordering ambiguity? Or, since I think this is also a problem, can anybody suggest a clean way to decouple the params from each other? The fact that cluster instance name and ZKs are coupled is an implementation detail that need not be exposed in the API... or at least, if it is exposed, it should be more clear their relationship. For example, it should be more clear that the name is the registration name, and that ZKs is the registration service, as in `.registeredAs(name, zks)`, or maybe just `.zk(name, zks)` (with good API docs explaining the use of ZK as a registration service). Or, maybe they should be decoupled in a way that also avoids the parameter ambiguity? As in: `.to(name).at(zks)`?

**Comment by ctubbsii** [comment]
If we had a well-defined syntax for a "connectionString", it would be much simpler: `.to(connectionString)`. Maybe `accumulo://name@host1:port1,host2:port2,host3,host4:port4`.

**Comment by ctubbsii** [comment]
I'm willing to overlook my concerns about getting that ZK connection API "just right" if we reserve a clean API for passing in a connection string (can be done in future work). As long as we keep that in mind as future work and don't create anything that would conflict with it, I'm probably okay with whatever others decide here.

**Comment by mikewalch** [comment]
I really like `.to(connectionString)`.  I am going to create a pull request for this issue. I think there is enough consensus. The remaining questions can be resolved during review of the pull request.
