### ISSUE TITLE
Improve new MapReduce API

### ISSUE THREAD

**Issue by milleruntime** [apache/accumulo#753]
Follow on work for #743.  Improve the new API further by combining the builder fluent API into the one static method.  This would make it so the user only has to perform one step.

**Comment by milleruntime** [comment]
@ctubbsii @keith-turner What do you think of this for the API?
<pre>
AccumuloInputFormat.configure(job).clientInfo(clientInfo).table("test").scanAuths(Authorizations.EMPTY)
            .addIterator(is).done();
</pre>

**Comment by keith-turner** [comment]
Passing the job in at the end of the fluent chain allows for sanity checks to be done all at once.  It also makes it very clear when the job is mutated.  Could do something like the following.

```java
AccumuloInputFormat.settings().clientInfo(clientInfo).table("test").scanAuths(Authorizations.EMPTY)
            .addIterator(is).configure(job);
```

**Comment by milleruntime** [comment]
Another thing to take into consideration is allowing multi table options for completing #749

**Comment by milleruntime** [comment]
I was planning on performing the serialization of all the options into the configuration on the last method.  So we could do something like:

```java
AccumuloInputFormat.configure().clientInfo(clientInfo).table("test").scanAuths(Authorizations.EMPTY)
            .addIterator(is).serialize(job);
```

**Comment by ctubbsii** [comment]
How about `.configure(). ... .store(job)` instead of serialize? How would we incorporate multiple tables into this? I'm kinda thinking maybe have a `.table` hanging off of each method after the first `.table`, and implement it so you can configure one table, then the next, then the next, etc. Methods chained after one `.table` call, and before the next `.table` affect only the one that precedes it. So,

```java
AccumuloInputFormat.configure().clientInfo(clientInfo)
  .table("table1").scanAuths(Authorizations.EMPTY).addIterator(is1)
  .table("table2").ranges(ranges).scanAuths(auths).addIterator(is2).addIterator(is3)
  .table("table3")
  .store(job);
```

In the above, table1 is fully scanned with no auths and one iterator, while table2 is only scanned over specific ranges and with custom auths and two iterators, and the third table is fully scanned with all the default behavior.

Internally, we just edit the most recent internal data structure for a table, and add it to a list of all the tables when we encounter the next `.table` or a terminating `.store`. For keeping the table configs separate, we internally track a 1-up counter for each table.

**Comment by milleruntime** [comment]
I like ```configure()... store(job)``` It is shorter and makes more sense than `build()` or `done()`.

I was thinking something similar for mutli tables.  I was going to base the table options off of the previously used object `InputTableConfig`.  The only option I wasn't sure about was `scanAuths()`. It is not clear whether they are set at the table level or the same auths were used for all scans, since they aren't a part of `InputTableConfig`.  I just wanted to make sure the API will still work in a loop for users who have many tables.

**Comment by milleruntime** [comment]
> It is not clear whether they are set at the table level or the same auths were used for all scans, since they aren't a part of InputTableConfig

Looking at the implementation it appears that we currently use one set of Auths for the whole job.  While I don't see why we couldn't set Auths per table, it would be more work.

**Comment by ctubbsii** [comment]
Per-table makes more sense for me, for scan auths (and all other scan options).
