### ISSUE TITLE
Cdh Accumulo is broken How to fix up?

### ISSUE THREAD

**Issue by byungwok** [apache/accumulo#760]
well......finally cdh accumulo is gone.....it is not working normally. Help me for fixing up

This is two symptoms;
First, not working table operation. it is looping infinitely to write logs '[tableOps.Utils] INFO : namespace 2 (242d0adce6beb4bd) locked for read operation' in master log. because of this operation, it's not working any other command in accumulo shell. and than it said '[impl.ThriftTransportPool] INFO : Thread "shell" no longer stuck on IO to testmaster01:10010 (0) sawError = true' or 'Internal error processing waitForFateOperation' when i command. Maybe i guess this error looks like looking for already deleted '*rf' files in HDFS for operation. I'm very wondering that how to kill or stop that accumulo threads.

this is shot for this question;
![fuck](https://user-images.githubusercontent.com/39606428/48259678-0c57b980-e45c-11e8-992e-4143e2e6d2d1.PNG)
![not work](https://user-images.githubusercontent.com/39606428/48259729-3315f000-e45c-11e8-8085-c178e6d9758f.PNG)
![default](https://user-images.githubusercontent.com/39606428/48259732-37420d80-e45c-11e8-91b4-e5e2285214dd.PNG)
![default](https://user-images.githubusercontent.com/39606428/48259736-3a3cfe00-e45c-11e8-8d86-94315ab03ab1.PNG)

Second, no instance name. In the process of fixing the preceding error, this accumulo lost its instance name. i give to him the instance name through my Cloudera manger to accumulo. but instance name in shell info and monior said 'null' or 'Unavailable'.  Unfortunately, intilization does not choose because of stupid cloudera permission problem and new instance id which fool CDH accumulo can not create. i'm wondering how to give the instance name on alive accumulo without using cdh manger.

this is shot
![default](https://user-images.githubusercontent.com/39606428/48260724-da485680-e45f-11e8-8f1f-f3fdc457b23a.PNG)
->i already gave and set instance name at CDH manger. but...

![info](https://user-images.githubusercontent.com/39606428/48260748-fe0b9c80-e45f-11e8-8f98-760549e5da49.PNG)
-> info in accumulo shell said it's null......

Please let me know how to fix it up asap. i need big help. i did re-install the cdh accumulo but The situation got even worse. so please help me....

**Comment by EdColeman** [comment]
Check zookeeper - see http://accumulo.apache.org/1.9/accumulo_user_manual.html#_zookeeper

You need to be able to see the instance, try: 

./bin/accumulo org.apache.accumulo.server.util.ListInstances

Did you overwrite the accumulo config on the reinstall?

As a last resort) you may need to follow http://accumulo.apache.org/1.9/accumulo_user_manual.html#zookeeper_failure if your instance is not in zookeeper and if the rfiles still exist in hdfs.

Once you have you instance in zookeeper, you can kill fate transactions using fate fail command - see http://accumulo.apache.org/1.9/accumulo_user_manual.html#_administration

You will need to stop the masters so that the shell can get the master lock - using fate fail is not normal and you need to proceed with caution.

If you have corrupted the system metadata, http://accumulo.apache.org/1.9/accumulo_user_manual.html#_advanced_system_recovery provides some things you could also try.
