### ISSUE TITLE
NoClassDefFound for an iterator that is on the classpath

### ISSUE THREAD

**Issue by adamjshook** [apache/accumulo#764]
We've been experiencing an issue recently where a customer iterator class appears to be unloaded (or otherwise unreachable) by a TabletServer.  We need to restart the TabletServer when this issue appears and it clears up the issue.  Version 1.9.2.  I'll add that the JAR files in question are stored on HDFS and set via `general.vfs.classpaths`.

**Comment by keith-turner** [comment]
Do you know if this is related to #728?

**Comment by adamjshook** [comment]
Could very well be.  I'll revert to 2.1 in our fork and see if the issue goes away.

**Comment by adamjshook** [comment]
We've reverted to `commons-vfs2` to 2.1 and it is still popping up from time to time.  We're going to move our custom iterators out of the VFS classpath and see what happens.

**Comment by ctubbsii** [comment]
This sounds like a VFS-specific issue. While it affects Accumulo users using VFS, I'm not sure we can really address it in any meaningful way. It seems like it needs to be fixed in VFS itself. VFS 2.3 is now available. That may work better. I'm not sure.

I think we should close this for now, because I don't think we can do anything in Accumulo to address this. If there's something we can do in Accumulo to address this, we can re-open.
