### ISSUE TITLE
Bulk import process can result in a lost file

### ISSUE THREAD

**Issue by ivakegg** [apache/accumulo#800]
In the 1.8, 1.9 line of code (unsure about 2.0), we can get into a situation where a major compaction starts failing because of a missing file.  The scenario is as follows:

master asked to import directory
tserver1 asked the assign a file
tserver1 askes tserver2 to load a file
tserver2 loads the file successfully but not not respond to tserver1 in a timely manor
tserver2 major compacts and adds a ~del entry for the file
tserver1 times out and retries asking tserver2 to load the file
tserver2 starts to load the same file a second time
garbage collector deletes the file
tserver2 attempts to major compact the file away but now it does not exist.

**Comment by keith-turner** [comment]
There are mechanism in Accumulo that are supposed to prevent this.  Not sure where those are falling down.  I am going to create an IT that attempts to reproduce this.  I plan to do this by making the IT directly call the RPC to load a file.  If that does not yield anything then I will review the code paths for preventing multiple loads.

**Comment by keith-turner** [comment]
Looking at the code I found a potential problem.  Each bulk import has a unique fate transaction id stored in zookeeper.  There is code that prevents RPCs related to the bulk import from running if the fate transaction id is deleted from ZK. Also there is code to wait for all active RPCs to finish.  So the bulk import FATE op will delete the id from ZK and then wait for all tservers to complete any RPCs that were active before it was deleted.

The bulk import FATE op makes RPCs to intermediate tserver that inspect files.  Once the intermediate tserver determines where a file goes then makes an RPC to tserver that should load the file.  The problem is that only the intermediate RPC is checking the if the transaction id is active.  Really the final RPC should be doing this check.

Below are some places in the code where this is all happening.

 * [CompleteBulkImport line 42](https://github.com/apache/accumulo/blob/rel/1.9.2/server/master/src/main/java/org/apache/accumulo/master/tableOps/CompleteBulkImport.java#L42) deletes the transaction id from ZK
 * [CopyFailed line line 75](https://github.com/apache/accumulo/blob/rel/1.9.2/server/master/src/main/java/org/apache/accumulo/master/tableOps/CopyFailed.java#L75) waits for active RPCs to complete
* [ClientServiceHandler line 345](https://github.com/apache/accumulo/blob/rel/1.9.2/server/base/src/main/java/org/apache/accumulo/server/client/ClientServiceHandler.java#L345) Runs the intermediate RPC to inspect files.  This RPC is run using TransactionWatcher.  TransactionWatcher will not run the RPC if the id does not exist in ZK.  If it does exist then increments a counter for the number of RPCs running for that transaction.
 * [TabletServer line 463](https://github.com/apache/accumulo/blob/rel/1.9.2/server/tserver/src/main/java/org/apache/accumulo/tserver/TabletServer.java#L463)  This the RPC that actually loads a file into a tablet.  This RPC is not run using TransactionWatcher and I think it should.

I think the intermediate RPC should stop using TransactionWatcher and the final RPC should start using TransactionWatcher.  I don't think there is a benefit to the intermediate one using it and it puts more load on ZK.

**Comment by keith-turner** [comment]
Also I have been working on IT that sends a load message to a tablet, compacts the tablet, and then sends another load message.  This IT shows that the current code that tracks loads prevents a load after compact.
