### ISSUE TITLE
Failing to recover WAL leases

### ISSUE THREAD

**Issue by ivakegg** [apache/accumulo#802]
In 1.8 and 1.9 we are having issues when a tserver dies hard, and the master needs to recover the leases (LeaseException).  With hadoop 2.6.0, we get into a state where the lease cannot be recovered within a resonable amount of time (minutes as opposed to hours).  In order to get out of this state, we have to manually copy the WAL having the issue out of the way, and then move the copy into the original file's place.  We had verified when we came up with this procedure that the copy appears to contain all of the data.
I am suggesting that we add a little more to the lease recovery such that after a configured amount of time, if we cannot communicate with the tserver and the zookeeper lock does not exist, then force the lease recover (copy the file if needed).  This would allow the system to continue operations without having to intervene every time.

**Comment by ctubbsii** [comment]
I've seen this copy-into-place to fix stuck Hadoop before. IIRC, it happened before 2.6 also. This seems like a Hadoop bug. Maybe we can add complexity to Hadoop to fix it, but I'd hope that the fix can be pushed upstream into Hadoop, so we don't set a precedent of Accumulo taking responsibility for bugs in libraries Accumulo uses.

I'm sympathetic to the need to have this fixed in production, and don't inherently have a problem with Accumulo doing more stuff to be fault-tolerant... I'm just worried slightly that the increasing complexity in Accumulo is not a scalable solution this category of problem. Without seeing the code needed to fix this, it's hard to say whether it would be complex or simple in this case.

Regardless, I definitely think this should be brought to the attention of Hadoop (or whatever Hadoop vendor you're using).

**Comment by ivakegg** [comment]
Ok, that is a fair point.  Since the LogCloser is actually pluggable, we can write separate one that will do what we need until we can get the appropriate hadoop bugs fixed/installed on our system.  This has been brought to the attention of Hadoop and I believe most of the bugs in this area have been fixed and are destined for later versions of hadoop.  Closing this ticket.

**Comment by ctubbsii** [comment]
It would be interesting to see if this bug still affects 2.0-alpha-1 with Hadoop 3.

We don't necessarily need to close this issue. My intent was not to discourage a potential contribution, but merely to review the idea, in the absence of code, and express a modicum of caution.
