### ISSUE TITLE
Replace MiniAccumulo LogWriter's with ProcessBuilder.redirectOutput()

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#810]
When MiniAccumulo was written Java did not offer a way to redirect stderr and stdout for a process.  Since Java 1.7 it has been possible to do this.   The custom LogWriter code/threads could be removed from MiniAccumulo and replaced with ProcessBuilder.redirectOutput() and ProcessBuilder.redirectError()

**Comment by keith-turner** [comment]
This is the code I am thinking of https://github.com/apache/accumulo/blob/5c6e0c3c491787b9269032bf9cae76f7dc01adc1/minicluster/src/main/java/org/apache/accumulo/miniclusterImpl/MiniAccumuloClusterImpl.java#L339

**Comment by jzgithub1** [comment]
jzeiberg - I will be working on this issue.

**Comment by ctubbsii** [comment]
Which is your user? @jzgithub1  or @jzeiberg?

**Comment by jzgithub1** [comment]
I am both.    I want to use jzeiberg but I posted the other day as
jzgithub1.  I am a little confused how I got two names.

Jeffrey

**Comment by jzgithub1** [comment]
jzeiberg is my organization and jzgithub1 is my user.  I have to figure out
how to change my user name.

**Comment by jzgithub1** [comment]
jzgithub1 is my user and jzeiberg is my project.

**Comment by ctubbsii** [comment]
Ah, that makes sense. I wonder if you can convert the organization account back to a regular user if you wanted to? Doesn't matter to me, though. I was just curious. :smiley_cat:

Also, although you can comment on the GitHub thread by replying to the email notifications as you've been doing, it's not necessarily the best practice, since it adds a lot of extra noise to the thread, especially if you include the original notification message quoted in your reply. I would use that reply-to-post feature sparingly and instead click on the "view it on GitHub" link and reply on the page directly.
