### ISSUE TITLE
Tserver log names do not include port number

### ISSUE THREAD

**Issue by alerman** [apache/accumulo#831]
This causes an issue when running 2 tservers on a host. The monitor differentiates by port number, but the log files just use a numeric (1,2) to differentiate. This makes tracking down which log is for which tserver difficult as the lower port number does not necessarily mean the lower log number.

**Comment by milleruntime** [comment]
What version are you seeing this?

**Comment by alerman** [comment]
1.8.1 and 1.9.2

**Comment by ctubbsii** [comment]
I understand the inconvenience, but I'm not sure this is a problem. The file names for logging are under the user's control in the log4j configuration files. The hostname and port combination, on the other hand, is Accumulo's own internal registration information, when the tservers do service advertisement in ZooKeeper. They are separate things.

Because Accumulo tserver processes are going to start emitting logs right away, it's not even possible for the service itself to know what its port number is going to be (if you are using the automatic port assignment) before the log is emitted. If you really want the log file names to reflect the port number, it would be best to configure static port numbers in each tserver's configuration file and in their respective log4j configuration files.

**Comment by ctubbsii** [comment]
Removed the 1.9.3 label (I think labeling it is premature, at this point, since it's not clear when/whether it will be solved).

One way this could be addressed is that we could have a separate logger, which emits the tserver's configuration once fully initialized (similarly to how auditing goes to a separate logger), which includes the port number and other initialization details. Users could configure this logger to go to a separate file in their log4j configuration... so that it doesn't roll over and/or get lost, and should have enough information to help the user correlate the logs by file name.

**Comment by ctubbsii** [comment]
Closing for reasons previously discussed.
