### ISSUE TITLE
Simplify 'accumulo classpath' command

### ISSUE THREAD

**Issue by mikewalch** [apache/accumulo#885]
The current implementation is written in Java and outputs `general.classpath` settings.  It could be simplified to just echo CLASSPATH variable.

**Comment by ctubbsii** [comment]
This is good, because in Java 11, you can't enumerate the runtime class path from the system class loader, because it can't be cast to a URLClassLoader, and all the methods and types to enumerate its runtime settings are private and/or buried in the `java.base` module, which doesn't export the system class loader type's package. So, the best we can get for that is to just look at what the value of `System.getProperty("java.class.path")` or, even simpler, just `echo "$CLASSPATH"` in the script.
