### ISSUE TITLE
Log if general.classpaths or general.dynamic.classpaths is set

### ISSUE THREAD

**Issue by mikewalch** [apache/accumulo#886]
This is needed when #885 is completed.  Accumulo should log (probably at the INFO level) if an application is started and `general.classpaths` or `general.dynamic.classpaths` is set.

**Comment by jzgithub1** [comment]
I will work on this.

**Comment by Manno15** [comment]
I'm taking over this issue from @jzgithub1

**Comment by hkeebler** [comment]
I'm taking this over from @Manno15

**Comment by hkeebler** [comment]
@mikewalch the properties are printed at the start of services: master, tserver, monitor, tracer.  Can you explain better what is being asked here?  Are you looking for an additional info message that says using "general.dynamic.classpath" (because it is set to something) vs. "general.classpath" (because it is empty)?

**Comment by ctubbsii** [comment]
@hkeebler The properties are deprecated as of #885. The preferred way of setting a class path is to set the CLASSPATH environment variable in `conf/accumulo-env.sh` (or whatever environment is appropriate for a user's particular deployment). This replaces the `general.classpaths` configuration property.

As for the `general.dynamic.classpaths` property, that should also be deprecated. The dynamic class loading features are not, and have never been, stable in Accumulo. We were trying to provide a reasonable mechanism for users to drop in user code without restarting the servers, but this was always unreliable. Users can achieve a similar result by using a custom class loader (of their choosing) and configuring it appropriately, using built-in Java features to specify the system class loader with a system property: `-Djava.system.class.loader=com.test.YourCustomClassLoader`.

So, for this issue, we just want to mark the properties deprecated, and then print a warning if they are set by the user, to highlight the fact that they are deprecated.

**Comment by hkeebler** [comment]
Thank you.  That makes sense.

**Comment by hkeebler** [comment]
@ctubbsii  If a property is set and is deprecated a warning is logged by server.ServerUtil in the respective service log at system startup.  The general.dynamic.classpath property is 'zk mutable: no'  and cannot be set in the shell or java api InstanceOperation.setProperty() so I believe it is already properly logging the deprecation.

The only change here,   I believe, is to mark the property deprecated in Property.java.  Additionally, since the property is deprecated I removed the defaultValue - seemed to make sense.

Note that the properties are printed at service startup with empty values.  What if an empty property with deprecated set NOT be printed?

**Comment by ctubbsii** [comment]
Marking the property `@Deprecated` in Property.java should also affect the generated documentation, if I remember correctly.

> What if an empty property with deprecated set NOT be printed?

I think you're suggesting that we stop printing deprecated properties that aren't set? If so, I think that could be a good idea, but I can also see it being useful to somebody debugging to explicitly see in the logs that the property wasn't set. I don't have a strong opinion either way.
