### ISSUE TITLE
Optimize generation of custom props map in ServiceEnvironmentImpl

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#947]
This is follow on work to #941.  In that change ServiceEnvironmentImpl.getCustom() and getTableCustom() were introduced.  The implementation of those method could be optimized to only recompute the maps when config changes.   AccumuloConfig has an atomic counter that is update each time it changes. This can be used to cache the custom maps and only recompute them when the counter changes.

**Comment by DomGarguilo** [comment]
Is this issue obsolete? The referenced methods getCustom() and getTableCustom() no longer exist in ServiceEnvironmentImpl.java

**Comment by ctubbsii** [comment]
> Is this issue obsolete? The referenced methods getCustom() and getTableCustom() no longer exist in ServiceEnvironmentImpl.java

It looks like the implementation moved to core/src/main/java/org/apache/accumulo/core/util/ConfigurationImpl.java

As for the proposed change, I'm not sure exactly what is being proposed.

**Comment by DomGarguilo** [comment]
I would like to be assigned to this ticket please.

**Comment by EdColeman** [comment]
If these changes involve reading properties from zookeeper - could you hold off - the storage of those is close to being changed.

**Comment by DomGarguilo** [comment]
> If these changes involve reading properties from zookeeper - could you hold off - the storage of those is close to being changed.

Yes, will do.

**Comment by DomGarguilo** [comment]
After a bit of investigation, this may not be an issue. The proposed change is to cache the props map in question and only update it if the configuration changes. However, the props maps are only ever generated once, when they are null. Assuming this is correct, this may not be an issue.

During my investigation I did look into the mentioned counter that is updated when AccumuloConfig changes however the getter for this counter AccumuloConfig.getUpdateCount() returns 0 instead of the counters value. It seems this variable is used as mentioned, to determine when to recompute or when to use the cached map. From what I can tell this is an error and will always cause the updateCounter comparisons to fail causing the props maps to be recomputed every time. I'm not certain whether this is behaving correctly or not so I wanted to get a second opinion. I'll create a separate issue if needed.

**Comment by keith-turner** [comment]
> However, the props maps are only ever generated once, when they are null (see getCustom() and getTableCustom()). Assuming this is correct, this may not be an issue.

Yeah I think the caching solves this issue.  I also like the caching as it provides a consistent snapshot of those props to plugins.  There is a comment that could be removed [here](https://github.com/apache/accumulo/blob/3c039c75ba257c9ff47e0b09be53ef12665ddc74/core/src/main/java/org/apache/accumulo/core/util/ConfigurationImpl.java#L110).

Looking at the code in ConfigurationImpl, it seems like it may provide a consistent snapshot of the custom props but not other props.  That seems like a wild and wacky user experience (also related to wider discussion I have had w/ @ctubbsii  in the past about making all of Accumulo's config operate on consistent snapshots), but if we wanted to address that it would be another issue.  I think the comment can be removed and this issue could be closed.

**Comment by DomGarguilo** [comment]
Okay sounds good, thanks.

>  I think the comment can be removed and this issue could be closed.

I'll go ahead and do that.

**Comment by ctubbsii** [comment]
Based on the above conversation, I'll go ahead and close this issue. @DomGarguilo , feel free to make a PR to remove the comment. That PR doesn't have to depend on this issue being open, since this issue describes something else entirely.
